
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.ComponentModel.TypeConverter", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// {0} Array
        /// </summary>
        internal static string Array
        {
            get
            {
                return ResourceManager.GetString("Array", resourceCulture);
            }
        }


        internal static string FormatArray(object arg1)
        {
            return string.Format(Array, arg1);
        }


        /// <summary>
        /// (Collection)
        /// </summary>
        internal static string Collection
        {
            get
            {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }



        /// <summary>
        /// {0} cannot convert from {1}.
        /// </summary>
        internal static string ConvertFromException
        {
            get
            {
                return ResourceManager.GetString("ConvertFromException", resourceCulture);
            }
        }


        internal static string FormatConvertFromException(object arg1, object arg2)
        {
            return string.Format(ConvertFromException, arg1, arg2);
        }


        /// <summary>
        /// {0} is not a valid value for {1}.
        /// </summary>
        internal static string ConvertInvalidPrimitive
        {
            get
            {
                return ResourceManager.GetString("ConvertInvalidPrimitive", resourceCulture);
            }
        }


        internal static string FormatConvertInvalidPrimitive(object arg1, object arg2)
        {
            return string.Format(ConvertInvalidPrimitive, arg1, arg2);
        }


        /// <summary>
        /// '{0}' is unable to convert '{1}' to '{2}'.
        /// </summary>
        internal static string ConvertToException
        {
            get
            {
                return ResourceManager.GetString("ConvertToException", resourceCulture);
            }
        }


        internal static string FormatConvertToException(object arg1, object arg2, object arg3)
        {
            return string.Format(ConvertToException, arg1, arg2, arg3);
        }


        /// <summary>
        /// The value '{0}' is not a valid value for the enum '{1}'.
        /// </summary>
        internal static string EnumConverterInvalidValue
        {
            get
            {
                return ResourceManager.GetString("EnumConverterInvalidValue", resourceCulture);
            }
        }


        internal static string FormatEnumConverterInvalidValue(object arg1, object arg2)
        {
            return string.Format(EnumConverterInvalidValue, arg1, arg2);
        }


        /// <summary>
        /// Type provided must be an Enum.
        /// </summary>
        internal static string EnumInvalidValue
        {
            get
            {
                return ResourceManager.GetString("EnumInvalidValue", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid event handler for the {0} event.
        /// </summary>
        internal static string ErrorInvalidEventHandler
        {
            get
            {
                return ResourceManager.GetString("ErrorInvalidEventHandler", resourceCulture);
            }
        }


        internal static string FormatErrorInvalidEventHandler(object arg1)
        {
            return string.Format(ErrorInvalidEventHandler, arg1);
        }


        /// <summary>
        /// Invalid type for the {0} event.
        /// </summary>
        internal static string ErrorInvalidEventType
        {
            get
            {
                return ResourceManager.GetString("ErrorInvalidEventType", resourceCulture);
            }
        }


        internal static string FormatErrorInvalidEventType(object arg1)
        {
            return string.Format(ErrorInvalidEventType, arg1);
        }


        /// <summary>
        /// Invalid type for the {0} property
        /// </summary>
        internal static string ErrorInvalidPropertyType
        {
            get
            {
                return ResourceManager.GetString("ErrorInvalidPropertyType", resourceCulture);
            }
        }


        internal static string FormatErrorInvalidPropertyType(object arg1)
        {
            return string.Format(ErrorInvalidPropertyType, arg1);
        }


        /// <summary>
        /// Accessor methods for the {0} event are missing.
        /// </summary>
        internal static string ErrorMissingEventAccessors
        {
            get
            {
                return ResourceManager.GetString("ErrorMissingEventAccessors", resourceCulture);
            }
        }


        internal static string FormatErrorMissingEventAccessors(object arg1)
        {
            return string.Format(ErrorMissingEventAccessors, arg1);
        }


        /// <summary>
        /// Accessor methods for the {0} property are missing.
        /// </summary>
        internal static string ErrorMissingPropertyAccessors
        {
            get
            {
                return ResourceManager.GetString("ErrorMissingPropertyAccessors", resourceCulture);
            }
        }


        internal static string FormatErrorMissingPropertyAccessors(object arg1)
        {
            return string.Format(ErrorMissingPropertyAccessors, arg1);
        }


        /// <summary>
        /// Invalid member name
        /// </summary>
        internal static string InvalidMemberName
        {
            get
            {
                return ResourceManager.GetString("InvalidMemberName", resourceCulture);
            }
        }



        /// <summary>
        /// (none)
        /// </summary>
        internal static string none
        {
            get
            {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }



        /// <summary>
        /// (null)
        /// </summary>
        internal static string Null
        {
            get
            {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }



        /// <summary>
        /// The specified type is not a nullable type.
        /// </summary>
        internal static string NullableConverterBadCtorArg
        {
            get
            {
                return ResourceManager.GetString("NullableConverterBadCtorArg", resourceCulture);
            }
        }



        /// <summary>
        /// Runtime instantiation of this attribute is not allowed.
        /// </summary>
        internal static string RuntimeInstanceNotAllowed
        {
            get
            {
                return ResourceManager.GetString("RuntimeInstanceNotAllowed", resourceCulture);
            }
        }



        /// <summary>
        /// (Text)
        /// </summary>
        internal static string Text
        {
            get
            {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }



        /// <summary>
        /// The primary and secondary objects are already associated with each other.
        /// </summary>
        internal static string TypeDescriptorAlreadyAssociated
        {
            get
            {
                return ResourceManager.GetString("TypeDescriptorAlreadyAssociated", resourceCulture);
            }
        }



        /// <summary>
        /// The number of elements in the Type and Object arrays must match.
        /// </summary>
        internal static string TypeDescriptorArgsCountMismatch
        {
            get
            {
                return ResourceManager.GetString("TypeDescriptorArgsCountMismatch", resourceCulture);
            }
        }



        /// <summary>
        /// The type description provider {0} has returned null from {1} which is illegal.
        /// </summary>
        internal static string TypeDescriptorProviderError
        {
            get
            {
                return ResourceManager.GetString("TypeDescriptorProviderError", resourceCulture);
            }
        }


        internal static string FormatTypeDescriptorProviderError(object arg1, object arg2)
        {
            return string.Format(TypeDescriptorProviderError, arg1, arg2);
        }


        /// <summary>
        /// Expected types in the collection to be of type {0}.
        /// </summary>
        internal static string TypeDescriptorExpectedElementType
        {
            get
            {
                return ResourceManager.GetString("TypeDescriptorExpectedElementType", resourceCulture);
            }
        }


        internal static string FormatTypeDescriptorExpectedElementType(object arg1)
        {
            return string.Format(TypeDescriptorExpectedElementType, arg1);
        }


        /// <summary>
        /// Cannot create an association when the primary and secondary objects are the same.
        /// </summary>
        internal static string TypeDescriptorSameAssociation
        {
            get
            {
                return ResourceManager.GetString("TypeDescriptorSameAssociation", resourceCulture);
            }
        }



        /// <summary>
        /// Color '{0}' is not valid.
        /// </summary>
        internal static string InvalidColor
        {
            get
            {
                return ResourceManager.GetString("InvalidColor", resourceCulture);
            }
        }


        internal static string FormatInvalidColor(object arg1)
        {
            return string.Format(InvalidColor, arg1);
        }


        /// <summary>
        /// Text "{0}" cannot be parsed. The expected text format is "{1}".
        /// </summary>
        internal static string TextParseFailedFormat
        {
            get
            {
                return ResourceManager.GetString("TextParseFailedFormat", resourceCulture);
            }
        }


        internal static string FormatTextParseFailedFormat(object arg1, object arg2)
        {
            return string.Format(TextParseFailedFormat, arg1, arg2);
        }


        /// <summary>
        /// IDictionary parameter contains at least one entry that is not valid. Ensure all values are consistent with the object's properties.
        /// </summary>
        internal static string PropertyValueInvalidEntry
        {
            get
            {
                return ResourceManager.GetString("PropertyValueInvalidEntry", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid value '{1}' for parameter '{0}'.
        /// </summary>
        internal static string InvalidParameter
        {
            get
            {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }


        internal static string FormatInvalidParameter(object arg1, object arg2)
        {
            return string.Format(InvalidParameter, arg1, arg2);
        }


        /// <summary>
        /// Indicates whether the timer will be restarted when it is enabled.
        /// </summary>
        internal static string TimerAutoReset
        {
            get
            {
                return ResourceManager.GetString("TimerAutoReset", resourceCulture);
            }
        }



        /// <summary>
        /// Indicates whether the timer is enabled to fire events at a defined interval.
        /// </summary>
        internal static string TimerEnabled
        {
            get
            {
                return ResourceManager.GetString("TimerEnabled", resourceCulture);
            }
        }



        /// <summary>
        /// The number of milliseconds between timer events.
        /// </summary>
        internal static string TimerInterval
        {
            get
            {
                return ResourceManager.GetString("TimerInterval", resourceCulture);
            }
        }



        /// <summary>
        /// Occurs when the Interval has elapsed.
        /// </summary>
        internal static string TimerIntervalElapsed
        {
            get
            {
                return ResourceManager.GetString("TimerIntervalElapsed", resourceCulture);
            }
        }



        /// <summary>
        /// '{0}' is not a valid value for 'Interval'. 'Interval' must be greater than {1}.
        /// </summary>
        internal static string TimerInvalidInterval
        {
            get
            {
                return ResourceManager.GetString("TimerInvalidInterval", resourceCulture);
            }
        }


        internal static string FormatTimerInvalidInterval(object arg1, object arg2)
        {
            return string.Format(TimerInvalidInterval, arg1, arg2);
        }


        /// <summary>
        /// The object used to marshal the event handler calls issued when an interval has elapsed.
        /// </summary>
        internal static string TimerSynchronizingObject
        {
            get
            {
                return ResourceManager.GetString("TimerSynchronizingObject", resourceCulture);
            }
        }



        /// <summary>
        /// Failed to create ToolboxItem of type: {0}
        /// </summary>
        internal static string ToolboxItemAttributeFailedGetType
        {
            get
            {
                return ResourceManager.GetString("ToolboxItemAttributeFailedGetType", resourceCulture);
            }
        }


        internal static string FormatToolboxItemAttributeFailedGetType(object arg1)
        {
            return string.Format(ToolboxItemAttributeFailedGetType, arg1);
        }


        /// <summary>
        /// Scope must be PropertyTabScope.Document or PropertyTabScope.Component
        /// </summary>
        internal static string PropertyTabAttributeBadPropertyTabScope
        {
            get
            {
                return ResourceManager.GetString("PropertyTabAttributeBadPropertyTabScope", resourceCulture);
            }
        }



        /// <summary>
        /// Couldn't find type {0}
        /// </summary>
        internal static string PropertyTabAttributeTypeLoadException
        {
            get
            {
                return ResourceManager.GetString("PropertyTabAttributeTypeLoadException", resourceCulture);
            }
        }


        internal static string FormatPropertyTabAttributeTypeLoadException(object arg1)
        {
            return string.Format(PropertyTabAttributeTypeLoadException, arg1);
        }


        /// <summary>
        /// tabClasses must have the same number of items as tabScopes
        /// </summary>
        internal static string PropertyTabAttributeArrayLengthMismatch
        {
            get
            {
                return ResourceManager.GetString("PropertyTabAttributeArrayLengthMismatch", resourceCulture);
            }
        }



        /// <summary>
        /// An array of tab type names or tab types must be specified
        /// </summary>
        internal static string PropertyTabAttributeParamsBothNull
        {
            get
            {
                return ResourceManager.GetString("PropertyTabAttributeParamsBothNull", resourceCulture);
            }
        }



        /// <summary>
        /// COM object type descriptor functionality has been disabled in the app configuration and is not supported.
        /// </summary>
        internal static string ComObjectDescriptorsNotSupported
        {
            get
            {
                return ResourceManager.GetString("ComObjectDescriptorsNotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// (Default)
        /// </summary>
        internal static string CultureInfoConverterDefaultCultureString
        {
            get
            {
                return ResourceManager.GetString("CultureInfoConverterDefaultCultureString", resourceCulture);
            }
        }



        /// <summary>
        /// The {0} culture cannot be converted to a CultureInfo object on this computer.
        /// </summary>
        internal static string CultureInfoConverterInvalidCulture
        {
            get
            {
                return ResourceManager.GetString("CultureInfoConverterInvalidCulture", resourceCulture);
            }
        }


        internal static string FormatCultureInfoConverterInvalidCulture(object arg1)
        {
            return string.Format(CultureInfoConverterInvalidCulture, arg1);
        }


        /// <summary>
        /// Designer support has been disabled in the app configuration and is not supported.
        /// </summary>
        internal static string IDesignerHostNotSupported
        {
            get
            {
                return ResourceManager.GetString("IDesignerHostNotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// The service instance must derive from or implement {0}.
        /// </summary>
        internal static string ErrorInvalidServiceInstance
        {
            get
            {
                return ResourceManager.GetString("ErrorInvalidServiceInstance", resourceCulture);
            }
        }


        internal static string FormatErrorInvalidServiceInstance(object arg1)
        {
            return string.Format(ErrorInvalidServiceInstance, arg1);
        }


        /// <summary>
        /// The service {0} already exists in the service container.
        /// </summary>
        internal static string ErrorServiceExists
        {
            get
            {
                return ResourceManager.GetString("ErrorServiceExists", resourceCulture);
            }
        }


        internal static string FormatErrorServiceExists(object arg1)
        {
            return string.Format(ErrorServiceExists, arg1);
        }


        /// <summary>
        /// Value of '{0}' cannot be empty.
        /// </summary>
        internal static string InvalidArgumentValue
        {
            get
            {
                return ResourceManager.GetString("InvalidArgumentValue", resourceCulture);
            }
        }


        internal static string FormatInvalidArgumentValue(object arg1)
        {
            return string.Format(InvalidArgumentValue, arg1);
        }


        /// <summary>
        /// Null is not a valid value for {0}.
        /// </summary>
        internal static string InvalidNullArgument
        {
            get
            {
                return ResourceManager.GetString("InvalidNullArgument", resourceCulture);
            }
        }


        internal static string FormatInvalidNullArgument(object arg1)
        {
            return string.Format(InvalidNullArgument, arg1);
        }


        /// <summary>
        /// Duplicate component name '{0}'. Component names must be unique and case-insensitive.
        /// </summary>
        internal static string DuplicateComponentName
        {
            get
            {
                return ResourceManager.GetString("DuplicateComponentName", resourceCulture);
            }
        }


        internal static string FormatDuplicateComponentName(object arg1)
        {
            return string.Format(DuplicateComponentName, arg1);
        }


        /// <summary>
        /// The PasswordChar and PromptChar values cannot be the same.
        /// </summary>
        internal static string MaskedTextProviderPasswordAndPromptCharError
        {
            get
            {
                return ResourceManager.GetString("MaskedTextProviderPasswordAndPromptCharError", resourceCulture);
            }
        }



        /// <summary>
        /// The specified character value is not allowed for this property.
        /// </summary>
        internal static string MaskedTextProviderInvalidCharError
        {
            get
            {
                return ResourceManager.GetString("MaskedTextProviderInvalidCharError", resourceCulture);
            }
        }



        /// <summary>
        /// The specified mask contains invalid characters.
        /// </summary>
        internal static string MaskedTextProviderMaskInvalidChar
        {
            get
            {
                return ResourceManager.GetString("MaskedTextProviderMaskInvalidChar", resourceCulture);
            }
        }



        /// <summary>
        /// Parameter cannot be static.
        /// </summary>
        internal static string InstanceDescriptorCannotBeStatic
        {
            get
            {
                return ResourceManager.GetString("InstanceDescriptorCannotBeStatic", resourceCulture);
            }
        }



        /// <summary>
        /// Parameter must be static.
        /// </summary>
        internal static string InstanceDescriptorMustBeStatic
        {
            get
            {
                return ResourceManager.GetString("InstanceDescriptorMustBeStatic", resourceCulture);
            }
        }



        /// <summary>
        /// Parameter must be readable.
        /// </summary>
        internal static string InstanceDescriptorMustBeReadable
        {
            get
            {
                return ResourceManager.GetString("InstanceDescriptorMustBeReadable", resourceCulture);
            }
        }



        /// <summary>
        /// Length mismatch.
        /// </summary>
        internal static string InstanceDescriptorLengthMismatch
        {
            get
            {
                return ResourceManager.GetString("InstanceDescriptorLengthMismatch", resourceCulture);
            }
        }



        /// <summary>
        /// {0} on {1}
        /// </summary>
        internal static string MetaExtenderName
        {
            get
            {
                return ResourceManager.GetString("MetaExtenderName", resourceCulture);
            }
        }


        internal static string FormatMetaExtenderName(object arg1, object arg2)
        {
            return string.Format(MetaExtenderName, arg1, arg2);
        }


        /// <summary>
        /// Once a ListSortDescriptionCollection has been created it can't be modified.
        /// </summary>
        internal static string CantModifyListSortDescriptionCollection
        {
            get
            {
                return ResourceManager.GetString("CantModifyListSortDescriptionCollection", resourceCulture);
            }
        }



        /// <summary>
        /// A valid license cannot be granted for the type {0}. Contact the manufacturer of the component for more information.
        /// </summary>
        internal static string LicExceptionTypeOnly
        {
            get
            {
                return ResourceManager.GetString("LicExceptionTypeOnly", resourceCulture);
            }
        }


        internal static string FormatLicExceptionTypeOnly(object arg1)
        {
            return string.Format(LicExceptionTypeOnly, arg1);
        }


        /// <summary>
        /// An instance of type '{1}' was being created, and a valid license could not be granted for the type '{0}'. Please,  contact the manufacturer of the component for more information.
        /// </summary>
        internal static string LicExceptionTypeAndInstance
        {
            get
            {
                return ResourceManager.GetString("LicExceptionTypeAndInstance", resourceCulture);
            }
        }


        internal static string FormatLicExceptionTypeAndInstance(object arg1, object arg2)
        {
            return string.Format(LicExceptionTypeAndInstance, arg1, arg2);
        }


        /// <summary>
        /// The CurrentContext property of the LicenseManager is currently locked and cannot be changed.
        /// </summary>
        internal static string LicMgrContextCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("LicMgrContextCannotBeChanged", resourceCulture);
            }
        }



        /// <summary>
        /// The CurrentContext property of the LicenseManager is already locked by another user.
        /// </summary>
        internal static string LicMgrAlreadyLocked
        {
            get
            {
                return ResourceManager.GetString("LicMgrAlreadyLocked", resourceCulture);
            }
        }



        /// <summary>
        /// The CurrentContext property of the LicenseManager can only be unlocked with the same contextUser.
        /// </summary>
        internal static string LicMgrDifferentUser
        {
            get
            {
                return ResourceManager.GetString("LicMgrDifferentUser", resourceCulture);
            }
        }



        /// <summary>
        /// (Collection)
        /// </summary>
        internal static string CollectionConverterText
        {
            get
            {
                return ResourceManager.GetString("CollectionConverterText", resourceCulture);
            }
        }



        /// <summary>
        /// (New...)
        /// </summary>
        internal static string InstanceCreationEditorDefaultText
        {
            get
            {
                return ResourceManager.GetString("InstanceCreationEditorDefaultText", resourceCulture);
            }
        }



        /// <summary>
        /// Property accessor '{0}' on object '{1}' threw the following exception:'{2}'
        /// </summary>
        internal static string ErrorPropertyAccessorException
        {
            get
            {
                return ResourceManager.GetString("ErrorPropertyAccessorException", resourceCulture);
            }
        }


        internal static string FormatErrorPropertyAccessorException(object arg1, object arg2, object arg3)
        {
            return string.Format(ErrorPropertyAccessorException, arg1, arg2, arg3);
        }


        /// <summary>
        /// The checkout was canceled by the user.
        /// </summary>
        internal static string CHECKOUTCanceled
        {
            get
            {
                return ResourceManager.GetString("CHECKOUTCanceled", resourceCulture);
            }
        }



        /// <summary>
        /// (none)
        /// </summary>
        internal static string toStringNone
        {
            get
            {
                return ResourceManager.GetString("toStringNone", resourceCulture);
            }
        }



        /// <summary>
        /// Relationships between {0}.{1} and {2}.{3} are not supported.
        /// </summary>
        internal static string MemberRelationshipService_RelationshipNotSupported
        {
            get
            {
                return ResourceManager.GetString("MemberRelationshipService_RelationshipNotSupported", resourceCulture);
            }
        }


        internal static string FormatMemberRelationshipService_RelationshipNotSupported(object arg1, object arg2, object arg3, object arg4)
        {
            return string.Format(MemberRelationshipService_RelationshipNotSupported, arg1, arg2, arg3, arg4);
        }


        /// <summary>
        /// BinaryFormatter serialization is obsolete and should not be used. See https://aka.ms/binaryformatter for more information.
        /// </summary>
        internal static string BinaryFormatterMessage
        {
            get
            {
                return ResourceManager.GetString("BinaryFormatterMessage", resourceCulture);
            }
        }



        /// <summary>
        /// The type {0} is not registered. Call 'TypeDescriptor.RegisterType()' to register the type.
        /// </summary>
        internal static string TypeIsNotRegistered
        {
            get
            {
                return ResourceManager.GetString("TypeIsNotRegistered", resourceCulture);
            }
        }


        internal static string FormatTypeIsNotRegistered(object arg1)
        {
            return string.Format(TypeIsNotRegistered, arg1);
        }


        /// <summary>
        /// Custom type providers must implement member {0}.
        /// </summary>
        internal static string CustomTypeProviderNotImplemented
        {
            get
            {
                return ResourceManager.GetString("CustomTypeProviderNotImplemented", resourceCulture);
            }
        }


        internal static string FormatCustomTypeProviderNotImplemented(object arg1)
        {
            return string.Format(CustomTypeProviderNotImplemented, arg1);
        }
    }
}
