
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Runtime.InteropServices.JavaScript", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Invalid argument: {0} can not be null.
        /// </summary>
        internal static string ArgumentCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("ArgumentCannotBeNull", resourceCulture);
            }
        }


        internal static string FormatArgumentCannotBeNull(object arg1)
        {
            return string.Format(ArgumentCannotBeNull, arg1);
        }


        /// <summary>
        /// Invalid argument: {0} can not be null and must have a length.
        /// </summary>
        internal static string ArgumentCannotBeNullWithLength
        {
            get
            {
                return ResourceManager.GetString("ArgumentCannotBeNullWithLength", resourceCulture);
            }
        }


        internal static string FormatArgumentCannotBeNullWithLength(object arg1)
        {
            return string.Format(ArgumentCannotBeNullWithLength, arg1);
        }


        /// <summary>
        /// System.Runtime.InteropServices.JavaScript is not supported on this platform.
        /// </summary>
        internal static string SystemRuntimeInteropServicesJavaScript_PlatformNotSupported
        {
            get
            {
                return ResourceManager.GetString("SystemRuntimeInteropServicesJavaScript_PlatformNotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// TypedArray is not of correct type.
        /// </summary>
        internal static string TypedArrayNotCorrectType
        {
            get
            {
                return ResourceManager.GetString("TypedArrayNotCorrectType", resourceCulture);
            }
        }



        /// <summary>
        /// Unable to cast null to type {0}.
        /// </summary>
        internal static string UnableCastNullToType
        {
            get
            {
                return ResourceManager.GetString("UnableCastNullToType", resourceCulture);
            }
        }


        internal static string FormatUnableCastNullToType(object arg1)
        {
            return string.Format(UnableCastNullToType, arg1);
        }


        /// <summary>
        /// Unable to cast object of type {0} to type {1}.
        /// </summary>
        internal static string UnableCastObjectToType
        {
            get
            {
                return ResourceManager.GetString("UnableCastObjectToType", resourceCulture);
            }
        }


        internal static string FormatUnableCastObjectToType(object arg1, object arg2)
        {
            return string.Format(UnableCastObjectToType, arg1, arg2);
        }


        /// <summary>
        /// Managed entrypoint handle is not set.
        /// </summary>
        internal static string MissingManagedEntrypointHandle
        {
            get
            {
                return ResourceManager.GetString("MissingManagedEntrypointHandle", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot resolve managed entrypoint handle.
        /// </summary>
        internal static string CannotResolveManagedEntrypointHandle
        {
            get
            {
                return ResourceManager.GetString("CannotResolveManagedEntrypointHandle", resourceCulture);
            }
        }



        /// <summary>
        /// Return type '{0}' from main method in not supported.
        /// </summary>
        internal static string ReturnTypeNotSupportedForMain
        {
            get
            {
                return ResourceManager.GetString("ReturnTypeNotSupportedForMain", resourceCulture);
            }
        }


        internal static string FormatReturnTypeNotSupportedForMain(object arg1)
        {
            return string.Format(ReturnTypeNotSupportedForMain, arg1);
        }


        /// <summary>
        /// ToManagedCallback is null.
        /// </summary>
        internal static string NullToManagedCallback
        {
            get
            {
                return ResourceManager.GetString("NullToManagedCallback", resourceCulture);
            }
        }



        /// <summary>
        /// PromiseHolder is null.
        /// </summary>
        internal static string NullPromiseHolder
        {
            get
            {
                return ResourceManager.GetString("NullPromiseHolder", resourceCulture);
            }
        }



        /// <summary>
        /// Empty profile data.
        /// </summary>
        internal static string EmptyProfileData
        {
            get
            {
                return ResourceManager.GetString("EmptyProfileData", resourceCulture);
            }
        }



        /// <summary>
        /// Error setting {0} on (js-obj js '{1}'): {2}.
        /// </summary>
        internal static string ErrorLegacySettingProperty
        {
            get
            {
                return ResourceManager.GetString("ErrorLegacySettingProperty", resourceCulture);
            }
        }


        internal static string FormatErrorLegacySettingProperty(object arg1, object arg2, object arg3)
        {
            return string.Format(ErrorLegacySettingProperty, arg1, arg2, arg3);
        }


        /// <summary>
        /// Error resolving property {0} from globalThis.
        /// </summary>
        internal static string ErrorResolvingFromGlobalThis
        {
            get
            {
                return ResourceManager.GetString("ErrorResolvingFromGlobalThis", resourceCulture);
            }
        }


        internal static string FormatErrorResolvingFromGlobalThis(object arg1)
        {
            return string.Format(ErrorResolvingFromGlobalThis, arg1);
        }


        /// <summary>
        /// Failed to marshal exception.
        /// </summary>
        internal static string FailedToMarshalException
        {
            get
            {
                return ResourceManager.GetString("FailedToMarshalException", resourceCulture);
            }
        }



        /// <summary>
        /// Failed to marshal Promise callback.
        /// </summary>
        internal static string FailedToMarshalPromiseHolder
        {
            get
            {
                return ResourceManager.GetString("FailedToMarshalPromiseHolder", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid InFlightCounter for JSObject {0}, expected: {1}, actual: {2}.
        /// </summary>
        internal static string InvalidInFlightCounter
        {
            get
            {
                return ResourceManager.GetString("InvalidInFlightCounter", resourceCulture);
            }
        }


        internal static string FormatInvalidInFlightCounter(object arg1, object arg2, object arg3)
        {
            return string.Format(InvalidInFlightCounter, arg1, arg2, arg3);
        }


        /// <summary>
        /// ToJS for {0} is not implemented.
        /// </summary>
        internal static string ToJSNotImplemented
        {
            get
            {
                return ResourceManager.GetString("ToJSNotImplemented", resourceCulture);
            }
        }


        internal static string FormatToJSNotImplemented(object arg1)
        {
            return string.Format(ToJSNotImplemented, arg1);
        }


        /// <summary>
        /// ToManaged for {0} is not implemented.
        /// </summary>
        internal static string ToManagedNotImplemented
        {
            get
            {
                return ResourceManager.GetString("ToManagedNotImplemented", resourceCulture);
            }
        }


        internal static string FormatToManagedNotImplemented(object arg1)
        {
            return string.Format(ToManagedNotImplemented, arg1);
        }


        /// <summary>
        /// Unable to resolve the handle as an Exception.
        /// </summary>
        internal static string UnableToResolveHandleAsException
        {
            get
            {
                return ResourceManager.GetString("UnableToResolveHandleAsException", resourceCulture);
            }
        }



        /// <summary>
        /// Unsupported array type {0}. Only single-dimensional arrays with a zero lower bound can be marshaled to JS.
        /// </summary>
        internal static string UnsupportedArrayType
        {
            get
            {
                return ResourceManager.GetString("UnsupportedArrayType", resourceCulture);
            }
        }


        internal static string FormatUnsupportedArrayType(object arg1)
        {
            return string.Format(UnsupportedArrayType, arg1);
        }


        /// <summary>
        /// Unsupported element type {0}.
        /// </summary>
        internal static string UnsupportedElementType
        {
            get
            {
                return ResourceManager.GetString("UnsupportedElementType", resourceCulture);
            }
        }


        internal static string FormatUnsupportedElementType(object arg1)
        {
            return string.Format(UnsupportedElementType, arg1);
        }


        /// <summary>
        /// Unsupported enum type {0}.
        /// </summary>
        internal static string UnsupportedEnumType
        {
            get
            {
                return ResourceManager.GetString("UnsupportedEnumType", resourceCulture);
            }
        }


        internal static string FormatUnsupportedEnumType(object arg1)
        {
            return string.Format(UnsupportedEnumType, arg1);
        }


        /// <summary>
        /// Unsupported marshal type {0}.
        /// </summary>
        internal static string UnsupportedLegacyMarshlerType
        {
            get
            {
                return ResourceManager.GetString("UnsupportedLegacyMarshlerType", resourceCulture);
            }
        }


        internal static string FormatUnsupportedLegacyMarshlerType(object arg1)
        {
            return string.Format(UnsupportedLegacyMarshlerType, arg1);
        }


        /// <summary>
        /// Unsupported nullable type {0}.
        /// </summary>
        internal static string UnsupportedNullableType
        {
            get
            {
                return ResourceManager.GetString("UnsupportedNullableType", resourceCulture);
            }
        }


        internal static string FormatUnsupportedNullableType(object arg1)
        {
            return string.Format(UnsupportedNullableType, arg1);
        }


        /// <summary>
        /// Unsupported task result type {0}.
        /// </summary>
        internal static string UnsupportedTaskResultType
        {
            get
            {
                return ResourceManager.GetString("UnsupportedTaskResultType", resourceCulture);
            }
        }


        internal static string FormatUnsupportedTaskResultType(object arg1)
        {
            return string.Format(UnsupportedTaskResultType, arg1);
        }


        /// <summary>
        /// Constructor on type 'System.Uri' not found. Please consider to protect it's constructor from trimming.
        /// </summary>
        internal static string UriConstructorMissing
        {
            get
            {
                return ResourceManager.GetString("UriConstructorMissing", resourceCulture);
            }
        }



        /// <summary>
        /// The type System.Uri could not be found. Please consider to protect the class and it's constructor from trimming.
        /// </summary>
        internal static string UriTypeMissing
        {
            get
            {
                return ResourceManager.GetString("UriTypeMissing", resourceCulture);
            }
        }



        /// <summary>
        /// Overflow: value {0} is out of {1} {2} range.
        /// </summary>
        internal static string ValueOutOf52BitRange
        {
            get
            {
                return ResourceManager.GetString("ValueOutOf52BitRange", resourceCulture);
            }
        }


        internal static string FormatValueOutOf52BitRange(object arg1, object arg2, object arg3)
        {
            return string.Format(ValueOutOf52BitRange, arg1, arg2, arg3);
        }
    }
}
