
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Private.Xml.Linq", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// An attribute cannot be added to content.
        /// </summary>
        internal static string Argument_AddAttribute
        {
            get
            {
                return ResourceManager.GetString("Argument_AddAttribute", resourceCulture);
            }
        }



        /// <summary>
        /// A node of type {0} cannot be added to content.
        /// </summary>
        internal static string Argument_AddNode
        {
            get
            {
                return ResourceManager.GetString("Argument_AddNode", resourceCulture);
            }
        }


        internal static string FormatArgument_AddNode(object arg1)
        {
            return string.Format(Argument_AddNode, arg1);
        }


        /// <summary>
        /// Non-whitespace characters cannot be added to content.
        /// </summary>
        internal static string Argument_AddNonWhitespace
        {
            get
            {
                return ResourceManager.GetString("Argument_AddNonWhitespace", resourceCulture);
            }
        }



        /// <summary>
        /// The argument cannot be converted to a string.
        /// </summary>
        internal static string Argument_ConvertToString
        {
            get
            {
                return ResourceManager.GetString("Argument_ConvertToString", resourceCulture);
            }
        }



        /// <summary>
        /// '{0}' is an invalid expanded name.
        /// </summary>
        internal static string Argument_InvalidExpandedName
        {
            get
            {
                return ResourceManager.GetString("Argument_InvalidExpandedName", resourceCulture);
            }
        }


        internal static string FormatArgument_InvalidExpandedName(object arg1)
        {
            return string.Format(Argument_InvalidExpandedName, arg1);
        }


        /// <summary>
        /// '{0}' is an invalid name for a processing instruction.
        /// </summary>
        internal static string Argument_InvalidPIName
        {
            get
            {
                return ResourceManager.GetString("Argument_InvalidPIName", resourceCulture);
            }
        }


        internal static string FormatArgument_InvalidPIName(object arg1)
        {
            return string.Format(Argument_InvalidPIName, arg1);
        }


        /// <summary>
        /// The argument must be derived from {0}.
        /// </summary>
        internal static string Argument_MustBeDerivedFrom
        {
            get
            {
                return ResourceManager.GetString("Argument_MustBeDerivedFrom", resourceCulture);
            }
        }


        internal static string FormatArgument_MustBeDerivedFrom(object arg1)
        {
            return string.Format(Argument_MustBeDerivedFrom, arg1);
        }


        /// <summary>
        /// The prefix '{0}' cannot be bound to the empty namespace name.
        /// </summary>
        internal static string Argument_NamespaceDeclarationPrefixed
        {
            get
            {
                return ResourceManager.GetString("Argument_NamespaceDeclarationPrefixed", resourceCulture);
            }
        }


        internal static string FormatArgument_NamespaceDeclarationPrefixed(object arg1)
        {
            return string.Format(Argument_NamespaceDeclarationPrefixed, arg1);
        }


        /// <summary>
        /// The prefix 'xml' is bound to the namespace name 'http://www.w3.org/XML/1998/namespace'. Other prefixes must not be bound to this namespace name, and it must not be declared as the default namespace.
        /// </summary>
        internal static string Argument_NamespaceDeclarationXml
        {
            get
            {
                return ResourceManager.GetString("Argument_NamespaceDeclarationXml", resourceCulture);
            }
        }



        /// <summary>
        /// The prefix 'xmlns' is bound to the namespace name 'http://www.w3.org/2000/xmlns/'. It must not be declared. Other prefixes must not be bound to this namespace name, and it must not be declared as the default namespace.
        /// </summary>
        internal static string Argument_NamespaceDeclarationXmlns
        {
            get
            {
                return ResourceManager.GetString("Argument_NamespaceDeclarationXmlns", resourceCulture);
            }
        }



        /// <summary>
        /// An XObject cannot be used as a value.
        /// </summary>
        internal static string Argument_XObjectValue
        {
            get
            {
                return ResourceManager.GetString("Argument_XObjectValue", resourceCulture);
            }
        }



        /// <summary>
        /// This instance cannot be deserialized.
        /// </summary>
        internal static string InvalidOperation_DeserializeInstance
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_DeserializeInstance", resourceCulture);
            }
        }



        /// <summary>
        /// This operation would create an incorrectly structured document.
        /// </summary>
        internal static string InvalidOperation_DocumentStructure
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_DocumentStructure", resourceCulture);
            }
        }



        /// <summary>
        /// Duplicate attribute.
        /// </summary>
        internal static string InvalidOperation_DuplicateAttribute
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_DuplicateAttribute", resourceCulture);
            }
        }



        /// <summary>
        /// The XmlReader state should be EndOfFile after this operation.
        /// </summary>
        internal static string InvalidOperation_ExpectedEndOfFile
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_ExpectedEndOfFile", resourceCulture);
            }
        }



        /// <summary>
        /// The XmlReader state should be Interactive.
        /// </summary>
        internal static string InvalidOperation_ExpectedInteractive
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_ExpectedInteractive", resourceCulture);
            }
        }



        /// <summary>
        /// The XmlReader must be on a node of type {0} instead of a node of type {1}.
        /// </summary>
        internal static string InvalidOperation_ExpectedNodeType
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_ExpectedNodeType", resourceCulture);
            }
        }


        internal static string FormatInvalidOperation_ExpectedNodeType(object arg1, object arg2)
        {
            return string.Format(InvalidOperation_ExpectedNodeType, arg1, arg2);
        }


        /// <summary>
        /// This operation was corrupted by external code.
        /// </summary>
        internal static string InvalidOperation_ExternalCode
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_ExternalCode", resourceCulture);
            }
        }



        /// <summary>
        /// A common ancestor is missing.
        /// </summary>
        internal static string InvalidOperation_MissingAncestor
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_MissingAncestor", resourceCulture);
            }
        }



        /// <summary>
        /// The parent is missing.
        /// </summary>
        internal static string InvalidOperation_MissingParent
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_MissingParent", resourceCulture);
            }
        }



        /// <summary>
        /// The root element is missing.
        /// </summary>
        internal static string InvalidOperation_MissingRoot
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_MissingRoot", resourceCulture);
            }
        }



        /// <summary>
        /// The XmlReader should not be on a node of type {0}.
        /// </summary>
        internal static string InvalidOperation_UnexpectedNodeType
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_UnexpectedNodeType", resourceCulture);
            }
        }


        internal static string FormatInvalidOperation_UnexpectedNodeType(object arg1)
        {
            return string.Format(InvalidOperation_UnexpectedNodeType, arg1);
        }


        /// <summary>
        /// The XmlReader cannot resolve entity references.
        /// </summary>
        internal static string InvalidOperation_UnresolvedEntityReference
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_UnresolvedEntityReference", resourceCulture);
            }
        }



        /// <summary>
        /// An attribute cannot be written after content.
        /// </summary>
        internal static string InvalidOperation_WriteAttribute
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_WriteAttribute", resourceCulture);
            }
        }



        /// <summary>
        /// This XmlWriter does not support base64 encoded data.
        /// </summary>
        internal static string NotSupported_WriteBase64
        {
            get
            {
                return ResourceManager.GetString("NotSupported_WriteBase64", resourceCulture);
            }
        }



        /// <summary>
        /// This XmlWriter does not support entity references.
        /// </summary>
        internal static string NotSupported_WriteEntityRef
        {
            get
            {
                return ResourceManager.GetString("NotSupported_WriteEntityRef", resourceCulture);
            }
        }



        /// <summary>
        /// This XPathNavigator cannot be created on a node of type {0}.
        /// </summary>
        internal static string Argument_CreateNavigator
        {
            get
            {
                return ResourceManager.GetString("Argument_CreateNavigator", resourceCulture);
            }
        }


        internal static string FormatArgument_CreateNavigator(object arg1)
        {
            return string.Format(Argument_CreateNavigator, arg1);
        }


        /// <summary>
        /// This operation is not valid on a node of type {0}.
        /// </summary>
        internal static string InvalidOperation_BadNodeType
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_BadNodeType", resourceCulture);
            }
        }


        internal static string FormatInvalidOperation_BadNodeType(object arg1)
        {
            return string.Format(InvalidOperation_BadNodeType, arg1);
        }


        /// <summary>
        /// The XPath expression evaluated to unexpected type {0}.
        /// </summary>
        internal static string InvalidOperation_UnexpectedEvaluation
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_UnexpectedEvaluation", resourceCulture);
            }
        }


        internal static string FormatInvalidOperation_UnexpectedEvaluation(object arg1)
        {
            return string.Format(InvalidOperation_UnexpectedEvaluation, arg1);
        }


        /// <summary>
        /// This XPathNavigator does not support IDs.
        /// </summary>
        internal static string NotSupported_MoveToId
        {
            get
            {
                return ResourceManager.GetString("NotSupported_MoveToId", resourceCulture);
            }
        }

    }
}
