
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Extensions.Options", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Cannot create instance of type '{0}' because it is either abstract or an interface.
        /// </summary>
        internal static string Error_CannotActivateAbstractOrInterface
        {
            get
            {
                return ResourceManager.GetString("Error_CannotActivateAbstractOrInterface", resourceCulture);
            }
        }


        internal static string FormatError_CannotActivateAbstractOrInterface(object arg1)
        {
            return string.Format(Error_CannotActivateAbstractOrInterface, arg1);
        }


        /// <summary>
        /// Failed to convert '{0}' to type '{1}'.
        /// </summary>
        internal static string Error_FailedBinding
        {
            get
            {
                return ResourceManager.GetString("Error_FailedBinding", resourceCulture);
            }
        }


        internal static string FormatError_FailedBinding(object arg1, object arg2)
        {
            return string.Format(Error_FailedBinding, arg1, arg2);
        }


        /// <summary>
        /// Failed to create instance of type '{0}'.
        /// </summary>
        internal static string Error_FailedToActivate
        {
            get
            {
                return ResourceManager.GetString("Error_FailedToActivate", resourceCulture);
            }
        }


        internal static string FormatError_FailedToActivate(object arg1)
        {
            return string.Format(Error_FailedToActivate, arg1);
        }


        /// <summary>
        /// Cannot create instance of type '{0}' because it is missing a public parameterless constructor.
        /// </summary>
        internal static string Error_MissingParameterlessConstructor
        {
            get
            {
                return ResourceManager.GetString("Error_MissingParameterlessConstructor", resourceCulture);
            }
        }


        internal static string FormatError_MissingParameterlessConstructor(object arg1)
        {
            return string.Format(Error_MissingParameterlessConstructor, arg1);
        }


        /// <summary>
        /// No IConfigureOptions<>, IPostConfigureOptions<>, or IValidateOptions<> implementations were found.
        /// </summary>
        internal static string Error_NoConfigurationServices
        {
            get
            {
                return ResourceManager.GetString("Error_NoConfigurationServices", resourceCulture);
            }
        }



        /// <summary>
        /// No IConfigureOptions<>, IPostConfigureOptions<>, or IValidateOptions<> implementations were found, did you mean to call Configure<> or PostConfigure<>?
        /// </summary>
        internal static string Error_NoConfigurationServicesAndAction
        {
            get
            {
                return ResourceManager.GetString("Error_NoConfigurationServicesAndAction", resourceCulture);
            }
        }

    }
}
