
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Reflection.Metadata", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Image is too small.
        /// </summary>
        internal static string ImageTooSmall
        {
            get
            {
                return ResourceManager.GetString("ImageTooSmall", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid COR header size.
        /// </summary>
        internal static string InvalidCorHeaderSize
        {
            get
            {
                return ResourceManager.GetString("InvalidCorHeaderSize", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid handle.
        /// </summary>
        internal static string InvalidHandle
        {
            get
            {
                return ResourceManager.GetString("InvalidHandle", resourceCulture);
            }
        }



        /// <summary>
        /// Unexpected handle kind: {0}.
        /// </summary>
        internal static string UnexpectedHandleKind
        {
            get
            {
                return ResourceManager.GetString("UnexpectedHandleKind", resourceCulture);
            }
        }


        internal static string FormatUnexpectedHandleKind(object arg1)
        {
            return string.Format(UnexpectedHandleKind, arg1);
        }


        /// <summary>
        /// Unexpected op-code: {0}.
        /// </summary>
        internal static string UnexpectedOpCode
        {
            get
            {
                return ResourceManager.GetString("UnexpectedOpCode", resourceCulture);
            }
        }


        internal static string FormatUnexpectedOpCode(object arg1)
        {
            return string.Format(UnexpectedOpCode, arg1);
        }


        /// <summary>
        /// Invalid local signature token: 0x{0:X8}
        /// </summary>
        internal static string InvalidLocalSignatureToken
        {
            get
            {
                return ResourceManager.GetString("InvalidLocalSignatureToken", resourceCulture);
            }
        }


        internal static string FormatInvalidLocalSignatureToken(object arg1)
        {
            return string.Format(InvalidLocalSignatureToken, arg1);
        }


        /// <summary>
        /// Invalid metadata section span.
        /// </summary>
        internal static string InvalidMetadataSectionSpan
        {
            get
            {
                return ResourceManager.GetString("InvalidMetadataSectionSpan", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid method header: 0x{0:X2}
        /// </summary>
        internal static string InvalidMethodHeader1
        {
            get
            {
                return ResourceManager.GetString("InvalidMethodHeader1", resourceCulture);
            }
        }


        internal static string FormatInvalidMethodHeader1(object arg1)
        {
            return string.Format(InvalidMethodHeader1, arg1);
        }


        /// <summary>
        /// Invalid method header: 0x{0:X2} 0x{1:X2}
        /// </summary>
        internal static string InvalidMethodHeader2
        {
            get
            {
                return ResourceManager.GetString("InvalidMethodHeader2", resourceCulture);
            }
        }


        internal static string FormatInvalidMethodHeader2(object arg1, object arg2)
        {
            return string.Format(InvalidMethodHeader2, arg1, arg2);
        }


        /// <summary>
        /// Invalid PE signature.
        /// </summary>
        internal static string InvalidPESignature
        {
            get
            {
                return ResourceManager.GetString("InvalidPESignature", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid SEH header: 0x{0:X2}
        /// </summary>
        internal static string InvalidSehHeader
        {
            get
            {
                return ResourceManager.GetString("InvalidSehHeader", resourceCulture);
            }
        }


        internal static string FormatInvalidSehHeader(object arg1)
        {
            return string.Format(InvalidSehHeader, arg1);
        }


        /// <summary>
        /// Invalid token.
        /// </summary>
        internal static string InvalidToken
        {
            get
            {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }



        /// <summary>
        /// Metadata image doesn't represent an assembly.
        /// </summary>
        internal static string MetadataImageDoesNotRepresentAnAssembly
        {
            get
            {
                return ResourceManager.GetString("MetadataImageDoesNotRepresentAnAssembly", resourceCulture);
            }
        }



        /// <summary>
        /// Standalone debug metadata image doesn't contain Module table.
        /// </summary>
        internal static string StandaloneDebugMetadataImageDoesNotContainModuleTable
        {
            get
            {
                return ResourceManager.GetString("StandaloneDebugMetadataImageDoesNotContainModuleTable", resourceCulture);
            }
        }



        /// <summary>
        /// PE image not available.
        /// </summary>
        internal static string PEImageNotAvailable
        {
            get
            {
                return ResourceManager.GetString("PEImageNotAvailable", resourceCulture);
            }
        }



        /// <summary>
        /// Missing data directory.
        /// </summary>
        internal static string MissingDataDirectory
        {
            get
            {
                return ResourceManager.GetString("MissingDataDirectory", resourceCulture);
            }
        }



        /// <summary>
        /// Specified handle is not a valid metadata heap handle.
        /// </summary>
        internal static string NotMetadataHeapHandle
        {
            get
            {
                return ResourceManager.GetString("NotMetadataHeapHandle", resourceCulture);
            }
        }



        /// <summary>
        /// Specified handle is not a valid metadata table or UserString heap handle.
        /// </summary>
        internal static string NotMetadataTableOrUserStringHandle
        {
            get
            {
                return ResourceManager.GetString("NotMetadataTableOrUserStringHandle", resourceCulture);
            }
        }



        /// <summary>
        /// Section too small.
        /// </summary>
        internal static string SectionTooSmall
        {
            get
            {
                return ResourceManager.GetString("SectionTooSmall", resourceCulture);
            }
        }



        /// <summary>
        /// Stream must support read and seek operations.
        /// </summary>
        internal static string StreamMustSupportReadAndSeek
        {
            get
            {
                return ResourceManager.GetString("StreamMustSupportReadAndSeek", resourceCulture);
            }
        }



        /// <summary>
        /// Unknown file format.
        /// </summary>
        internal static string UnknownFileFormat
        {
            get
            {
                return ResourceManager.GetString("UnknownFileFormat", resourceCulture);
            }
        }



        /// <summary>
        /// Unknown PE Magic value.
        /// </summary>
        internal static string UnknownPEMagicValue
        {
            get
            {
                return ResourceManager.GetString("UnknownPEMagicValue", resourceCulture);
            }
        }



        /// <summary>
        /// Metadata table {0} not sorted.
        /// </summary>
        internal static string MetadataTableNotSorted
        {
            get
            {
                return ResourceManager.GetString("MetadataTableNotSorted", resourceCulture);
            }
        }


        internal static string FormatMetadataTableNotSorted(object arg1)
        {
            return string.Format(MetadataTableNotSorted, arg1);
        }


        /// <summary>
        /// Invalid number of rows of Module table: {0}.
        /// </summary>
        internal static string ModuleTableInvalidNumberOfRows
        {
            get
            {
                return ResourceManager.GetString("ModuleTableInvalidNumberOfRows", resourceCulture);
            }
        }


        internal static string FormatModuleTableInvalidNumberOfRows(object arg1)
        {
            return string.Format(ModuleTableInvalidNumberOfRows, arg1);
        }


        /// <summary>
        /// Unknown tables: 0x{0:x16}.
        /// </summary>
        internal static string UnknownTables
        {
            get
            {
                return ResourceManager.GetString("UnknownTables", resourceCulture);
            }
        }


        internal static string FormatUnknownTables(object arg1)
        {
            return string.Format(UnknownTables, arg1);
        }


        /// <summary>
        /// Illegal tables in compressed metadata stream.
        /// </summary>
        internal static string IllegalTablesInCompressedMetadataStream
        {
            get
            {
                return ResourceManager.GetString("IllegalTablesInCompressedMetadataStream", resourceCulture);
            }
        }



        /// <summary>
        /// Table row count space to small.
        /// </summary>
        internal static string TableRowCountSpaceTooSmall
        {
            get
            {
                return ResourceManager.GetString("TableRowCountSpaceTooSmall", resourceCulture);
            }
        }



        /// <summary>
        /// Read out of bounds.
        /// </summary>
        internal static string OutOfBoundsRead
        {
            get
            {
                return ResourceManager.GetString("OutOfBoundsRead", resourceCulture);
            }
        }



        /// <summary>
        /// Write out of bounds.
        /// </summary>
        internal static string OutOfBoundsWrite
        {
            get
            {
                return ResourceManager.GetString("OutOfBoundsWrite", resourceCulture);
            }
        }



        /// <summary>
        /// Metadata header too small.
        /// </summary>
        internal static string MetadataHeaderTooSmall
        {
            get
            {
                return ResourceManager.GetString("MetadataHeaderTooSmall", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid COR20 header signature.
        /// </summary>
        internal static string MetadataSignature
        {
            get
            {
                return ResourceManager.GetString("MetadataSignature", resourceCulture);
            }
        }



        /// <summary>
        /// Not enough space for version string.
        /// </summary>
        internal static string NotEnoughSpaceForVersionString
        {
            get
            {
                return ResourceManager.GetString("NotEnoughSpaceForVersionString", resourceCulture);
            }
        }



        /// <summary>
        /// Stream header too small.
        /// </summary>
        internal static string StreamHeaderTooSmall
        {
            get
            {
                return ResourceManager.GetString("StreamHeaderTooSmall", resourceCulture);
            }
        }



        /// <summary>
        /// Not enough space for stream header name.
        /// </summary>
        internal static string NotEnoughSpaceForStreamHeaderName
        {
            get
            {
                return ResourceManager.GetString("NotEnoughSpaceForStreamHeaderName", resourceCulture);
            }
        }



        /// <summary>
        /// Not enough space for String stream.
        /// </summary>
        internal static string NotEnoughSpaceForStringStream
        {
            get
            {
                return ResourceManager.GetString("NotEnoughSpaceForStringStream", resourceCulture);
            }
        }



        /// <summary>
        /// Not enough space for Blob stream.
        /// </summary>
        internal static string NotEnoughSpaceForBlobStream
        {
            get
            {
                return ResourceManager.GetString("NotEnoughSpaceForBlobStream", resourceCulture);
            }
        }



        /// <summary>
        /// Not enough space for GUID stream.
        /// </summary>
        internal static string NotEnoughSpaceForGUIDStream
        {
            get
            {
                return ResourceManager.GetString("NotEnoughSpaceForGUIDStream", resourceCulture);
            }
        }



        /// <summary>
        /// Not enough space for Metadata stream.
        /// </summary>
        internal static string NotEnoughSpaceForMetadataStream
        {
            get
            {
                return ResourceManager.GetString("NotEnoughSpaceForMetadataStream", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid Metadata stream format.
        /// </summary>
        internal static string InvalidMetadataStreamFormat
        {
            get
            {
                return ResourceManager.GetString("InvalidMetadataStreamFormat", resourceCulture);
            }
        }



        /// <summary>
        /// Metadata tables too small.
        /// </summary>
        internal static string MetadataTablesTooSmall
        {
            get
            {
                return ResourceManager.GetString("MetadataTablesTooSmall", resourceCulture);
            }
        }



        /// <summary>
        /// Metadata table header too small.
        /// </summary>
        internal static string MetadataTableHeaderTooSmall
        {
            get
            {
                return ResourceManager.GetString("MetadataTableHeaderTooSmall", resourceCulture);
            }
        }



        /// <summary>
        /// Missing mscorlib reference in AssemblyRef table.
        /// </summary>
        internal static string WinMDMissingMscorlibRef
        {
            get
            {
                return ResourceManager.GetString("WinMDMissingMscorlibRef", resourceCulture);
            }
        }



        /// <summary>
        /// Unexpected stream end.
        /// </summary>
        internal static string UnexpectedStreamEnd
        {
            get
            {
                return ResourceManager.GetString("UnexpectedStreamEnd", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid relative virtual address (RVA): 0x{0:X8}
        /// </summary>
        internal static string InvalidMethodRva
        {
            get
            {
                return ResourceManager.GetString("InvalidMethodRva", resourceCulture);
            }
        }


        internal static string FormatInvalidMethodRva(object arg1)
        {
            return string.Format(InvalidMethodRva, arg1);
        }


        /// <summary>
        /// Can't get a heap offset for a virtual heap handle
        /// </summary>
        internal static string CantGetOffsetForVirtualHeapHandle
        {
            get
            {
                return ResourceManager.GetString("CantGetOffsetForVirtualHeapHandle", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid number of sections declared in PE header.
        /// </summary>
        internal static string InvalidNumberOfSections
        {
            get
            {
                return ResourceManager.GetString("InvalidNumberOfSections", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid signature.
        /// </summary>
        internal static string InvalidSignature
        {
            get
            {
                return ResourceManager.GetString("InvalidSignature", resourceCulture);
            }
        }



        /// <summary>
        /// PE image does not have metadata.
        /// </summary>
        internal static string PEImageDoesNotHaveMetadata
        {
            get
            {
                return ResourceManager.GetString("PEImageDoesNotHaveMetadata", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid coded index.
        /// </summary>
        internal static string InvalidCodedIndex
        {
            get
            {
                return ResourceManager.GetString("InvalidCodedIndex", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid compressed integer.
        /// </summary>
        internal static string InvalidCompressedInteger
        {
            get
            {
                return ResourceManager.GetString("InvalidCompressedInteger", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid document name.
        /// </summary>
        internal static string InvalidDocumentName
        {
            get
            {
                return ResourceManager.GetString("InvalidDocumentName", resourceCulture);
            }
        }



        /// <summary>
        /// Row ID or heap offset is too large.
        /// </summary>
        internal static string RowIdOrHeapOffsetTooLarge
        {
            get
            {
                return ResourceManager.GetString("RowIdOrHeapOffsetTooLarge", resourceCulture);
            }
        }



        /// <summary>
        /// EnCMap table not sorted or has missing records.
        /// </summary>
        internal static string EnCMapNotSorted
        {
            get
            {
                return ResourceManager.GetString("EnCMapNotSorted", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid serialized string.
        /// </summary>
        internal static string InvalidSerializedString
        {
            get
            {
                return ResourceManager.GetString("InvalidSerializedString", resourceCulture);
            }
        }



        /// <summary>
        /// Stream length minus starting position is too large to hold a PEImage.
        /// </summary>
        internal static string StreamTooLarge
        {
            get
            {
                return ResourceManager.GetString("StreamTooLarge", resourceCulture);
            }
        }



        /// <summary>
        /// Image is either too small or contains an invalid byte offset or count.
        /// </summary>
        internal static string ImageTooSmallOrContainsInvalidOffsetOrCount
        {
            get
            {
                return ResourceManager.GetString("ImageTooSmallOrContainsInvalidOffsetOrCount", resourceCulture);
            }
        }



        /// <summary>
        /// The MetadataStringDecoder instance used to instantiate the Metadata reader must have a UTF-8 encoding.
        /// </summary>
        internal static string MetadataStringDecoderEncodingMustBeUtf8
        {
            get
            {
                return ResourceManager.GetString("MetadataStringDecoderEncodingMustBeUtf8", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid constant value.
        /// </summary>
        internal static string InvalidConstantValue
        {
            get
            {
                return ResourceManager.GetString("InvalidConstantValue", resourceCulture);
            }
        }



        /// <summary>
        /// Value of type '{0}' is not a constant.
        /// </summary>
        internal static string InvalidConstantValueOfType
        {
            get
            {
                return ResourceManager.GetString("InvalidConstantValueOfType", resourceCulture);
            }
        }


        internal static string FormatInvalidConstantValueOfType(object arg1)
        {
            return string.Format(InvalidConstantValueOfType, arg1);
        }


        /// <summary>
        /// Invalid import definition kind: {0}.
        /// </summary>
        internal static string InvalidImportDefinitionKind
        {
            get
            {
                return ResourceManager.GetString("InvalidImportDefinitionKind", resourceCulture);
            }
        }


        internal static string FormatInvalidImportDefinitionKind(object arg1)
        {
            return string.Format(InvalidImportDefinitionKind, arg1);
        }


        /// <summary>
        /// Value is too large.
        /// </summary>
        internal static string ValueTooLarge
        {
            get
            {
                return ResourceManager.GetString("ValueTooLarge", resourceCulture);
            }
        }



        /// <summary>
        /// Blob is to large.
        /// </summary>
        internal static string BlobTooLarge
        {
            get
            {
                return ResourceManager.GetString("BlobTooLarge", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid type size.
        /// </summary>
        internal static string InvalidTypeSize
        {
            get
            {
                return ResourceManager.GetString("InvalidTypeSize", resourceCulture);
            }
        }



        /// <summary>
        /// Handle belongs to a future generation
        /// </summary>
        internal static string HandleBelongsToFutureGeneration
        {
            get
            {
                return ResourceManager.GetString("HandleBelongsToFutureGeneration", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid row count: {0}
        /// </summary>
        internal static string InvalidRowCount
        {
            get
            {
                return ResourceManager.GetString("InvalidRowCount", resourceCulture);
            }
        }


        internal static string FormatInvalidRowCount(object arg1)
        {
            return string.Format(InvalidRowCount, arg1);
        }


        /// <summary>
        /// Invalid entry point token: 0x{0:8X}
        /// </summary>
        internal static string InvalidEntryPointToken
        {
            get
            {
                return ResourceManager.GetString("InvalidEntryPointToken", resourceCulture);
            }
        }


        internal static string FormatInvalidEntryPointToken(object arg1)
        {
            return string.Format(InvalidEntryPointToken, arg1);
        }


        /// <summary>
        /// There are too many subnamespaces.
        /// </summary>
        internal static string TooManySubnamespaces
        {
            get
            {
                return ResourceManager.GetString("TooManySubnamespaces", resourceCulture);
            }
        }



        /// <summary>
        /// There are too many exception regions.
        /// </summary>
        internal static string TooManyExceptionRegions
        {
            get
            {
                return ResourceManager.GetString("TooManyExceptionRegions", resourceCulture);
            }
        }



        /// <summary>
        /// Sequence point value is out of range.
        /// </summary>
        internal static string SequencePointValueOutOfRange
        {
            get
            {
                return ResourceManager.GetString("SequencePointValueOutOfRange", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid directory relative virtual address.
        /// </summary>
        internal static string InvalidDirectoryRVA
        {
            get
            {
                return ResourceManager.GetString("InvalidDirectoryRVA", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid directory size.
        /// </summary>
        internal static string InvalidDirectorySize
        {
            get
            {
                return ResourceManager.GetString("InvalidDirectorySize", resourceCulture);
            }
        }



        /// <summary>
        /// The value of field Characteristics in debug directory entry must be zero.
        /// </summary>
        internal static string InvalidDebugDirectoryEntryCharacteristics
        {
            get
            {
                return ResourceManager.GetString("InvalidDebugDirectoryEntryCharacteristics", resourceCulture);
            }
        }



        /// <summary>
        /// Unexpected CodeView data signature value.
        /// </summary>
        internal static string UnexpectedCodeViewDataSignature
        {
            get
            {
                return ResourceManager.GetString("UnexpectedCodeViewDataSignature", resourceCulture);
            }
        }



        /// <summary>
        /// Unexpected Embedded Portable PDB data signature value.
        /// </summary>
        internal static string UnexpectedEmbeddedPortablePdbDataSignature
        {
            get
            {
                return ResourceManager.GetString("UnexpectedEmbeddedPortablePdbDataSignature", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid PDB Checksum data format.
        /// </summary>
        internal static string InvalidPdbChecksumDataFormat
        {
            get
            {
                return ResourceManager.GetString("InvalidPdbChecksumDataFormat", resourceCulture);
            }
        }



        /// <summary>
        /// Expected signature header for '{0}', but found '{1}' (0x{2:x2}).
        /// </summary>
        internal static string UnexpectedSignatureHeader
        {
            get
            {
                return ResourceManager.GetString("UnexpectedSignatureHeader", resourceCulture);
            }
        }


        internal static string FormatUnexpectedSignatureHeader(object arg1, object arg2, object arg3)
        {
            return string.Format(UnexpectedSignatureHeader, arg1, arg2, arg3);
        }


        /// <summary>
        /// Expected signature header for '{0}' or '{1}', but found '{2}' (0x{3:x2}).
        /// </summary>
        internal static string UnexpectedSignatureHeader2
        {
            get
            {
                return ResourceManager.GetString("UnexpectedSignatureHeader2", resourceCulture);
            }
        }


        internal static string FormatUnexpectedSignatureHeader2(object arg1, object arg2, object arg3, object arg4)
        {
            return string.Format(UnexpectedSignatureHeader2, arg1, arg2, arg3, arg4);
        }


        /// <summary>
        /// Specified handle is not a TypeDefinitionHandle or TypeReferenceHandle.
        /// </summary>
        internal static string NotTypeDefOrRefHandle
        {
            get
            {
                return ResourceManager.GetString("NotTypeDefOrRefHandle", resourceCulture);
            }
        }



        /// <summary>
        /// Unexpected SignatureTypeCode: (0x{0:x}).
        /// </summary>
        internal static string UnexpectedSignatureTypeCode
        {
            get
            {
                return ResourceManager.GetString("UnexpectedSignatureTypeCode", resourceCulture);
            }
        }


        internal static string FormatUnexpectedSignatureTypeCode(object arg1)
        {
            return string.Format(UnexpectedSignatureTypeCode, arg1);
        }


        /// <summary>
        /// Signature type sequence must have at least one element.
        /// </summary>
        internal static string SignatureTypeSequenceMustHaveAtLeastOneElement
        {
            get
            {
                return ResourceManager.GetString("SignatureTypeSequenceMustHaveAtLeastOneElement", resourceCulture);
            }
        }



        /// <summary>
        /// Specified handle is not a TypeDefinitionHandle, TypeReferenceHandle, or TypeSpecificationHandle.
        /// </summary>
        internal static string NotTypeDefOrRefOrSpecHandle
        {
            get
            {
                return ResourceManager.GetString("NotTypeDefOrRefOrSpecHandle", resourceCulture);
            }
        }



        /// <summary>
        /// The Debug directory was not of type {0}.
        /// </summary>
        internal static string UnexpectedDebugDirectoryType
        {
            get
            {
                return ResourceManager.GetString("UnexpectedDebugDirectoryType", resourceCulture);
            }
        }


        internal static string FormatUnexpectedDebugDirectoryType(object arg1)
        {
            return string.Format(UnexpectedDebugDirectoryType, arg1);
        }


        /// <summary>
        /// The limit on the size of {0} heap has been exceeded.
        /// </summary>
        internal static string HeapSizeLimitExceeded
        {
            get
            {
                return ResourceManager.GetString("HeapSizeLimitExceeded", resourceCulture);
            }
        }


        internal static string FormatHeapSizeLimitExceeded(object arg1)
        {
            return string.Format(HeapSizeLimitExceeded, arg1);
        }


        /// <summary>
        /// Builder must be aligned to 4 byte boundary.
        /// </summary>
        internal static string BuilderMustAligned
        {
            get
            {
                return ResourceManager.GetString("BuilderMustAligned", resourceCulture);
            }
        }



        /// <summary>
        /// The operation is not valid on this builder as it has been linked with another one.
        /// </summary>
        internal static string BuilderAlreadyLinked
        {
            get
            {
                return ResourceManager.GetString("BuilderAlreadyLinked", resourceCulture);
            }
        }



        /// <summary>
        /// The size of the builder returned by {0}.{1} is smaller than requested.
        /// </summary>
        internal static string ReturnedBuilderSizeTooSmall
        {
            get
            {
                return ResourceManager.GetString("ReturnedBuilderSizeTooSmall", resourceCulture);
            }
        }


        internal static string FormatReturnedBuilderSizeTooSmall(object arg1, object arg2)
        {
            return string.Format(ReturnedBuilderSizeTooSmall, arg1, arg2);
        }


        /// <summary>
        /// Can't add vararg parameters to non-vararg signature.
        /// </summary>
        internal static string SignatureNotVarArg
        {
            get
            {
                return ResourceManager.GetString("SignatureNotVarArg", resourceCulture);
            }
        }



        /// <summary>
        /// Specified label doesn't belong to the current builder.
        /// </summary>
        internal static string LabelDoesntBelongToBuilder
        {
            get
            {
                return ResourceManager.GetString("LabelDoesntBelongToBuilder", resourceCulture);
            }
        }



        /// <summary>
        /// Can't emit a branch or exception region, the current encoder not created with a control flow builder.
        /// </summary>
        internal static string ControlFlowBuilderNotAvailable
        {
            get
            {
                return ResourceManager.GetString("ControlFlowBuilderNotAvailable", resourceCulture);
            }
        }



        /// <summary>
        /// Base reader must be a full metadata reader.
        /// </summary>
        internal static string BaseReaderMustBeFullMetadataReader
        {
            get
            {
                return ResourceManager.GetString("BaseReaderMustBeFullMetadataReader", resourceCulture);
            }
        }



        /// <summary>
        /// Module already added.
        /// </summary>
        internal static string ModuleAlreadyAdded
        {
            get
            {
                return ResourceManager.GetString("ModuleAlreadyAdded", resourceCulture);
            }
        }



        /// <summary>
        /// Assembly already added.
        /// </summary>
        internal static string AssemblyAlreadyAdded
        {
            get
            {
                return ResourceManager.GetString("AssemblyAlreadyAdded", resourceCulture);
            }
        }



        /// <summary>
        /// Expected list of size {0}.
        /// </summary>
        internal static string ExpectedListOfSize
        {
            get
            {
                return ResourceManager.GetString("ExpectedListOfSize", resourceCulture);
            }
        }


        internal static string FormatExpectedListOfSize(object arg1)
        {
            return string.Format(ExpectedListOfSize, arg1);
        }


        /// <summary>
        /// Expected array of size {0}.
        /// </summary>
        internal static string ExpectedArrayOfSize
        {
            get
            {
                return ResourceManager.GetString("ExpectedArrayOfSize", resourceCulture);
            }
        }


        internal static string FormatExpectedArrayOfSize(object arg1)
        {
            return string.Format(ExpectedArrayOfSize, arg1);
        }


        /// <summary>
        /// Expected non-empty list.
        /// </summary>
        internal static string ExpectedNonEmptyList
        {
            get
            {
                return ResourceManager.GetString("ExpectedNonEmptyList", resourceCulture);
            }
        }



        /// <summary>
        /// Expected non-empty array.
        /// </summary>
        internal static string ExpectedNonEmptyArray
        {
            get
            {
                return ResourceManager.GetString("ExpectedNonEmptyArray", resourceCulture);
            }
        }



        /// <summary>
        /// Expected non-empty string.
        /// </summary>
        internal static string ExpectedNonEmptyString
        {
            get
            {
                return ResourceManager.GetString("ExpectedNonEmptyString", resourceCulture);
            }
        }



        /// <summary>
        /// Specified readers must be minimal delta metadata readers.
        /// </summary>
        internal static string ReadersMustBeDeltaReaders
        {
            get
            {
                return ResourceManager.GetString("ReadersMustBeDeltaReaders", resourceCulture);
            }
        }



        /// <summary>
        /// Signature provider returned invalid signature.
        /// </summary>
        internal static string SignatureProviderReturnedInvalidSignature
        {
            get
            {
                return ResourceManager.GetString("SignatureProviderReturnedInvalidSignature", resourceCulture);
            }
        }



        /// <summary>
        /// Unknown section name: '{0}'.
        /// </summary>
        internal static string UnknownSectionName
        {
            get
            {
                return ResourceManager.GetString("UnknownSectionName", resourceCulture);
            }
        }


        internal static string FormatUnknownSectionName(object arg1)
        {
            return string.Format(UnknownSectionName, arg1);
        }


        /// <summary>
        /// Hash must be at least {0}B long.
        /// </summary>
        internal static string HashTooShort
        {
            get
            {
                return ResourceManager.GetString("HashTooShort", resourceCulture);
            }
        }


        internal static string FormatHashTooShort(object arg1)
        {
            return string.Format(HashTooShort, arg1);
        }


        /// <summary>
        /// Expected array of length {0}.
        /// </summary>
        internal static string UnexpectedArrayLength
        {
            get
            {
                return ResourceManager.GetString("UnexpectedArrayLength", resourceCulture);
            }
        }


        internal static string FormatUnexpectedArrayLength(object arg1)
        {
            return string.Format(UnexpectedArrayLength, arg1);
        }


        /// <summary>
        /// Value must be multiple of {0}.
        /// </summary>
        internal static string ValueMustBeMultiple
        {
            get
            {
                return ResourceManager.GetString("ValueMustBeMultiple", resourceCulture);
            }
        }


        internal static string FormatValueMustBeMultiple(object arg1)
        {
            return string.Format(ValueMustBeMultiple, arg1);
        }


        /// <summary>
        /// {0} must not return null.
        /// </summary>
        internal static string MustNotReturnNull
        {
            get
            {
                return ResourceManager.GetString("MustNotReturnNull", resourceCulture);
            }
        }


        internal static string FormatMustNotReturnNull(object arg1)
        {
            return string.Format(MustNotReturnNull, arg1);
        }


        /// <summary>
        /// Metadata version too long.
        /// </summary>
        internal static string MetadataVersionTooLong
        {
            get
            {
                return ResourceManager.GetString("MetadataVersionTooLong", resourceCulture);
            }
        }



        /// <summary>
        /// Row count must be zero for table #{0}.
        /// </summary>
        internal static string RowCountMustBeZero
        {
            get
            {
                return ResourceManager.GetString("RowCountMustBeZero", resourceCulture);
            }
        }


        internal static string FormatRowCountMustBeZero(object arg1)
        {
            return string.Format(RowCountMustBeZero, arg1);
        }


        /// <summary>
        /// Row count specified for table index {0} is out of allowed range.
        /// </summary>
        internal static string RowCountOutOfRange
        {
            get
            {
                return ResourceManager.GetString("RowCountOutOfRange", resourceCulture);
            }
        }


        internal static string FormatRowCountOutOfRange(object arg1)
        {
            return string.Format(RowCountOutOfRange, arg1);
        }


        /// <summary>
        /// Declared size doesn't correspond to the actual size.
        /// </summary>
        internal static string SizeMismatch
        {
            get
            {
                return ResourceManager.GetString("SizeMismatch", resourceCulture);
            }
        }



        /// <summary>
        /// Data too big to fit in memory.
        /// </summary>
        internal static string DataTooBig
        {
            get
            {
                return ResourceManager.GetString("DataTooBig", resourceCulture);
            }
        }



        /// <summary>
        /// Unsupported format version: {0}
        /// </summary>
        internal static string UnsupportedFormatVersion
        {
            get
            {
                return ResourceManager.GetString("UnsupportedFormatVersion", resourceCulture);
            }
        }


        internal static string FormatUnsupportedFormatVersion(object arg1)
        {
            return string.Format(UnsupportedFormatVersion, arg1);
        }


        /// <summary>
        /// The distance between the instruction {0} (offset {1}) and the target label doesn't fit the operand size: {2}
        /// </summary>
        internal static string DistanceBetweenInstructionAndLabelTooBig
        {
            get
            {
                return ResourceManager.GetString("DistanceBetweenInstructionAndLabelTooBig", resourceCulture);
            }
        }


        internal static string FormatDistanceBetweenInstructionAndLabelTooBig(object arg1, object arg2, object arg3)
        {
            return string.Format(DistanceBetweenInstructionAndLabelTooBig, arg1, arg2, arg3);
        }


        /// <summary>
        /// Label {0} has not been marked.
        /// </summary>
        internal static string LabelNotMarked
        {
            get
            {
                return ResourceManager.GetString("LabelNotMarked", resourceCulture);
            }
        }


        internal static string FormatLabelNotMarked(object arg1)
        {
            return string.Format(LabelNotMarked, arg1);
        }


        /// <summary>
        /// Method body was created with no exception regions.
        /// </summary>
        internal static string MethodHasNoExceptionRegions
        {
            get
            {
                return ResourceManager.GetString("MethodHasNoExceptionRegions", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid exception region bounds: start offset ({0}) is greater than end offset ({1}).
        /// </summary>
        internal static string InvalidExceptionRegionBounds
        {
            get
            {
                return ResourceManager.GetString("InvalidExceptionRegionBounds", resourceCulture);
            }
        }


        internal static string FormatInvalidExceptionRegionBounds(object arg1, object arg2)
        {
            return string.Format(InvalidExceptionRegionBounds, arg1, arg2);
        }


        /// <summary>
        /// Unexpected value '{0}' of type '{1}'
        /// </summary>
        internal static string UnexpectedValue
        {
            get
            {
                return ResourceManager.GetString("UnexpectedValue", resourceCulture);
            }
        }


        internal static string FormatUnexpectedValue(object arg1, object arg2)
        {
            return string.Format(UnexpectedValue, arg1, arg2);
        }


        /// <summary>
        /// Unexpected value '{0}' of unknown type.
        /// </summary>
        internal static string UnexpectedValueUnknownType
        {
            get
            {
                return ResourceManager.GetString("UnexpectedValueUnknownType", resourceCulture);
            }
        }


        internal static string FormatUnexpectedValueUnknownType(object arg1)
        {
            return string.Format(UnexpectedValueUnknownType, arg1);
        }


        /// <summary>
        /// The SwitchInstructionEncoder.Branch method was invoked too few times.
        /// </summary>
        internal static string SwitchInstructionEncoderTooFewBranches
        {
            get
            {
                return ResourceManager.GetString("SwitchInstructionEncoderTooFewBranches", resourceCulture);
            }
        }



        /// <summary>
        /// The SwitchInstructionEncoder.Branch method was invoked too many times.
        /// </summary>
        internal static string SwitchInstructionEncoderTooManyBranches
        {
            get
            {
                return ResourceManager.GetString("SwitchInstructionEncoderTooManyBranches", resourceCulture);
            }
        }



        /// <summary>
        /// The name of the type is invalid.
        /// </summary>
        internal static string Argument_InvalidTypeName
        {
            get
            {
                return ResourceManager.GetString("Argument_InvalidTypeName", resourceCulture);
            }
        }



        /// <summary>
        /// Maximum node count of {0} exceeded.
        /// </summary>
        internal static string InvalidOperation_MaxNodesExceeded
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_MaxNodesExceeded", resourceCulture);
            }
        }


        internal static string FormatInvalidOperation_MaxNodesExceeded(object arg1)
        {
            return string.Format(InvalidOperation_MaxNodesExceeded, arg1);
        }


        /// <summary>
        /// Must be an array type.
        /// </summary>
        internal static string Argument_HasToBeArrayClass
        {
            get
            {
                return ResourceManager.GetString("Argument_HasToBeArrayClass", resourceCulture);
            }
        }



        /// <summary>
        /// This operation is only valid on generic types.
        /// </summary>
        internal static string InvalidOperation_NotGenericType
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_NotGenericType", resourceCulture);
            }
        }



        /// <summary>
        /// This operation is only valid on nested types.
        /// </summary>
        internal static string InvalidOperation_NotNestedType
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_NotNestedType", resourceCulture);
            }
        }



        /// <summary>
        /// This operation is only valid on arrays, pointers and references.
        /// </summary>
        internal static string InvalidOperation_NoElement
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_NoElement", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot retrieve the namespace of a nested type.
        /// </summary>
        internal static string InvalidOperation_NestedTypeNamespace
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_NestedTypeNamespace", resourceCulture);
            }
        }



        /// <summary>
        /// The given assembly name was invalid.
        /// </summary>
        internal static string InvalidAssemblyName
        {
            get
            {
                return ResourceManager.GetString("InvalidAssemblyName", resourceCulture);
            }
        }



        /// <summary>
        /// '{0}' is not a simple TypeName.
        /// </summary>
        internal static string Arg_NotSimpleTypeName
        {
            get
            {
                return ResourceManager.GetString("Arg_NotSimpleTypeName", resourceCulture);
            }
        }


        internal static string FormatArg_NotSimpleTypeName(object arg1)
        {
            return string.Format(Arg_NotSimpleTypeName, arg1);
        }
    }
}
