
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Net.Primitives", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// This method is not implemented by this class.
        /// </summary>
        internal static string net_MethodNotImplementedException
        {
            get
            {
                return ResourceManager.GetString("net_MethodNotImplementedException", resourceCulture);
            }
        }



        /// <summary>
        /// This property is not implemented by this class.
        /// </summary>
        internal static string net_PropertyNotImplementedException
        {
            get
            {
                return ResourceManager.GetString("net_PropertyNotImplementedException", resourceCulture);
            }
        }



        /// <summary>
        /// The AddressFamily {0} is not valid for the {1} end point.
        /// </summary>
        internal static string net_InvalidAddressFamily
        {
            get
            {
                return ResourceManager.GetString("net_InvalidAddressFamily", resourceCulture);
            }
        }


        internal static string Formatnet_InvalidAddressFamily(object arg1, object arg2)
        {
            return string.Format(net_InvalidAddressFamily, arg1, arg2);
        }


        /// <summary>
        /// The supplied {0} is an invalid size for the {1} end point.
        /// </summary>
        internal static string net_InvalidSocketAddressSize
        {
            get
            {
                return ResourceManager.GetString("net_InvalidSocketAddressSize", resourceCulture);
            }
        }


        internal static string Formatnet_InvalidSocketAddressSize(object arg1, object arg2)
        {
            return string.Format(net_InvalidSocketAddressSize, arg1, arg2);
        }


        /// <summary>
        /// The specified value is not valid.
        /// </summary>
        internal static string net_sockets_invalid_optionValue_all
        {
            get
            {
                return ResourceManager.GetString("net_sockets_invalid_optionValue_all", resourceCulture);
            }
        }



        /// <summary>
        /// The parameter '{0}' cannot be an empty string.
        /// </summary>
        internal static string net_emptystringcall
        {
            get
            {
                return ResourceManager.GetString("net_emptystringcall", resourceCulture);
            }
        }


        internal static string Formatnet_emptystringcall(object arg1)
        {
            return string.Format(net_emptystringcall, arg1);
        }


        /// <summary>
        /// An invalid IP address was specified.
        /// </summary>
        internal static string dns_bad_ip_address
        {
            get
            {
                return ResourceManager.GetString("dns_bad_ip_address", resourceCulture);
            }
        }



        /// <summary>
        /// An invalid IP network was specified.
        /// </summary>
        internal static string net_bad_ip_network
        {
            get
            {
                return ResourceManager.GetString("net_bad_ip_network", resourceCulture);
            }
        }



        /// <summary>
        /// An error occurred when adding a cookie to the container.
        /// </summary>
        internal static string net_container_add_cookie
        {
            get
            {
                return ResourceManager.GetString("net_container_add_cookie", resourceCulture);
            }
        }



        /// <summary>
        /// The value size of the cookie is '{0}'. This exceeds the configured maximum size, which is '{1}'.
        /// </summary>
        internal static string net_cookie_size
        {
            get
            {
                return ResourceManager.GetString("net_cookie_size", resourceCulture);
            }
        }


        internal static string Formatnet_cookie_size(object arg1, object arg2)
        {
            return string.Format(net_cookie_size, arg1, arg2);
        }


        /// <summary>
        /// An error occurred when parsing the Cookie header for Uri '{0}'.
        /// </summary>
        internal static string net_cookie_parse_header
        {
            get
            {
                return ResourceManager.GetString("net_cookie_parse_header", resourceCulture);
            }
        }


        internal static string Formatnet_cookie_parse_header(object arg1)
        {
            return string.Format(net_cookie_parse_header, arg1);
        }


        /// <summary>
        /// The '{0}'='{1}' part of the cookie is invalid.
        /// </summary>
        internal static string net_cookie_attribute
        {
            get
            {
                return ResourceManager.GetString("net_cookie_attribute", resourceCulture);
            }
        }


        internal static string Formatnet_cookie_attribute(object arg1, object arg2)
        {
            return string.Format(net_cookie_attribute, arg1, arg2);
        }


        /// <summary>
        /// Cookie format error.
        /// </summary>
        internal static string net_cookie_format
        {
            get
            {
                return ResourceManager.GetString("net_cookie_format", resourceCulture);
            }
        }



        /// <summary>
        /// '{0}' has to be greater than '{1}' and less than '{2}'.
        /// </summary>
        internal static string net_cookie_capacity_range
        {
            get
            {
                return ResourceManager.GetString("net_cookie_capacity_range", resourceCulture);
            }
        }


        internal static string Formatnet_cookie_capacity_range(object arg1, object arg2, object arg3)
        {
            return string.Format(net_cookie_capacity_range, arg1, arg2, arg3);
        }


        /// <summary>
        /// The collection is read-only.
        /// </summary>
        internal static string net_collection_readonly
        {
            get
            {
                return ResourceManager.GetString("net_collection_readonly", resourceCulture);
            }
        }



        /// <summary>
        /// Default credentials cannot be supplied for the {0} authentication scheme.
        /// </summary>
        internal static string net_nodefaultcreds
        {
            get
            {
                return ResourceManager.GetString("net_nodefaultcreds", resourceCulture);
            }
        }


        internal static string Formatnet_nodefaultcreds(object arg1)
        {
            return string.Format(net_nodefaultcreds, arg1);
        }


        /// <summary>
        /// Collection was modified after the enumerator was instantiated.
        /// </summary>
        internal static string InvalidOperation_EnumFailedVersion
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_EnumFailedVersion", resourceCulture);
            }
        }



        /// <summary>
        /// Enumeration has either not started or has already finished.
        /// </summary>
        internal static string InvalidOperation_EnumOpCantHappen
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_EnumOpCantHappen", resourceCulture);
            }
        }



        /// <summary>
        /// An invalid IPEndPoint was specified.
        /// </summary>
        internal static string bad_endpoint_string
        {
            get
            {
                return ResourceManager.GetString("bad_endpoint_string", resourceCulture);
            }
        }



        /// <summary>
        /// System.Net.Primitives is not supported on this platform.
        /// </summary>
        internal static string PlatformNotSupported_NetPrimitives
        {
            get
            {
                return ResourceManager.GetString("PlatformNotSupported_NetPrimitives", resourceCulture);
            }
        }



        /// <summary>
        /// The requested property is not supported for the '{0}' AddressFamily.
        /// </summary>
        internal static string net_SocketException_OperationNotSupported
        {
            get
            {
                return ResourceManager.GetString("net_SocketException_OperationNotSupported", resourceCulture);
            }
        }


        internal static string Formatnet_SocketException_OperationNotSupported(object arg1)
        {
            return string.Format(net_SocketException_OperationNotSupported, arg1);
        }


        /// <summary>
        /// This operation is not supported on a read-only IPAddress instance.
        /// </summary>
        internal static string net_SocketException_OperationNotSupported_ReadOnlyIPAddress
        {
            get
            {
                return ResourceManager.GetString("net_SocketException_OperationNotSupported_ReadOnlyIPAddress", resourceCulture);
            }
        }

    }
}
