
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Net.Http", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// The requested security protocol is not supported.
        /// </summary>
        internal static string net_securityprotocolnotsupported
        {
            get
            {
                return ResourceManager.GetString("net_securityprotocolnotsupported", resourceCulture);
            }
        }



        /// <summary>
        /// The format of the HTTP method is invalid.
        /// </summary>
        internal static string net_http_httpmethod_format_error
        {
            get
            {
                return ResourceManager.GetString("net_http_httpmethod_format_error", resourceCulture);
            }
        }



        /// <summary>
        /// The reason phrase must not contain new-line or NUL characters.
        /// </summary>
        internal static string net_http_reasonphrase_format_error
        {
            get
            {
                return ResourceManager.GetString("net_http_reasonphrase_format_error", resourceCulture);
            }
        }



        /// <summary>
        /// The number of elements is greater than the available space from arrayIndex to the end of the destination array.
        /// </summary>
        internal static string net_http_copyto_array_too_small
        {
            get
            {
                return ResourceManager.GetString("net_http_copyto_array_too_small", resourceCulture);
            }
        }



        /// <summary>
        /// The given header was not found.
        /// </summary>
        internal static string net_http_headers_not_found
        {
            get
            {
                return ResourceManager.GetString("net_http_headers_not_found", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot add value because header '{0}' does not support multiple values.
        /// </summary>
        internal static string net_http_headers_single_value_header
        {
            get
            {
                return ResourceManager.GetString("net_http_headers_single_value_header", resourceCulture);
            }
        }


        internal static string Formatnet_http_headers_single_value_header(object arg1)
        {
            return string.Format(net_http_headers_single_value_header, arg1);
        }


        /// <summary>
        /// The header name '{0}' has an invalid format.
        /// </summary>
        internal static string net_http_headers_invalid_header_name
        {
            get
            {
                return ResourceManager.GetString("net_http_headers_invalid_header_name", resourceCulture);
            }
        }


        internal static string Formatnet_http_headers_invalid_header_name(object arg1)
        {
            return string.Format(net_http_headers_invalid_header_name, arg1);
        }


        /// <summary>
        /// The format of value '{0}' is invalid.
        /// </summary>
        internal static string net_http_headers_invalid_value
        {
            get
            {
                return ResourceManager.GetString("net_http_headers_invalid_value", resourceCulture);
            }
        }


        internal static string Formatnet_http_headers_invalid_value(object arg1)
        {
            return string.Format(net_http_headers_invalid_value, arg1);
        }


        /// <summary>
        /// Misused header name, '{0}'. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
        /// </summary>
        internal static string net_http_headers_not_allowed_header_name
        {
            get
            {
                return ResourceManager.GetString("net_http_headers_not_allowed_header_name", resourceCulture);
            }
        }


        internal static string Formatnet_http_headers_not_allowed_header_name(object arg1)
        {
            return string.Format(net_http_headers_not_allowed_header_name, arg1);
        }


        /// <summary>
        /// The specified value is not a valid 'Host' header string.
        /// </summary>
        internal static string net_http_headers_invalid_host_header
        {
            get
            {
                return ResourceManager.GetString("net_http_headers_invalid_host_header", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid range. At least one of the two parameters must not be null.
        /// </summary>
        internal static string net_http_headers_invalid_range
        {
            get
            {
                return ResourceManager.GetString("net_http_headers_invalid_range", resourceCulture);
            }
        }



        /// <summary>
        /// New-line or NUL characters are not allowed in header values.
        /// </summary>
        internal static string net_http_headers_no_newlines_no_nul
        {
            get
            {
                return ResourceManager.GetString("net_http_headers_no_newlines_no_nul", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot write more bytes to the buffer than the configured maximum buffer size: {0}.
        /// </summary>
        internal static string net_http_content_buffersize_exceeded
        {
            get
            {
                return ResourceManager.GetString("net_http_content_buffersize_exceeded", resourceCulture);
            }
        }


        internal static string Formatnet_http_content_buffersize_exceeded(object arg1)
        {
            return string.Format(net_http_content_buffersize_exceeded, arg1);
        }


        /// <summary>
        /// The async operation did not return a System.Threading.Tasks.Task object.
        /// </summary>
        internal static string net_http_content_no_task_returned
        {
            get
            {
                return ResourceManager.GetString("net_http_content_no_task_returned", resourceCulture);
            }
        }



        /// <summary>
        /// The stream was already consumed. It cannot be read again.
        /// </summary>
        internal static string net_http_content_stream_already_read
        {
            get
            {
                return ResourceManager.GetString("net_http_content_stream_already_read", resourceCulture);
            }
        }



        /// <summary>
        /// The stream does not support writing.
        /// </summary>
        internal static string net_http_content_readonly_stream
        {
            get
            {
                return ResourceManager.GetString("net_http_content_readonly_stream", resourceCulture);
            }
        }



        /// <summary>
        /// The stream does not support reading.
        /// </summary>
        internal static string net_http_content_writeonly_stream
        {
            get
            {
                return ResourceManager.GetString("net_http_content_writeonly_stream", resourceCulture);
            }
        }



        /// <summary>
        /// The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set.
        /// </summary>
        internal static string net_http_content_invalid_charset
        {
            get
            {
                return ResourceManager.GetString("net_http_content_invalid_charset", resourceCulture);
            }
        }



        /// <summary>
        /// Error while copying content to a stream.
        /// </summary>
        internal static string net_http_content_stream_copy_error
        {
            get
            {
                return ResourceManager.GetString("net_http_content_stream_copy_error", resourceCulture);
            }
        }



        /// <summary>
        /// The content's stream has already been retrieved via async ReadAsStreamAsync and cannot be subsequently accessed synchronously.
        /// </summary>
        internal static string net_http_content_read_as_stream_has_task
        {
            get
            {
                return ResourceManager.GetString("net_http_content_read_as_stream_has_task", resourceCulture);
            }
        }



        /// <summary>
        /// The request message was already sent. Cannot send the same request message multiple times.
        /// </summary>
        internal static string net_http_client_request_already_sent
        {
            get
            {
                return ResourceManager.GetString("net_http_client_request_already_sent", resourceCulture);
            }
        }



        /// <summary>
        /// This instance has already started one or more requests. Properties can only be modified before sending the first request.
        /// </summary>
        internal static string net_http_operation_started
        {
            get
            {
                return ResourceManager.GetString("net_http_operation_started", resourceCulture);
            }
        }



        /// <summary>
        /// An error occurred while sending the request.
        /// </summary>
        internal static string net_http_client_execution_error
        {
            get
            {
                return ResourceManager.GetString("net_http_client_execution_error", resourceCulture);
            }
        }



        /// <summary>
        /// The base address must be an absolute URI.
        /// </summary>
        internal static string net_http_client_absolute_baseaddress_required
        {
            get
            {
                return ResourceManager.GetString("net_http_client_absolute_baseaddress_required", resourceCulture);
            }
        }



        /// <summary>
        /// An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
        /// </summary>
        internal static string net_http_client_invalid_requesturi
        {
            get
            {
                return ResourceManager.GetString("net_http_client_invalid_requesturi", resourceCulture);
            }
        }



        /// <summary>
        /// The '{0}' scheme is not supported.
        /// </summary>
        internal static string net_http_unsupported_requesturi_scheme
        {
            get
            {
                return ResourceManager.GetString("net_http_unsupported_requesturi_scheme", resourceCulture);
            }
        }


        internal static string Formatnet_http_unsupported_requesturi_scheme(object arg1)
        {
            return string.Format(net_http_unsupported_requesturi_scheme, arg1);
        }


        /// <summary>
        /// Value '{0}' is not a valid Base64 string. Error: {1}
        /// </summary>
        internal static string net_http_parser_invalid_base64_string
        {
            get
            {
                return ResourceManager.GetString("net_http_parser_invalid_base64_string", resourceCulture);
            }
        }


        internal static string Formatnet_http_parser_invalid_base64_string(object arg1, object arg2)
        {
            return string.Format(net_http_parser_invalid_base64_string, arg1, arg2);
        }


        /// <summary>
        /// Handler did not return a response message.
        /// </summary>
        internal static string net_http_handler_noresponse
        {
            get
            {
                return ResourceManager.GetString("net_http_handler_noresponse", resourceCulture);
            }
        }



        /// <summary>
        /// A request message must be provided. It cannot be null.
        /// </summary>
        internal static string net_http_handler_norequest
        {
            get
            {
                return ResourceManager.GetString("net_http_handler_norequest", resourceCulture);
            }
        }



        /// <summary>
        /// Response status code does not indicate success: {0}.
        /// </summary>
        internal static string net_http_message_not_success_statuscode
        {
            get
            {
                return ResourceManager.GetString("net_http_message_not_success_statuscode", resourceCulture);
            }
        }


        internal static string Formatnet_http_message_not_success_statuscode(object arg1)
        {
            return string.Format(net_http_message_not_success_statuscode, arg1);
        }


        /// <summary>
        /// Response status code does not indicate success: {0} ({1}).
        /// </summary>
        internal static string net_http_message_not_success_statuscode_reason
        {
            get
            {
                return ResourceManager.GetString("net_http_message_not_success_statuscode_reason", resourceCulture);
            }
        }


        internal static string Formatnet_http_message_not_success_statuscode_reason(object arg1, object arg2)
        {
            return string.Format(net_http_message_not_success_statuscode_reason, arg1, arg2);
        }


        /// <summary>
        /// The field cannot be longer than {0} characters.
        /// </summary>
        internal static string net_http_content_field_too_long
        {
            get
            {
                return ResourceManager.GetString("net_http_content_field_too_long", resourceCulture);
            }
        }


        internal static string Formatnet_http_content_field_too_long(object arg1)
        {
            return string.Format(net_http_content_field_too_long, arg1);
        }


        /// <summary>
        /// Value for header '{0}' contains new-line characters. Value: '{1}'.
        /// </summary>
        internal static string net_http_log_headers_no_newlines
        {
            get
            {
                return ResourceManager.GetString("net_http_log_headers_no_newlines", resourceCulture);
            }
        }


        internal static string Formatnet_http_log_headers_no_newlines(object arg1, object arg2)
        {
            return string.Format(net_http_log_headers_no_newlines, arg1, arg2);
        }


        /// <summary>
        /// The 'q' value is invalid: '{0}'.
        /// </summary>
        internal static string net_http_log_headers_invalid_quality
        {
            get
            {
                return ResourceManager.GetString("net_http_log_headers_invalid_quality", resourceCulture);
            }
        }


        internal static string Formatnet_http_log_headers_invalid_quality(object arg1)
        {
            return string.Format(net_http_log_headers_invalid_quality, arg1);
        }


        /// <summary>
        /// The inner handler has not been assigned.
        /// </summary>
        internal static string net_http_handler_not_assigned
        {
            get
            {
                return ResourceManager.GetString("net_http_handler_not_assigned", resourceCulture);
            }
        }



        /// <summary>
        /// The {0} property must be set to '{1}' to use this property.
        /// </summary>
        internal static string net_http_invalid_enable_first
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_enable_first", resourceCulture);
            }
        }


        internal static string Formatnet_http_invalid_enable_first(object arg1, object arg2)
        {
            return string.Format(net_http_invalid_enable_first, arg1, arg2);
        }


        /// <summary>
        /// Buffering more than {0} bytes is not supported.
        /// </summary>
        internal static string net_http_content_buffersize_limit
        {
            get
            {
                return ResourceManager.GetString("net_http_content_buffersize_limit", resourceCulture);
            }
        }


        internal static string Formatnet_http_content_buffersize_limit(object arg1)
        {
            return string.Format(net_http_content_buffersize_limit, arg1);
        }


        /// <summary>
        /// The read operation failed, see inner exception.
        /// </summary>
        internal static string net_http_io_read
        {
            get
            {
                return ResourceManager.GetString("net_http_io_read", resourceCulture);
            }
        }



        /// <summary>
        /// Unable to read data from the transport connection. The connection was closed before all data could be read. Expected {0} bytes, read {1} bytes.
        /// </summary>
        internal static string net_http_io_read_incomplete
        {
            get
            {
                return ResourceManager.GetString("net_http_io_read_incomplete", resourceCulture);
            }
        }


        internal static string Formatnet_http_io_read_incomplete(object arg1, object arg2)
        {
            return string.Format(net_http_io_read_incomplete, arg1, arg2);
        }


        /// <summary>
        /// The write operation failed, see inner exception.
        /// </summary>
        internal static string net_http_io_write
        {
            get
            {
                return ResourceManager.GetString("net_http_io_write", resourceCulture);
            }
        }



        /// <summary>
        /// 'Transfer-Encoding: chunked' header can not be used when content object is not specified.
        /// </summary>
        internal static string net_http_chunked_not_allowed_with_empty_content
        {
            get
            {
                return ResourceManager.GetString("net_http_chunked_not_allowed_with_empty_content", resourceCulture);
            }
        }



        /// <summary>
        /// When using CookieUsePolicy.UseSpecifiedCookieContainer, the CookieContainer property must not be null.
        /// </summary>
        internal static string net_http_invalid_cookiecontainer
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_cookiecontainer", resourceCulture);
            }
        }



        /// <summary>
        /// When using a non-null Proxy, the WindowsProxyUsePolicy property must be set to WindowsProxyUsePolicy.UseCustomProxy.
        /// </summary>
        internal static string net_http_invalid_proxyusepolicy
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_proxyusepolicy", resourceCulture);
            }
        }



        /// <summary>
        /// When using WindowsProxyUsePolicy.UseCustomProxy, the Proxy property must not be null.
        /// </summary>
        internal static string net_http_invalid_proxy
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_proxy", resourceCulture);
            }
        }



        /// <summary>
        /// The specified value must be greater than {0}.
        /// </summary>
        internal static string net_http_value_must_be_greater_than
        {
            get
            {
                return ResourceManager.GetString("net_http_value_must_be_greater_than", resourceCulture);
            }
        }


        internal static string Formatnet_http_value_must_be_greater_than(object arg1)
        {
            return string.Format(net_http_value_must_be_greater_than, arg1);
        }


        /// <summary>
        /// The specified value '{0}' must be greater than or equal to '{1}'.
        /// </summary>
        internal static string net_http_value_must_be_greater_than_or_equal
        {
            get
            {
                return ResourceManager.GetString("net_http_value_must_be_greater_than_or_equal", resourceCulture);
            }
        }


        internal static string Formatnet_http_value_must_be_greater_than_or_equal(object arg1, object arg2)
        {
            return string.Format(net_http_value_must_be_greater_than_or_equal, arg1, arg2);
        }


        /// <summary>
        /// The '{0}'='{1}' part of the cookie is invalid.
        /// </summary>
        internal static string net_cookie_attribute
        {
            get
            {
                return ResourceManager.GetString("net_cookie_attribute", resourceCulture);
            }
        }


        internal static string Formatnet_cookie_attribute(object arg1, object arg2)
        {
            return string.Format(net_cookie_attribute, arg1, arg2);
        }


        /// <summary>
        /// Specified file length was too large for the file system.
        /// </summary>
        internal static string ArgumentOutOfRange_FileLengthTooBig
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_FileLengthTooBig", resourceCulture);
            }
        }



        /// <summary>
        /// The file '{0}' already exists.
        /// </summary>
        internal static string IO_FileExists_Name
        {
            get
            {
                return ResourceManager.GetString("IO_FileExists_Name", resourceCulture);
            }
        }


        internal static string FormatIO_FileExists_Name(object arg1)
        {
            return string.Format(IO_FileExists_Name, arg1);
        }


        /// <summary>
        /// Unable to find the specified file.
        /// </summary>
        internal static string IO_FileNotFound
        {
            get
            {
                return ResourceManager.GetString("IO_FileNotFound", resourceCulture);
            }
        }



        /// <summary>
        /// Could not find file '{0}'.
        /// </summary>
        internal static string IO_FileNotFound_FileName
        {
            get
            {
                return ResourceManager.GetString("IO_FileNotFound_FileName", resourceCulture);
            }
        }


        internal static string FormatIO_FileNotFound_FileName(object arg1)
        {
            return string.Format(IO_FileNotFound_FileName, arg1);
        }


        /// <summary>
        /// Could not find a part of the path.
        /// </summary>
        internal static string IO_PathNotFound_NoPathName
        {
            get
            {
                return ResourceManager.GetString("IO_PathNotFound_NoPathName", resourceCulture);
            }
        }



        /// <summary>
        /// Could not find a part of the path '{0}'.
        /// </summary>
        internal static string IO_PathNotFound_Path
        {
            get
            {
                return ResourceManager.GetString("IO_PathNotFound_Path", resourceCulture);
            }
        }


        internal static string FormatIO_PathNotFound_Path(object arg1)
        {
            return string.Format(IO_PathNotFound_Path, arg1);
        }


        /// <summary>
        /// The specified file name or path is too long, or a component of the specified path is too long.
        /// </summary>
        internal static string IO_PathTooLong
        {
            get
            {
                return ResourceManager.GetString("IO_PathTooLong", resourceCulture);
            }
        }



        /// <summary>
        /// The process cannot access the file '{0}' because it is being used by another process.
        /// </summary>
        internal static string IO_SharingViolation_File
        {
            get
            {
                return ResourceManager.GetString("IO_SharingViolation_File", resourceCulture);
            }
        }


        internal static string FormatIO_SharingViolation_File(object arg1)
        {
            return string.Format(IO_SharingViolation_File, arg1);
        }


        /// <summary>
        /// The process cannot access the file because it is being used by another process.
        /// </summary>
        internal static string IO_SharingViolation_NoFileName
        {
            get
            {
                return ResourceManager.GetString("IO_SharingViolation_NoFileName", resourceCulture);
            }
        }



        /// <summary>
        /// Access to the path is denied.
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_NoPathName
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_NoPathName", resourceCulture);
            }
        }



        /// <summary>
        /// Access to the path '{0}' is denied.
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_Path
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_Path", resourceCulture);
            }
        }


        internal static string FormatUnauthorizedAccess_IODenied_Path(object arg1)
        {
            return string.Format(UnauthorizedAccess_IODenied_Path, arg1);
        }


        /// <summary>
        /// The username for a credential object cannot be null or empty.
        /// </summary>
        internal static string net_http_username_empty_string
        {
            get
            {
                return ResourceManager.GetString("net_http_username_empty_string", resourceCulture);
            }
        }



        /// <summary>
        /// The stream does not support concurrent I/O read or write operations.
        /// </summary>
        internal static string net_http_no_concurrent_io_allowed
        {
            get
            {
                return ResourceManager.GetString("net_http_no_concurrent_io_allowed", resourceCulture);
            }
        }



        /// <summary>
        /// The server returned an invalid or unrecognized response.
        /// </summary>
        internal static string net_http_invalid_response
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response", resourceCulture);
            }
        }



        /// <summary>
        /// Sent {0} request content bytes, but Content-Length promised {1}.
        /// </summary>
        internal static string net_http_request_content_length_mismatch
        {
            get
            {
                return ResourceManager.GetString("net_http_request_content_length_mismatch", resourceCulture);
            }
        }


        internal static string Formatnet_http_request_content_length_mismatch(object arg1, object arg2)
        {
            return string.Format(net_http_request_content_length_mismatch, arg1, arg2);
        }


        /// <summary>
        /// The response ended prematurely.
        /// </summary>
        internal static string net_http_invalid_response_premature_eof
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_premature_eof", resourceCulture);
            }
        }



        /// <summary>
        /// The response ended prematurely while waiting for the next frame from the server.
        /// </summary>
        internal static string net_http_invalid_response_missing_frame
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_missing_frame", resourceCulture);
            }
        }



        /// <summary>
        /// The response ended prematurely, with at least {0} additional bytes expected.
        /// </summary>
        internal static string net_http_invalid_response_premature_eof_bytecount
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_premature_eof_bytecount", resourceCulture);
            }
        }


        internal static string Formatnet_http_invalid_response_premature_eof_bytecount(object arg1)
        {
            return string.Format(net_http_invalid_response_premature_eof_bytecount, arg1);
        }


        /// <summary>
        /// Received chunk header length could not be parsed: '{0}'.
        /// </summary>
        internal static string net_http_invalid_response_chunk_header_invalid
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_chunk_header_invalid", resourceCulture);
            }
        }


        internal static string Formatnet_http_invalid_response_chunk_header_invalid(object arg1)
        {
            return string.Format(net_http_invalid_response_chunk_header_invalid, arg1);
        }


        /// <summary>
        /// Received an invalid chunk extension: '{0}'.
        /// </summary>
        internal static string net_http_invalid_response_chunk_extension_invalid
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_chunk_extension_invalid", resourceCulture);
            }
        }


        internal static string Formatnet_http_invalid_response_chunk_extension_invalid(object arg1)
        {
            return string.Format(net_http_invalid_response_chunk_extension_invalid, arg1);
        }


        /// <summary>
        /// Received an invalid chunk terminator: '{0}'.
        /// </summary>
        internal static string net_http_invalid_response_chunk_terminator_invalid
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_chunk_terminator_invalid", resourceCulture);
            }
        }


        internal static string Formatnet_http_invalid_response_chunk_terminator_invalid(object arg1)
        {
            return string.Format(net_http_invalid_response_chunk_terminator_invalid, arg1);
        }


        /// <summary>
        /// Received an invalid status line: '{0}'.
        /// </summary>
        internal static string net_http_invalid_response_status_line
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_status_line", resourceCulture);
            }
        }


        internal static string Formatnet_http_invalid_response_status_line(object arg1)
        {
            return string.Format(net_http_invalid_response_status_line, arg1);
        }


        /// <summary>
        /// Received an invalid status code: '{0}'.
        /// </summary>
        internal static string net_http_invalid_response_status_code
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_status_code", resourceCulture);
            }
        }


        internal static string Formatnet_http_invalid_response_status_code(object arg1)
        {
            return string.Format(net_http_invalid_response_status_code, arg1);
        }


        /// <summary>
        /// Received status phrase could not be decoded with iso-8859-1: '{0}'.
        /// </summary>
        internal static string net_http_invalid_response_status_reason
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_status_reason", resourceCulture);
            }
        }


        internal static string Formatnet_http_invalid_response_status_reason(object arg1)
        {
            return string.Format(net_http_invalid_response_status_reason, arg1);
        }


        /// <summary>
        /// The response contained more than one status code.
        /// </summary>
        internal static string net_http_invalid_response_multiple_status_codes
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_multiple_status_codes", resourceCulture);
            }
        }



        /// <summary>
        /// Received an invalid folded header.
        /// </summary>
        internal static string net_http_invalid_response_header_folder
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_header_folder", resourceCulture);
            }
        }



        /// <summary>
        /// Received an invalid header line: '{0}'.
        /// </summary>
        internal static string net_http_invalid_response_header_line
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_header_line", resourceCulture);
            }
        }


        internal static string Formatnet_http_invalid_response_header_line(object arg1)
        {
            return string.Format(net_http_invalid_response_header_line, arg1);
        }


        /// <summary>
        /// Received an invalid header name: '{0}'.
        /// </summary>
        internal static string net_http_invalid_response_header_name
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_header_name", resourceCulture);
            }
        }


        internal static string Formatnet_http_invalid_response_header_name(object arg1)
        {
            return string.Format(net_http_invalid_response_header_name, arg1);
        }


        /// <summary>
        /// The request was aborted.
        /// </summary>
        internal static string net_http_request_aborted
        {
            get
            {
                return ResourceManager.GetString("net_http_request_aborted", resourceCulture);
            }
        }



        /// <summary>
        /// Received an HTTP/2 pseudo-header as a trailing header.
        /// </summary>
        internal static string net_http_invalid_response_pseudo_header_in_trailer
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_response_pseudo_header_in_trailer", resourceCulture);
            }
        }



        /// <summary>
        /// The buffer was not long enough.
        /// </summary>
        internal static string net_http_buffer_insufficient_length
        {
            get
            {
                return ResourceManager.GetString("net_http_buffer_insufficient_length", resourceCulture);
            }
        }



        /// <summary>
        /// The HTTP request headers length exceeded the server limit of {0} bytes.
        /// </summary>
        internal static string net_http_request_headers_exceeded_length
        {
            get
            {
                return ResourceManager.GetString("net_http_request_headers_exceeded_length", resourceCulture);
            }
        }


        internal static string Formatnet_http_request_headers_exceeded_length(object arg1)
        {
            return string.Format(net_http_request_headers_exceeded_length, arg1);
        }


        /// <summary>
        /// The HTTP response headers length exceeded the set limit of {0} bytes.
        /// </summary>
        internal static string net_http_response_headers_exceeded_length
        {
            get
            {
                return ResourceManager.GetString("net_http_response_headers_exceeded_length", resourceCulture);
            }
        }


        internal static string Formatnet_http_response_headers_exceeded_length(object arg1)
        {
            return string.Format(net_http_response_headers_exceeded_length, arg1);
        }


        /// <summary>
        /// Stream does not support reading.
        /// </summary>
        internal static string NotSupported_UnreadableStream
        {
            get
            {
                return ResourceManager.GetString("NotSupported_UnreadableStream", resourceCulture);
            }
        }



        /// <summary>
        /// Stream does not support writing.
        /// </summary>
        internal static string NotSupported_UnwritableStream
        {
            get
            {
                return ResourceManager.GetString("NotSupported_UnwritableStream", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot access a closed stream.
        /// </summary>
        internal static string ObjectDisposed_StreamClosed
        {
            get
            {
                return ResourceManager.GetString("ObjectDisposed_StreamClosed", resourceCulture);
            }
        }



        /// <summary>
        /// Only the 'http', 'https', 'socks4', 'socks4a', 'socks5', and 'socks5h' schemes are allowed for proxies.
        /// </summary>
        internal static string net_http_invalid_proxy_scheme
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_proxy_scheme", resourceCulture);
            }
        }



        /// <summary>
        /// Request headers must contain only ASCII characters.
        /// </summary>
        internal static string net_http_request_invalid_char_encoding
        {
            get
            {
                return ResourceManager.GetString("net_http_request_invalid_char_encoding", resourceCulture);
            }
        }



        /// <summary>
        /// Request Uri's host could not be Punycode encoded.
        /// </summary>
        internal static string net_http_request_invalid_host_punycode
        {
            get
            {
                return ResourceManager.GetString("net_http_request_invalid_host_punycode", resourceCulture);
            }
        }



        /// <summary>
        /// The SSL connection could not be established, see inner exception.
        /// </summary>
        internal static string net_http_ssl_connection_failed
        {
            get
            {
                return ResourceManager.GetString("net_http_ssl_connection_failed", resourceCulture);
            }
        }



        /// <summary>
        /// HTTP 1.0 does not support chunking.
        /// </summary>
        internal static string net_http_unsupported_chunking
        {
            get
            {
                return ResourceManager.GetString("net_http_unsupported_chunking", resourceCulture);
            }
        }



        /// <summary>
        /// Request version value must be one of 1.0, 1.1, 2.0, or 3.0.
        /// </summary>
        internal static string net_http_unsupported_version
        {
            get
            {
                return ResourceManager.GetString("net_http_unsupported_version", resourceCulture);
            }
        }



        /// <summary>
        /// An attempt was made to move the position before the beginning of the stream.
        /// </summary>
        internal static string IO_SeekBeforeBegin
        {
            get
            {
                return ResourceManager.GetString("IO_SeekBeforeBegin", resourceCulture);
            }
        }



        /// <summary>
        /// The application protocol list is invalid.
        /// </summary>
        internal static string net_ssl_app_protocols_invalid
        {
            get
            {
                return ResourceManager.GetString("net_ssl_app_protocols_invalid", resourceCulture);
            }
        }



        /// <summary>
        /// HTTP/2 requires TLS 1.2 or newer, but '{0}' was negotiated.
        /// </summary>
        internal static string net_ssl_http2_requires_tls12
        {
            get
            {
                return ResourceManager.GetString("net_ssl_http2_requires_tls12", resourceCulture);
            }
        }


        internal static string Formatnet_ssl_http2_requires_tls12(object arg1)
        {
            return string.Format(net_ssl_http2_requires_tls12, arg1);
        }


        /// <summary>
        /// The path '{0}' is too long, or a component of the specified path is too long.
        /// </summary>
        internal static string IO_PathTooLong_Path
        {
            get
            {
                return ResourceManager.GetString("IO_PathTooLong_Path", resourceCulture);
            }
        }


        internal static string FormatIO_PathTooLong_Path(object arg1)
        {
            return string.Format(IO_PathTooLong_Path, arg1);
        }


        /// <summary>
        /// CONNECT request must contain Host header.
        /// </summary>
        internal static string net_http_request_no_host
        {
            get
            {
                return ResourceManager.GetString("net_http_request_no_host", resourceCulture);
            }
        }



        /// <summary>
        /// Error {0} calling {1}, '{2}'.
        /// </summary>
        internal static string net_http_winhttp_error
        {
            get
            {
                return ResourceManager.GetString("net_http_winhttp_error", resourceCulture);
            }
        }


        internal static string Formatnet_http_winhttp_error(object arg1, object arg2, object arg3)
        {
            return string.Format(net_http_winhttp_error, arg1, arg2, arg3);
        }


        /// <summary>
        /// The HTTP/2 server sent invalid data on the connection. HTTP/2 error code '{0}' (0x{1}).
        /// </summary>
        internal static string net_http_http2_connection_error
        {
            get
            {
                return ResourceManager.GetString("net_http_http2_connection_error", resourceCulture);
            }
        }


        internal static string Formatnet_http_http2_connection_error(object arg1, object arg2)
        {
            return string.Format(net_http_http2_connection_error, arg1, arg2);
        }


        /// <summary>
        /// The HTTP/2 server closed the connection. HTTP/2 error code '{0}' (0x{1}).
        /// </summary>
        internal static string net_http_http2_connection_close
        {
            get
            {
                return ResourceManager.GetString("net_http_http2_connection_close", resourceCulture);
            }
        }


        internal static string Formatnet_http_http2_connection_close(object arg1, object arg2)
        {
            return string.Format(net_http_http2_connection_close, arg1, arg2);
        }


        /// <summary>
        /// The HTTP/2 server reset the stream. HTTP/2 error code '{0}' (0x{1}).
        /// </summary>
        internal static string net_http_http2_stream_error
        {
            get
            {
                return ResourceManager.GetString("net_http_http2_stream_error", resourceCulture);
            }
        }


        internal static string Formatnet_http_http2_stream_error(object arg1, object arg2)
        {
            return string.Format(net_http_http2_stream_error, arg1, arg2);
        }


        /// <summary>
        /// The HTTP/3 server reset the stream. HTTP/3 error code '{0}' (0x{1}).
        /// </summary>
        internal static string net_http_http3_stream_error
        {
            get
            {
                return ResourceManager.GetString("net_http_http3_stream_error", resourceCulture);
            }
        }


        internal static string Formatnet_http_http3_stream_error(object arg1, object arg2)
        {
            return string.Format(net_http_http3_stream_error, arg1, arg2);
        }


        /// <summary>
        /// An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake.
        /// </summary>
        internal static string net_http_http2_connection_not_established
        {
            get
            {
                return ResourceManager.GetString("net_http_http2_connection_not_established", resourceCulture);
            }
        }



        /// <summary>
        /// The initial HTTP/2 stream window size must be between {0} and {1}.
        /// </summary>
        internal static string net_http_http2_invalidinitialstreamwindowsize
        {
            get
            {
                return ResourceManager.GetString("net_http_http2_invalidinitialstreamwindowsize", resourceCulture);
            }
        }


        internal static string Formatnet_http_http2_invalidinitialstreamwindowsize(object arg1, object arg2)
        {
            return string.Format(net_http_http2_invalidinitialstreamwindowsize, arg1, arg2);
        }


        /// <summary>
        /// This method is not implemented by this class.
        /// </summary>
        internal static string net_MethodNotImplementedException
        {
            get
            {
                return ResourceManager.GetString("net_MethodNotImplementedException", resourceCulture);
            }
        }



        /// <summary>
        /// {0} failed with error {1}.
        /// </summary>
        internal static string net_log_operation_failed_with_error
        {
            get
            {
                return ResourceManager.GetString("net_log_operation_failed_with_error", resourceCulture);
            }
        }


        internal static string Formatnet_log_operation_failed_with_error(object arg1, object arg2)
        {
            return string.Format(net_log_operation_failed_with_error, arg1, arg2);
        }


        /// <summary>
        /// This operation cannot be performed on a completed asynchronous result object.
        /// </summary>
        internal static string net_completed_result
        {
            get
            {
                return ResourceManager.GetString("net_completed_result", resourceCulture);
            }
        }



        /// <summary>
        /// The specified value is not valid in the '{0}' enumeration.
        /// </summary>
        internal static string net_invalid_enum
        {
            get
            {
                return ResourceManager.GetString("net_invalid_enum", resourceCulture);
            }
        }


        internal static string Formatnet_invalid_enum(object arg1)
        {
            return string.Format(net_invalid_enum, arg1);
        }


        /// <summary>
        /// Protocol error: A received message contains a valid signature but it was not encrypted as required by the effective Protection Level.
        /// </summary>
        internal static string net_auth_message_not_encrypted
        {
            get
            {
                return ResourceManager.GetString("net_auth_message_not_encrypted", resourceCulture);
            }
        }



        /// <summary>
        /// Authentication failed because the connection could not be reused.
        /// </summary>
        internal static string net_http_authconnectionfailure
        {
            get
            {
                return ResourceManager.GetString("net_http_authconnectionfailure", resourceCulture);
            }
        }



        /// <summary>
        /// Authentication validation failed with error - {0}.
        /// </summary>
        internal static string net_http_authvalidationfailure
        {
            get
            {
                return ResourceManager.GetString("net_http_authvalidationfailure", resourceCulture);
            }
        }


        internal static string Formatnet_http_authvalidationfailure(object arg1)
        {
            return string.Format(net_http_authvalidationfailure, arg1);
        }


        /// <summary>
        /// Huffman-coded literal string failed to decode.
        /// </summary>
        internal static string net_http_hpack_huffman_decode_failed
        {
            get
            {
                return ResourceManager.GetString("net_http_hpack_huffman_decode_failed", resourceCulture);
            }
        }



        /// <summary>
        /// Incomplete header block received.
        /// </summary>
        internal static string net_http_hpack_incomplete_header_block
        {
            get
            {
                return ResourceManager.GetString("net_http_hpack_incomplete_header_block", resourceCulture);
            }
        }



        /// <summary>
        /// Dynamic table size update received after beginning of header block.
        /// </summary>
        internal static string net_http_hpack_late_dynamic_table_size_update
        {
            get
            {
                return ResourceManager.GetString("net_http_hpack_late_dynamic_table_size_update", resourceCulture);
            }
        }



        /// <summary>
        /// HPACK integer exceeds limits or has an overlong encoding.
        /// </summary>
        internal static string net_http_hpack_bad_integer
        {
            get
            {
                return ResourceManager.GetString("net_http_hpack_bad_integer", resourceCulture);
            }
        }



        /// <summary>
        /// The object was disposed while operations were in progress.
        /// </summary>
        internal static string net_http_disposed_while_in_use
        {
            get
            {
                return ResourceManager.GetString("net_http_disposed_while_in_use", resourceCulture);
            }
        }



        /// <summary>
        /// Dynamic table size update to {0} bytes exceeds limit of {1} bytes.
        /// </summary>
        internal static string net_http_hpack_large_table_size_update
        {
            get
            {
                return ResourceManager.GetString("net_http_hpack_large_table_size_update", resourceCulture);
            }
        }


        internal static string Formatnet_http_hpack_large_table_size_update(object arg1, object arg2)
        {
            return string.Format(net_http_hpack_large_table_size_update, arg1, arg2);
        }


        /// <summary>
        /// The server shut down the connection.
        /// </summary>
        internal static string net_http_server_shutdown
        {
            get
            {
                return ResourceManager.GetString("net_http_server_shutdown", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid header index: {0} is outside of static table and no dynamic table entry found.
        /// </summary>
        internal static string net_http_hpack_invalid_index
        {
            get
            {
                return ResourceManager.GetString("net_http_hpack_invalid_index", resourceCulture);
            }
        }


        internal static string Formatnet_http_hpack_invalid_index(object arg1)
        {
            return string.Format(net_http_hpack_invalid_index, arg1);
        }


        /// <summary>
        /// End of headers reached with incomplete token.
        /// </summary>
        internal static string net_http_hpack_unexpected_end
        {
            get
            {
                return ResourceManager.GetString("net_http_hpack_unexpected_end", resourceCulture);
            }
        }



        /// <summary>
        /// The HTTP headers length exceeded the set limit of {0} bytes.
        /// </summary>
        internal static string net_http_headers_exceeded_length
        {
            get
            {
                return ResourceManager.GetString("net_http_headers_exceeded_length", resourceCulture);
            }
        }


        internal static string Formatnet_http_headers_exceeded_length(object arg1)
        {
            return string.Format(net_http_headers_exceeded_length, arg1);
        }


        /// <summary>
        /// Received an invalid header name: '{0}'.
        /// </summary>
        internal static string net_http_invalid_header_name
        {
            get
            {
                return ResourceManager.GetString("net_http_invalid_header_name", resourceCulture);
            }
        }


        internal static string Formatnet_http_invalid_header_name(object arg1)
        {
            return string.Format(net_http_invalid_header_name, arg1);
        }


        /// <summary>
        /// An HTTP/3 connection could not be established because the server did not complete the HTTP/3 handshake.
        /// </summary>
        internal static string net_http_http3_connection_not_established
        {
            get
            {
                return ResourceManager.GetString("net_http_http3_connection_not_established", resourceCulture);
            }
        }



        /// <summary>
        /// The HTTP/3 server sent invalid data on the connection. HTTP/3 error code '{0}' (0x{1}).
        /// </summary>
        internal static string net_http_http3_connection_error
        {
            get
            {
                return ResourceManager.GetString("net_http_http3_connection_error", resourceCulture);
            }
        }


        internal static string Formatnet_http_http3_connection_error(object arg1, object arg2)
        {
            return string.Format(net_http_http3_connection_error, arg1, arg2);
        }


        /// <summary>
        /// The HTTP/3 server closed the connection. HTTP/3 error code '{0}' (0x{1}).
        /// </summary>
        internal static string net_http_http3_connection_close
        {
            get
            {
                return ResourceManager.GetString("net_http_http3_connection_close", resourceCulture);
            }
        }


        internal static string Formatnet_http_http3_connection_close(object arg1, object arg2)
        {
            return string.Format(net_http_http3_connection_close, arg1, arg2);
        }


        /// <summary>
        /// The QUIC connection with the HTTP/3 server failed on the transport level.
        /// </summary>
        internal static string net_http_http3_connection_quic_error
        {
            get
            {
                return ResourceManager.GetString("net_http_http3_connection_quic_error", resourceCulture);
            }
        }



        /// <summary>
        /// The server is unable to process the request using the current HTTP version and indicates the request should be retried on an older HTTP version.
        /// </summary>
        internal static string net_http_retry_on_older_version
        {
            get
            {
                return ResourceManager.GetString("net_http_retry_on_older_version", resourceCulture);
            }
        }



        /// <summary>
        /// Unable to write content to request stream; content would exceed Content-Length.
        /// </summary>
        internal static string net_http_content_write_larger_than_content_length
        {
            get
            {
                return ResourceManager.GetString("net_http_content_write_larger_than_content_length", resourceCulture);
            }
        }



        /// <summary>
        /// The HTTP/3 server attempted to reference a dynamic table index that does not exist.
        /// </summary>
        internal static string net_http_qpack_no_dynamic_table
        {
            get
            {
                return ResourceManager.GetString("net_http_qpack_no_dynamic_table", resourceCulture);
            }
        }



        /// <summary>
        /// The request was canceled due to the configured HttpClient.Timeout of {0} seconds elapsing.
        /// </summary>
        internal static string net_http_request_timedout
        {
            get
            {
                return ResourceManager.GetString("net_http_request_timedout", resourceCulture);
            }
        }


        internal static string Formatnet_http_request_timedout(object arg1)
        {
            return string.Format(net_http_request_timedout, arg1);
        }


        /// <summary>
        /// A connection could not be established within the configured ConnectTimeout.
        /// </summary>
        internal static string net_http_connect_timedout
        {
            get
            {
                return ResourceManager.GetString("net_http_connect_timedout", resourceCulture);
            }
        }



        /// <summary>
        /// Connection aborted by peer ({0}).
        /// </summary>
        internal static string net_quic_connectionaborted
        {
            get
            {
                return ResourceManager.GetString("net_quic_connectionaborted", resourceCulture);
            }
        }


        internal static string Formatnet_quic_connectionaborted(object arg1)
        {
            return string.Format(net_quic_connectionaborted, arg1);
        }


        /// <summary>
        /// Operation aborted.
        /// </summary>
        internal static string net_quic_operationaborted
        {
            get
            {
                return ResourceManager.GetString("net_quic_operationaborted", resourceCulture);
            }
        }



        /// <summary>
        /// Stream aborted by peer ({0}).
        /// </summary>
        internal static string net_quic_streamaborted
        {
            get
            {
                return ResourceManager.GetString("net_quic_streamaborted", resourceCulture);
            }
        }


        internal static string Formatnet_quic_streamaborted(object arg1)
        {
            return string.Format(net_quic_streamaborted, arg1);
        }


        /// <summary>
        /// The synchronous method is not supported by '{0}'. If you're using a custom '{1}' and wish to use synchronous HTTP methods, you must override its '{2}' virtual method.
        /// </summary>
        internal static string net_http_missing_sync_implementation
        {
            get
            {
                return ResourceManager.GetString("net_http_missing_sync_implementation", resourceCulture);
            }
        }


        internal static string Formatnet_http_missing_sync_implementation(object arg1, object arg2, object arg3)
        {
            return string.Format(net_http_missing_sync_implementation, arg1, arg2, arg3);
        }


        /// <summary>
        /// The synchronous method is not supported by '{0}' for HTTP/2 or higher. Either use an asynchronous method or downgrade the request version to HTTP/1.1 or lower.
        /// </summary>
        internal static string net_http_http2_sync_not_supported
        {
            get
            {
                return ResourceManager.GetString("net_http_http2_sync_not_supported", resourceCulture);
            }
        }


        internal static string Formatnet_http_http2_sync_not_supported(object arg1)
        {
            return string.Format(net_http_http2_sync_not_supported, arg1);
        }


        /// <summary>
        /// HTTP request version upgrade is not enabled for synchronous '{0}'. Do not use '{1}' version policy for synchronous HTTP methods.
        /// </summary>
        internal static string net_http_upgrade_not_enabled_sync
        {
            get
            {
                return ResourceManager.GetString("net_http_upgrade_not_enabled_sync", resourceCulture);
            }
        }


        internal static string Formatnet_http_upgrade_not_enabled_sync(object arg1, object arg2)
        {
            return string.Format(net_http_upgrade_not_enabled_sync, arg1, arg2);
        }


        /// <summary>
        /// Requesting HTTP version {0} with version policy {1} while unable to establish HTTP/{2} connection.
        /// </summary>
        internal static string net_http_requested_version_cannot_establish
        {
            get
            {
                return ResourceManager.GetString("net_http_requested_version_cannot_establish", resourceCulture);
            }
        }


        internal static string Formatnet_http_requested_version_cannot_establish(object arg1, object arg2, object arg3)
        {
            return string.Format(net_http_requested_version_cannot_establish, arg1, arg2, arg3);
        }


        /// <summary>
        /// Requesting HTTP version {0} with version policy {1} while server offers only version fallback.
        /// </summary>
        internal static string net_http_requested_version_server_refused
        {
            get
            {
                return ResourceManager.GetString("net_http_requested_version_server_refused", resourceCulture);
            }
        }


        internal static string Formatnet_http_requested_version_server_refused(object arg1, object arg2)
        {
            return string.Format(net_http_requested_version_server_refused, arg1, arg2);
        }


        /// <summary>
        /// An exception occurred while invoking the PlaintextStreamFilter.
        /// </summary>
        internal static string net_http_exception_during_plaintext_filter
        {
            get
            {
                return ResourceManager.GetString("net_http_exception_during_plaintext_filter", resourceCulture);
            }
        }



        /// <summary>
        /// The user-supplied ConnectCallback returned null.
        /// </summary>
        internal static string net_http_null_from_connect_callback
        {
            get
            {
                return ResourceManager.GetString("net_http_null_from_connect_callback", resourceCulture);
            }
        }



        /// <summary>
        /// The user-supplied PlaintextStreamFilter returned null.
        /// </summary>
        internal static string net_http_null_from_plaintext_filter
        {
            get
            {
                return ResourceManager.GetString("net_http_null_from_plaintext_filter", resourceCulture);
            }
        }



        /// <summary>
        /// Internal error marshalling the response Promise from `fetch`.
        /// </summary>
        internal static string net_http_marshalling_response_promise_from_fetch
        {
            get
            {
                return ResourceManager.GetString("net_http_marshalling_response_promise_from_fetch", resourceCulture);
            }
        }



        /// <summary>
        /// Synchronous reads are not supported, use ReadAsync instead.
        /// </summary>
        internal static string net_http_synchronous_reads_not_supported
        {
            get
            {
                return ResourceManager.GetString("net_http_synchronous_reads_not_supported", resourceCulture);
            }
        }



        /// <summary>
        /// Synchronous writes are not supported, use WriteAsync instead.
        /// </summary>
        internal static string net_http_synchronous_writes_not_supported
        {
            get
            {
                return ResourceManager.GetString("net_http_synchronous_writes_not_supported", resourceCulture);
            }
        }



        /// <summary>
        /// Failed to authenticate with the SOCKS server.
        /// </summary>
        internal static string net_socks_auth_failed
        {
            get
            {
                return ResourceManager.GetString("net_socks_auth_failed", resourceCulture);
            }
        }



        /// <summary>
        /// SOCKS server returned an unknown address type.
        /// </summary>
        internal static string net_socks_bad_address_type
        {
            get
            {
                return ResourceManager.GetString("net_socks_bad_address_type", resourceCulture);
            }
        }



        /// <summary>
        /// SOCKS server failed to connect to the destination. Received error code 0x{0}.
        /// </summary>
        internal static string net_socks_connection_failed
        {
            get
            {
                return ResourceManager.GetString("net_socks_connection_failed", resourceCulture);
            }
        }


        internal static string Formatnet_socks_connection_failed(object arg1)
        {
            return string.Format(net_socks_connection_failed, arg1);
        }


        /// <summary>
        /// SOCKS4 does not support IPv6 addresses.
        /// </summary>
        internal static string net_socks_ipv6_notsupported
        {
            get
            {
                return ResourceManager.GetString("net_socks_ipv6_notsupported", resourceCulture);
            }
        }



        /// <summary>
        /// SOCKS server did not return a suitable authentication method.
        /// </summary>
        internal static string net_socks_no_auth_method
        {
            get
            {
                return ResourceManager.GetString("net_socks_no_auth_method", resourceCulture);
            }
        }



        /// <summary>
        /// Failed to resolve the destination host to an IPv4 address.
        /// </summary>
        internal static string net_socks_no_ipv4_address
        {
            get
            {
                return ResourceManager.GetString("net_socks_no_ipv4_address", resourceCulture);
            }
        }



        /// <summary>
        /// Unexpected SOCKS protocol version. Required {0}, got {1}.
        /// </summary>
        internal static string net_socks_unexpected_version
        {
            get
            {
                return ResourceManager.GetString("net_socks_unexpected_version", resourceCulture);
            }
        }


        internal static string Formatnet_socks_unexpected_version(object arg1, object arg2)
        {
            return string.Format(net_socks_unexpected_version, arg1, arg2);
        }


        /// <summary>
        /// Encoding the {0} took more than the maximum of 255 bytes.
        /// </summary>
        internal static string net_socks_string_too_long
        {
            get
            {
                return ResourceManager.GetString("net_socks_string_too_long", resourceCulture);
            }
        }


        internal static string Formatnet_socks_string_too_long(object arg1)
        {
            return string.Format(net_socks_string_too_long, arg1);
        }


        /// <summary>
        /// SOCKS server requested username & password authentication.
        /// </summary>
        internal static string net_socks_auth_required
        {
            get
            {
                return ResourceManager.GetString("net_socks_auth_required", resourceCulture);
            }
        }



        /// <summary>
        /// The proxy tunnel request to proxy '{0}' failed with status code '{1}'."
        /// </summary>
        internal static string net_http_proxy_tunnel_returned_failure_status_code
        {
            get
            {
                return ResourceManager.GetString("net_http_proxy_tunnel_returned_failure_status_code", resourceCulture);
            }
        }


        internal static string Formatnet_http_proxy_tunnel_returned_failure_status_code(object arg1, object arg2)
        {
            return string.Format(net_http_proxy_tunnel_returned_failure_status_code, arg1, arg2);
        }


        /// <summary>
        /// An error occurred while establishing a connection to the proxy tunnel.
        /// </summary>
        internal static string net_http_proxy_tunnel_error
        {
            get
            {
                return ResourceManager.GetString("net_http_proxy_tunnel_error", resourceCulture);
            }
        }



        /// <summary>
        /// System.Net.Http is not supported on this platform.
        /// </summary>
        internal static string PlatformNotSupported_NetHttp
        {
            get
            {
                return ResourceManager.GetString("PlatformNotSupported_NetHttp", resourceCulture);
            }
        }



        /// <summary>
        /// The HTTP/1.1 response chunk was too large.
        /// </summary>
        internal static string net_http_chunk_too_large
        {
            get
            {
                return ResourceManager.GetString("net_http_chunk_too_large", resourceCulture);
            }
        }



        /// <summary>
        /// Failed to establish web socket connection over HTTP/2 because extended CONNECT is not supported. Try to downgrade the request version to HTTP/1.1.
        /// </summary>
        internal static string net_unsupported_extended_connect
        {
            get
            {
                return ResourceManager.GetString("net_unsupported_extended_connect", resourceCulture);
            }
        }



        /// <summary>
        /// The HTTP/2 server didn't respond to a ping request within the configured KeepAlivePingDelay.
        /// </summary>
        internal static string net_ping_request_timed_out
        {
            get
            {
                return ResourceManager.GetString("net_ping_request_timed_out", resourceCulture);
            }
        }



        /// <summary>
        /// Failed to HPACK encode the headers.
        /// </summary>
        internal static string net_http_hpack_encode_failure
        {
            get
            {
                return ResourceManager.GetString("net_http_hpack_encode_failure", resourceCulture);
            }
        }

    }
}
