
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Formats.Asn1", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Destination is too short.
        /// </summary>
        internal static string Argument_DestinationTooShort
        {
            get
            {
                return ResourceManager.GetString("Argument_DestinationTooShort", resourceCulture);
            }
        }



        /// <summary>
        /// ASN.1 Enumerated values only apply to enum types without the [Flags] attribute.
        /// </summary>
        internal static string Argument_EnumeratedValueRequiresNonFlagsEnum
        {
            get
            {
                return ResourceManager.GetString("Argument_EnumeratedValueRequiresNonFlagsEnum", resourceCulture);
            }
        }



        /// <summary>
        /// Enumerations with a backing type of '{0}' are not supported for ReadEnumeratedValue.
        /// </summary>
        internal static string Argument_EnumeratedValueBackingTypeNotSupported
        {
            get
            {
                return ResourceManager.GetString("Argument_EnumeratedValueBackingTypeNotSupported", resourceCulture);
            }
        }


        internal static string FormatArgument_EnumeratedValueBackingTypeNotSupported(object arg1)
        {
            return string.Format(Argument_EnumeratedValueBackingTypeNotSupported, arg1);
        }


        /// <summary>
        /// The OID value is invalid.
        /// </summary>
        internal static string Argument_InvalidOidValue
        {
            get
            {
                return ResourceManager.GetString("Argument_InvalidOidValue", resourceCulture);
            }
        }



        /// <summary>
        /// Named bit list operations require an enum with the [Flags] attribute.
        /// </summary>
        internal static string Argument_NamedBitListRequiresFlagsEnum
        {
            get
            {
                return ResourceManager.GetString("Argument_NamedBitListRequiresFlagsEnum", resourceCulture);
            }
        }



        /// <summary>
        /// The destination buffer overlaps the source buffer.
        /// </summary>
        internal static string Argument_SourceOverlapsDestination
        {
            get
            {
                return ResourceManager.GetString("Argument_SourceOverlapsDestination", resourceCulture);
            }
        }



        /// <summary>
        /// The specified tag has the Universal TagClass, but the TagValue does not correspond with a known character string type.
        /// </summary>
        internal static string Argument_Tag_NotCharacterString
        {
            get
            {
                return ResourceManager.GetString("Argument_Tag_NotCharacterString", resourceCulture);
            }
        }



        /// <summary>
        /// An integer value cannot be empty.
        /// </summary>
        internal static string Argument_IntegerCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("Argument_IntegerCannotBeEmpty", resourceCulture);
            }
        }



        /// <summary>
        /// The first 9 bits of the integer value all have the same value. Ensure the input is in big-endian byte order and that all redundant leading bytes have been removed.
        /// </summary>
        internal static string Argument_IntegerRedundantByte
        {
            get
            {
                return ResourceManager.GetString("Argument_IntegerRedundantByte", resourceCulture);
            }
        }



        /// <summary>
        /// Tags with TagClass Universal must have the appropriate TagValue value for the data type being read or written.
        /// </summary>
        internal static string Argument_UniversalValueIsFixed
        {
            get
            {
                return ResourceManager.GetString("Argument_UniversalValueIsFixed", resourceCulture);
            }
        }



        /// <summary>
        /// Unused bit count must be 0 when the bit string is empty.
        /// </summary>
        internal static string Argument_UnusedBitCountMustBeZero
        {
            get
            {
                return ResourceManager.GetString("Argument_UnusedBitCountMustBeZero", resourceCulture);
            }
        }



        /// <summary>
        /// Unused bit count must be between 0 and 7, inclusive.
        /// </summary>
        internal static string Argument_UnusedBitCountRange
        {
            get
            {
                return ResourceManager.GetString("Argument_UnusedBitCountRange", resourceCulture);
            }
        }



        /// <summary>
        /// One or more of the bits covered by the provided unusedBitCount value is set. All unused bits must be cleared.
        /// </summary>
        internal static string Argument_UnusedBitWasSet
        {
            get
            {
                return ResourceManager.GetString("Argument_UnusedBitWasSet", resourceCulture);
            }
        }



        /// <summary>
        /// The input to WriteEncodedValue must represent a single encoded value with no trailing data.
        /// </summary>
        internal static string Argument_WriteEncodedValue_OneValueAtATime
        {
            get
            {
                return ResourceManager.GetString("Argument_WriteEncodedValue_OneValueAtATime", resourceCulture);
            }
        }



        /// <summary>
        /// Non-negative number required.
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }



        /// <summary>
        /// Encode cannot be called while a Sequence, Set-Of, or Octet String is still open.
        /// </summary>
        internal static string AsnWriter_EncodeUnbalancedStack
        {
            get
            {
                return ResourceManager.GetString("AsnWriter_EncodeUnbalancedStack", resourceCulture);
            }
        }



        /// <summary>
        /// The AsnWriter cannot be written to while performing the Encode callback.
        /// </summary>
        internal static string AsnWriter_ModifyingWhileEncoding
        {
            get
            {
                return ResourceManager.GetString("AsnWriter_ModifyingWhileEncoding", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot pop the requested tag as it is not currently in progress.
        /// </summary>
        internal static string AsnWriter_PopWrongTag
        {
            get
            {
                return ResourceManager.GetString("AsnWriter_PopWrongTag", resourceCulture);
            }
        }



        /// <summary>
        /// A constructed tag used a definite length encoding, which is invalid for CER data. The input may be encoded with BER or DER.
        /// </summary>
        internal static string ContentException_CerRequiresIndefiniteLength
        {
            get
            {
                return ResourceManager.GetString("ContentException_CerRequiresIndefiniteLength", resourceCulture);
            }
        }



        /// <summary>
        /// The encoded value uses a primitive encoding, which is invalid for '{0}' values.
        /// </summary>
        internal static string ContentException_ConstructedEncodingRequired
        {
            get
            {
                return ResourceManager.GetString("ContentException_ConstructedEncodingRequired", resourceCulture);
            }
        }


        internal static string FormatContentException_ConstructedEncodingRequired(object arg1)
        {
            return string.Format(ContentException_ConstructedEncodingRequired, arg1);
        }


        /// <summary>
        /// The ASN.1 value is invalid.
        /// </summary>
        internal static string ContentException_DefaultMessage
        {
            get
            {
                return ResourceManager.GetString("ContentException_DefaultMessage", resourceCulture);
            }
        }



        /// <summary>
        /// The encoded enumerated value is larger than the value size of the '{0}' enum.
        /// </summary>
        internal static string ContentException_EnumeratedValueTooBig
        {
            get
            {
                return ResourceManager.GetString("ContentException_EnumeratedValueTooBig", resourceCulture);
            }
        }


        internal static string FormatContentException_EnumeratedValueTooBig(object arg1)
        {
            return string.Format(ContentException_EnumeratedValueTooBig, arg1);
        }


        /// <summary>
        /// The encoded value is not valid under the selected encoding, but it may be valid under the BER or DER encoding.
        /// </summary>
        internal static string ContentException_InvalidUnderCer_TryBerOrDer
        {
            get
            {
                return ResourceManager.GetString("ContentException_InvalidUnderCer_TryBerOrDer", resourceCulture);
            }
        }



        /// <summary>
        /// The encoded value is not valid under the selected encoding, but it may be valid under the BER encoding.
        /// </summary>
        internal static string ContentException_InvalidUnderCerOrDer_TryBer
        {
            get
            {
                return ResourceManager.GetString("ContentException_InvalidUnderCerOrDer_TryBer", resourceCulture);
            }
        }



        /// <summary>
        /// The encoded value is not valid under the selected encoding, but it may be valid under the BER or CER encoding.
        /// </summary>
        internal static string ContentException_InvalidUnderDer_TryBerOrCer
        {
            get
            {
                return ResourceManager.GetString("ContentException_InvalidUnderDer_TryBerOrCer", resourceCulture);
            }
        }



        /// <summary>
        /// The provided data does not represent a valid tag.
        /// </summary>
        internal static string ContentException_InvalidTag
        {
            get
            {
                return ResourceManager.GetString("ContentException_InvalidTag", resourceCulture);
            }
        }



        /// <summary>
        /// The encoded length exceeds the number of bytes remaining in the input buffer.
        /// </summary>
        internal static string ContentException_LengthExceedsPayload
        {
            get
            {
                return ResourceManager.GetString("ContentException_LengthExceedsPayload", resourceCulture);
            }
        }



        /// <summary>
        /// The encoded length is not valid under the requested encoding rules, the value may be valid under the BER encoding.
        /// </summary>
        internal static string ContentException_LengthRuleSetConstraint
        {
            get
            {
                return ResourceManager.GetString("ContentException_LengthRuleSetConstraint", resourceCulture);
            }
        }



        /// <summary>
        /// The encoded length exceeds the maximum supported by this library (Int32.MaxValue).
        /// </summary>
        internal static string ContentException_LengthTooBig
        {
            get
            {
                return ResourceManager.GetString("ContentException_LengthTooBig", resourceCulture);
            }
        }



        /// <summary>
        /// The encoded named bit list value is larger than the value size of the '{0}' enum.
        /// </summary>
        internal static string ContentException_NamedBitListValueTooBig
        {
            get
            {
                return ResourceManager.GetString("ContentException_NamedBitListValueTooBig", resourceCulture);
            }
        }


        internal static string FormatContentException_NamedBitListValueTooBig(object arg1)
        {
            return string.Format(ContentException_NamedBitListValueTooBig, arg1);
        }


        /// <summary>
        /// The encoded object identifier (OID) exceeds the limits supported by this library. Supported OIDs are limited to 64 arcs and each subidentifier is limited to a 128-bit value.
        /// </summary>
        internal static string ContentException_OidTooBig
        {
            get
            {
                return ResourceManager.GetString("ContentException_OidTooBig", resourceCulture);
            }
        }



        /// <summary>
        /// The encoded value uses a constructed encoding, which is invalid for '{0}' values.
        /// </summary>
        internal static string ContentException_PrimitiveEncodingRequired
        {
            get
            {
                return ResourceManager.GetString("ContentException_PrimitiveEncodingRequired", resourceCulture);
            }
        }


        internal static string FormatContentException_PrimitiveEncodingRequired(object arg1)
        {
            return string.Format(ContentException_PrimitiveEncodingRequired, arg1);
        }


        /// <summary>
        /// The encoded set is not sorted as required by the current encoding rules. The value may be valid under the BER encoding, or you can ignore the sort validation by specifying skipSortValidation=true.
        /// </summary>
        internal static string ContentException_SetOfNotSorted
        {
            get
            {
                return ResourceManager.GetString("ContentException_SetOfNotSorted", resourceCulture);
            }
        }



        /// <summary>
        /// The last expected value has been read, but the reader still has pending data. This value may be from a newer schema, or is corrupt.
        /// </summary>
        internal static string ContentException_TooMuchData
        {
            get
            {
                return ResourceManager.GetString("ContentException_TooMuchData", resourceCulture);
            }
        }



        /// <summary>
        /// The provided data is tagged with '{0}' class value '{1}', but it should have been '{2}' class value '{3}'.
        /// </summary>
        internal static string ContentException_WrongTag
        {
            get
            {
                return ResourceManager.GetString("ContentException_WrongTag", resourceCulture);
            }
        }


        internal static string FormatContentException_WrongTag(object arg1, object arg2, object arg3, object arg4)
        {
            return string.Format(ContentException_WrongTag, arg1, arg2, arg3, arg4);
        }
    }
}
