
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CSharp", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// An unexpected exception occurred while binding a dynamic operation
        /// </summary>
        internal static string InternalCompilerError
        {
            get
            {
                return ResourceManager.GetString("InternalCompilerError", resourceCulture);
            }
        }



        /// <summary>
        /// The name '{0}' is bound to a method and cannot be used like a property
        /// </summary>
        internal static string BindPropertyFailedMethodGroup
        {
            get
            {
                return ResourceManager.GetString("BindPropertyFailedMethodGroup", resourceCulture);
            }
        }


        internal static string FormatBindPropertyFailedMethodGroup(object arg1)
        {
            return string.Format(BindPropertyFailedMethodGroup, arg1);
        }


        /// <summary>
        /// The event '{0}' can only appear on the left hand side of +
        /// </summary>
        internal static string BindPropertyFailedEvent
        {
            get
            {
                return ResourceManager.GetString("BindPropertyFailedEvent", resourceCulture);
            }
        }


        internal static string FormatBindPropertyFailedEvent(object arg1)
        {
            return string.Format(BindPropertyFailedEvent, arg1);
        }


        /// <summary>
        /// Cannot invoke a non-delegate type
        /// </summary>
        internal static string BindInvokeFailedNonDelegate
        {
            get
            {
                return ResourceManager.GetString("BindInvokeFailedNonDelegate", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot perform runtime binding on a null reference
        /// </summary>
        internal static string NullReferenceOnMemberException
        {
            get
            {
                return ResourceManager.GetString("NullReferenceOnMemberException", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot dynamically invoke method '{0}' because it has a Conditional attribute
        /// </summary>
        internal static string BindCallToConditionalMethod
        {
            get
            {
                return ResourceManager.GetString("BindCallToConditionalMethod", resourceCulture);
            }
        }


        internal static string FormatBindCallToConditionalMethod(object arg1)
        {
            return string.Format(BindCallToConditionalMethod, arg1);
        }


        /// <summary>
        /// Cannot implicitly convert type 'void' to 'object'
        /// </summary>
        internal static string BindToVoidMethodButExpectResult
        {
            get
            {
                return ResourceManager.GetString("BindToVoidMethodButExpectResult", resourceCulture);
            }
        }



        /// <summary>
        /// No further information on this object could be discovered
        /// </summary>
        internal static string EmptyDynamicView
        {
            get
            {
                return ResourceManager.GetString("EmptyDynamicView", resourceCulture);
            }
        }



        /// <summary>
        /// Write Only properties are not supported
        /// </summary>
        internal static string GetValueonWriteOnlyProperty
        {
            get
            {
                return ResourceManager.GetString("GetValueonWriteOnlyProperty", resourceCulture);
            }
        }



        /// <summary>
        /// Operator '{0}' cannot be applied to operands of type '{1}' and '{2}'
        /// </summary>
        internal static string BadBinaryOps
        {
            get
            {
                return ResourceManager.GetString("BadBinaryOps", resourceCulture);
            }
        }


        internal static string FormatBadBinaryOps(object arg1, object arg2, object arg3)
        {
            return string.Format(BadBinaryOps, arg1, arg2, arg3);
        }


        /// <summary>
        /// Cannot apply indexing with [] to an expression of type '{0}'
        /// </summary>
        internal static string BadIndexLHS
        {
            get
            {
                return ResourceManager.GetString("BadIndexLHS", resourceCulture);
            }
        }


        internal static string FormatBadIndexLHS(object arg1)
        {
            return string.Format(BadIndexLHS, arg1);
        }


        /// <summary>
        /// Wrong number of indices inside []; expected '{0}'
        /// </summary>
        internal static string BadIndexCount
        {
            get
            {
                return ResourceManager.GetString("BadIndexCount", resourceCulture);
            }
        }


        internal static string FormatBadIndexCount(object arg1)
        {
            return string.Format(BadIndexCount, arg1);
        }


        /// <summary>
        /// Operator '{0}' cannot be applied to operand of type '{1}'
        /// </summary>
        internal static string BadUnaryOp
        {
            get
            {
                return ResourceManager.GetString("BadUnaryOp", resourceCulture);
            }
        }


        internal static string FormatBadUnaryOp(object arg1, object arg2)
        {
            return string.Format(BadUnaryOp, arg1, arg2);
        }


        /// <summary>
        /// Cannot implicitly convert type '{0}' to '{1}'
        /// </summary>
        internal static string NoImplicitConv
        {
            get
            {
                return ResourceManager.GetString("NoImplicitConv", resourceCulture);
            }
        }


        internal static string FormatNoImplicitConv(object arg1, object arg2)
        {
            return string.Format(NoImplicitConv, arg1, arg2);
        }


        /// <summary>
        /// Cannot convert type '{0}' to '{1}'
        /// </summary>
        internal static string NoExplicitConv
        {
            get
            {
                return ResourceManager.GetString("NoExplicitConv", resourceCulture);
            }
        }


        internal static string FormatNoExplicitConv(object arg1, object arg2)
        {
            return string.Format(NoExplicitConv, arg1, arg2);
        }


        /// <summary>
        /// Constant value '{0}' cannot be converted to a '{1}'
        /// </summary>
        internal static string ConstOutOfRange
        {
            get
            {
                return ResourceManager.GetString("ConstOutOfRange", resourceCulture);
            }
        }


        internal static string FormatConstOutOfRange(object arg1, object arg2)
        {
            return string.Format(ConstOutOfRange, arg1, arg2);
        }


        /// <summary>
        /// Operator '{0}' is ambiguous on operands of type '{1}' and '{2}'
        /// </summary>
        internal static string AmbigBinaryOps
        {
            get
            {
                return ResourceManager.GetString("AmbigBinaryOps", resourceCulture);
            }
        }


        internal static string FormatAmbigBinaryOps(object arg1, object arg2, object arg3)
        {
            return string.Format(AmbigBinaryOps, arg1, arg2, arg3);
        }


        /// <summary>
        /// Operator '{0}' is ambiguous on an operand of type '{1}'
        /// </summary>
        internal static string AmbigUnaryOp
        {
            get
            {
                return ResourceManager.GetString("AmbigUnaryOp", resourceCulture);
            }
        }


        internal static string FormatAmbigUnaryOp(object arg1, object arg2)
        {
            return string.Format(AmbigUnaryOp, arg1, arg2);
        }


        /// <summary>
        /// Cannot convert null to '{0}' because it is a non-nullable value type
        /// </summary>
        internal static string ValueCantBeNull
        {
            get
            {
                return ResourceManager.GetString("ValueCantBeNull", resourceCulture);
            }
        }


        internal static string FormatValueCantBeNull(object arg1)
        {
            return string.Format(ValueCantBeNull, arg1);
        }


        /// <summary>
        /// '{0}' does not contain a definition for '{1}'
        /// </summary>
        internal static string NoSuchMember
        {
            get
            {
                return ResourceManager.GetString("NoSuchMember", resourceCulture);
            }
        }


        internal static string FormatNoSuchMember(object arg1, object arg2)
        {
            return string.Format(NoSuchMember, arg1, arg2);
        }


        /// <summary>
        /// An object reference is required for the non-static field, method, or property '{0}'
        /// </summary>
        internal static string ObjectRequired
        {
            get
            {
                return ResourceManager.GetString("ObjectRequired", resourceCulture);
            }
        }


        internal static string FormatObjectRequired(object arg1)
        {
            return string.Format(ObjectRequired, arg1);
        }


        /// <summary>
        /// The call is ambiguous between the following methods or properties: '{0}' and '{1}'
        /// </summary>
        internal static string AmbigCall
        {
            get
            {
                return ResourceManager.GetString("AmbigCall", resourceCulture);
            }
        }


        internal static string FormatAmbigCall(object arg1, object arg2)
        {
            return string.Format(AmbigCall, arg1, arg2);
        }


        /// <summary>
        /// '{0}' is inaccessible due to its protection level
        /// </summary>
        internal static string BadAccess
        {
            get
            {
                return ResourceManager.GetString("BadAccess", resourceCulture);
            }
        }


        internal static string FormatBadAccess(object arg1)
        {
            return string.Format(BadAccess, arg1);
        }


        /// <summary>
        /// The left-hand side of an assignment must be a variable, property or indexer
        /// </summary>
        internal static string AssgLvalueExpected
        {
            get
            {
                return ResourceManager.GetString("AssgLvalueExpected", resourceCulture);
            }
        }



        /// <summary>
        /// The type '{0}' has no constructors defined
        /// </summary>
        internal static string NoConstructors
        {
            get
            {
                return ResourceManager.GetString("NoConstructors", resourceCulture);
            }
        }


        internal static string FormatNoConstructors(object arg1)
        {
            return string.Format(NoConstructors, arg1);
        }


        /// <summary>
        /// The property or indexer '{0}' cannot be used in this context because it lacks the get accessor
        /// </summary>
        internal static string PropertyLacksGet
        {
            get
            {
                return ResourceManager.GetString("PropertyLacksGet", resourceCulture);
            }
        }


        internal static string FormatPropertyLacksGet(object arg1)
        {
            return string.Format(PropertyLacksGet, arg1);
        }


        /// <summary>
        /// Member '{0}' cannot be accessed with an instance reference; qualify it with a type name instead
        /// </summary>
        internal static string ObjectProhibited
        {
            get
            {
                return ResourceManager.GetString("ObjectProhibited", resourceCulture);
            }
        }


        internal static string FormatObjectProhibited(object arg1)
        {
            return string.Format(ObjectProhibited, arg1);
        }


        /// <summary>
        /// A readonly field cannot be assigned to (except in a constructor or a variable initializer)
        /// </summary>
        internal static string AssgReadonly
        {
            get
            {
                return ResourceManager.GetString("AssgReadonly", resourceCulture);
            }
        }



        /// <summary>
        /// A static readonly field cannot be assigned to (except in a static constructor or a variable initializer)
        /// </summary>
        internal static string AssgReadonlyStatic
        {
            get
            {
                return ResourceManager.GetString("AssgReadonlyStatic", resourceCulture);
            }
        }



        /// <summary>
        /// Property or indexer '{0}' cannot be assigned to -- it is read only
        /// </summary>
        internal static string AssgReadonlyProp
        {
            get
            {
                return ResourceManager.GetString("AssgReadonlyProp", resourceCulture);
            }
        }


        internal static string FormatAssgReadonlyProp(object arg1)
        {
            return string.Format(AssgReadonlyProp, arg1);
        }


        /// <summary>
        /// Dynamic calls cannot be used in conjunction with pointers
        /// </summary>
        internal static string UnsafeNeeded
        {
            get
            {
                return ResourceManager.GetString("UnsafeNeeded", resourceCulture);
            }
        }



        /// <summary>
        /// In order to be applicable as a short circuit operator a user-defined logical operator ('{0}') must have the same return type as the type of its 2 parameters
        /// </summary>
        internal static string BadBoolOp
        {
            get
            {
                return ResourceManager.GetString("BadBoolOp", resourceCulture);
            }
        }


        internal static string FormatBadBoolOp(object arg1)
        {
            return string.Format(BadBoolOp, arg1);
        }


        /// <summary>
        /// The type ('{0}') must contain declarations of operator true and operator false
        /// </summary>
        internal static string MustHaveOpTF
        {
            get
            {
                return ResourceManager.GetString("MustHaveOpTF", resourceCulture);
            }
        }


        internal static string FormatMustHaveOpTF(object arg1)
        {
            return string.Format(MustHaveOpTF, arg1);
        }


        /// <summary>
        /// Constant value '{0}' cannot be converted to a '{1}' (use 'unchecked' syntax to override)
        /// </summary>
        internal static string ConstOutOfRangeChecked
        {
            get
            {
                return ResourceManager.GetString("ConstOutOfRangeChecked", resourceCulture);
            }
        }


        internal static string FormatConstOutOfRangeChecked(object arg1, object arg2)
        {
            return string.Format(ConstOutOfRangeChecked, arg1, arg2);
        }


        /// <summary>
        /// Ambiguity between '{0}' and '{1}'
        /// </summary>
        internal static string AmbigMember
        {
            get
            {
                return ResourceManager.GetString("AmbigMember", resourceCulture);
            }
        }


        internal static string FormatAmbigMember(object arg1, object arg2)
        {
            return string.Format(AmbigMember, arg1, arg2);
        }


        /// <summary>
        /// Cannot implicitly convert type '{0}' to '{1}'. An explicit conversion exists (are you missing a cast?)
        /// </summary>
        internal static string NoImplicitConvCast
        {
            get
            {
                return ResourceManager.GetString("NoImplicitConvCast", resourceCulture);
            }
        }


        internal static string FormatNoImplicitConvCast(object arg1, object arg2)
        {
            return string.Format(NoImplicitConvCast, arg1, arg2);
        }


        /// <summary>
        /// The property or indexer '{0}' cannot be used in this context because the get accessor is inaccessible
        /// </summary>
        internal static string InaccessibleGetter
        {
            get
            {
                return ResourceManager.GetString("InaccessibleGetter", resourceCulture);
            }
        }


        internal static string FormatInaccessibleGetter(object arg1)
        {
            return string.Format(InaccessibleGetter, arg1);
        }


        /// <summary>
        /// The property or indexer '{0}' cannot be used in this context because the set accessor is inaccessible
        /// </summary>
        internal static string InaccessibleSetter
        {
            get
            {
                return ResourceManager.GetString("InaccessibleSetter", resourceCulture);
            }
        }


        internal static string FormatInaccessibleSetter(object arg1)
        {
            return string.Format(InaccessibleSetter, arg1);
        }


        /// <summary>
        /// Using the generic {1} '{0}' requires '{2}' type arguments
        /// </summary>
        internal static string BadArity
        {
            get
            {
                return ResourceManager.GetString("BadArity", resourceCulture);
            }
        }


        internal static string FormatBadArity(object arg1, object arg2, object arg3)
        {
            return string.Format(BadArity, arg1, arg2, arg3);
        }


        /// <summary>
        /// The {1} '{0}' cannot be used with type arguments
        /// </summary>
        internal static string TypeArgsNotAllowed
        {
            get
            {
                return ResourceManager.GetString("TypeArgsNotAllowed", resourceCulture);
            }
        }


        internal static string FormatTypeArgsNotAllowed(object arg1, object arg2)
        {
            return string.Format(TypeArgsNotAllowed, arg1, arg2);
        }


        /// <summary>
        /// The non-generic {1} '{0}' cannot be used with type arguments
        /// </summary>
        internal static string HasNoTypeVars
        {
            get
            {
                return ResourceManager.GetString("HasNoTypeVars", resourceCulture);
            }
        }


        internal static string FormatHasNoTypeVars(object arg1, object arg2)
        {
            return string.Format(HasNoTypeVars, arg1, arg2);
        }


        /// <summary>
        /// '{2}' must be a non-abstract type with a public parameterless constructor in order to use it as parameter '{1}' in the generic type or method '{0}'
        /// </summary>
        internal static string NewConstraintNotSatisfied
        {
            get
            {
                return ResourceManager.GetString("NewConstraintNotSatisfied", resourceCulture);
            }
        }


        internal static string FormatNewConstraintNotSatisfied(object arg1, object arg2, object arg3)
        {
            return string.Format(NewConstraintNotSatisfied, arg1, arg2, arg3);
        }


        /// <summary>
        /// The type '{3}' cannot be used as type parameter '{2}' in the generic type or method '{0}'. There is no implicit reference conversion from '{3}' to '{1}'.
        /// </summary>
        internal static string GenericConstraintNotSatisfiedRefType
        {
            get
            {
                return ResourceManager.GetString("GenericConstraintNotSatisfiedRefType", resourceCulture);
            }
        }


        internal static string FormatGenericConstraintNotSatisfiedRefType(object arg1, object arg2, object arg3, object arg4, object arg5)
        {
            return string.Format(GenericConstraintNotSatisfiedRefType, arg1, arg2, arg3, arg4, arg5);
        }


        /// <summary>
        /// The type '{3}' cannot be used as type parameter '{2}' in the generic type or method '{0}'. The nullable type '{3}' does not satisfy the constraint of '{1}'.
        /// </summary>
        internal static string GenericConstraintNotSatisfiedNullableEnum
        {
            get
            {
                return ResourceManager.GetString("GenericConstraintNotSatisfiedNullableEnum", resourceCulture);
            }
        }


        internal static string FormatGenericConstraintNotSatisfiedNullableEnum(object arg1, object arg2, object arg3, object arg4, object arg5)
        {
            return string.Format(GenericConstraintNotSatisfiedNullableEnum, arg1, arg2, arg3, arg4, arg5);
        }


        /// <summary>
        /// The type '{3}' cannot be used as type parameter '{2}' in the generic type or method '{0}'. The nullable type '{3}' does not satisfy the constraint of '{1}'. Nullable types can not satisfy any interface constraints.
        /// </summary>
        internal static string GenericConstraintNotSatisfiedNullableInterface
        {
            get
            {
                return ResourceManager.GetString("GenericConstraintNotSatisfiedNullableInterface", resourceCulture);
            }
        }


        internal static string FormatGenericConstraintNotSatisfiedNullableInterface(object arg1, object arg2, object arg3, object arg4, object arg5)
        {
            return string.Format(GenericConstraintNotSatisfiedNullableInterface, arg1, arg2, arg3, arg4, arg5);
        }


        /// <summary>
        /// The type '{3}' cannot be used as type parameter '{2}' in the generic type or method '{0}'. There is no boxing conversion from '{3}' to '{1}'.
        /// </summary>
        internal static string GenericConstraintNotSatisfiedValType
        {
            get
            {
                return ResourceManager.GetString("GenericConstraintNotSatisfiedValType", resourceCulture);
            }
        }


        internal static string FormatGenericConstraintNotSatisfiedValType(object arg1, object arg2, object arg3, object arg4, object arg5)
        {
            return string.Format(GenericConstraintNotSatisfiedValType, arg1, arg2, arg3, arg4, arg5);
        }


        /// <summary>
        /// The type arguments for method '{0}' cannot be inferred from the usage. Try specifying the type arguments explicitly.
        /// </summary>
        internal static string CantInferMethTypeArgs
        {
            get
            {
                return ResourceManager.GetString("CantInferMethTypeArgs", resourceCulture);
            }
        }


        internal static string FormatCantInferMethTypeArgs(object arg1)
        {
            return string.Format(CantInferMethTypeArgs, arg1);
        }


        /// <summary>
        /// The type '{2}' must be a reference type in order to use it as parameter '{1}' in the generic type or method '{0}'
        /// </summary>
        internal static string RefConstraintNotSatisfied
        {
            get
            {
                return ResourceManager.GetString("RefConstraintNotSatisfied", resourceCulture);
            }
        }


        internal static string FormatRefConstraintNotSatisfied(object arg1, object arg2, object arg3)
        {
            return string.Format(RefConstraintNotSatisfied, arg1, arg2, arg3);
        }


        /// <summary>
        /// The type '{2}' must be a non-nullable value type in order to use it as parameter '{1}' in the generic type or method '{0}'
        /// </summary>
        internal static string ValConstraintNotSatisfied
        {
            get
            {
                return ResourceManager.GetString("ValConstraintNotSatisfied", resourceCulture);
            }
        }


        internal static string FormatValConstraintNotSatisfied(object arg1, object arg2, object arg3)
        {
            return string.Format(ValConstraintNotSatisfied, arg1, arg2, arg3);
        }


        /// <summary>
        /// Ambiguous user defined conversions '{0}' and '{1}' when converting from '{2}' to '{3}'
        /// </summary>
        internal static string AmbigUDConv
        {
            get
            {
                return ResourceManager.GetString("AmbigUDConv", resourceCulture);
            }
        }


        internal static string FormatAmbigUDConv(object arg1, object arg2, object arg3, object arg4)
        {
            return string.Format(AmbigUDConv, arg1, arg2, arg3, arg4);
        }


        /// <summary>
        /// '{0}' is not supported by the language
        /// </summary>
        internal static string BindToBogus
        {
            get
            {
                return ResourceManager.GetString("BindToBogus", resourceCulture);
            }
        }


        internal static string FormatBindToBogus(object arg1)
        {
            return string.Format(BindToBogus, arg1);
        }


        /// <summary>
        /// '{0}': cannot explicitly call operator or accessor
        /// </summary>
        internal static string CantCallSpecialMethod
        {
            get
            {
                return ResourceManager.GetString("CantCallSpecialMethod", resourceCulture);
            }
        }


        internal static string FormatCantCallSpecialMethod(object arg1)
        {
            return string.Format(CantCallSpecialMethod, arg1);
        }


        /// <summary>
        /// Cannot convert to static type '{0}'
        /// </summary>
        internal static string ConvertToStaticClass
        {
            get
            {
                return ResourceManager.GetString("ConvertToStaticClass", resourceCulture);
            }
        }


        internal static string FormatConvertToStaticClass(object arg1)
        {
            return string.Format(ConvertToStaticClass, arg1);
        }


        /// <summary>
        /// The operand of an increment or decrement operator must be a variable, property or indexer
        /// </summary>
        internal static string IncrementLvalueExpected
        {
            get
            {
                return ResourceManager.GetString("IncrementLvalueExpected", resourceCulture);
            }
        }



        /// <summary>
        /// No overload for method '{0}' takes {1} arguments
        /// </summary>
        internal static string BadArgCount
        {
            get
            {
                return ResourceManager.GetString("BadArgCount", resourceCulture);
            }
        }


        internal static string FormatBadArgCount(object arg1, object arg2)
        {
            return string.Format(BadArgCount, arg1, arg2);
        }


        /// <summary>
        /// The best overloaded method match for '{0}' has some invalid arguments
        /// </summary>
        internal static string BadArgTypes
        {
            get
            {
                return ResourceManager.GetString("BadArgTypes", resourceCulture);
            }
        }


        internal static string FormatBadArgTypes(object arg1)
        {
            return string.Format(BadArgTypes, arg1);
        }


        /// <summary>
        /// Cannot access protected member '{0}' via a qualifier of type '{1}'; the qualifier must be of type '{2}' (or derived from it)
        /// </summary>
        internal static string BadProtectedAccess
        {
            get
            {
                return ResourceManager.GetString("BadProtectedAccess", resourceCulture);
            }
        }


        internal static string FormatBadProtectedAccess(object arg1, object arg2, object arg3)
        {
            return string.Format(BadProtectedAccess, arg1, arg2, arg3);
        }


        /// <summary>
        /// Property, indexer, or event '{0}' is not supported by the language; try directly calling accessor methods '{1}' or '{2}'
        /// </summary>
        internal static string BindToBogusProp2
        {
            get
            {
                return ResourceManager.GetString("BindToBogusProp2", resourceCulture);
            }
        }


        internal static string FormatBindToBogusProp2(object arg1, object arg2, object arg3)
        {
            return string.Format(BindToBogusProp2, arg1, arg2, arg3);
        }


        /// <summary>
        /// Property, indexer, or event '{0}' is not supported by the language; try directly calling accessor method '{1}'
        /// </summary>
        internal static string BindToBogusProp1
        {
            get
            {
                return ResourceManager.GetString("BindToBogusProp1", resourceCulture);
            }
        }


        internal static string FormatBindToBogusProp1(object arg1, object arg2)
        {
            return string.Format(BindToBogusProp1, arg1, arg2);
        }


        /// <summary>
        /// Delegate '{0}' does not take '{1}' arguments
        /// </summary>
        internal static string BadDelArgCount
        {
            get
            {
                return ResourceManager.GetString("BadDelArgCount", resourceCulture);
            }
        }


        internal static string FormatBadDelArgCount(object arg1, object arg2)
        {
            return string.Format(BadDelArgCount, arg1, arg2);
        }


        /// <summary>
        /// Delegate '{0}' has some invalid arguments
        /// </summary>
        internal static string BadDelArgTypes
        {
            get
            {
                return ResourceManager.GetString("BadDelArgTypes", resourceCulture);
            }
        }


        internal static string FormatBadDelArgTypes(object arg1)
        {
            return string.Format(BadDelArgTypes, arg1);
        }


        /// <summary>
        /// '{0}' does not contain a constructor that takes '{1}' arguments
        /// </summary>
        internal static string BadCtorArgCount
        {
            get
            {
                return ResourceManager.GetString("BadCtorArgCount", resourceCulture);
            }
        }


        internal static string FormatBadCtorArgCount(object arg1, object arg2)
        {
            return string.Format(BadCtorArgCount, arg1, arg2);
        }


        /// <summary>
        /// Non-invocable member '{0}' cannot be used like a method.
        /// </summary>
        internal static string NonInvocableMemberCalled
        {
            get
            {
                return ResourceManager.GetString("NonInvocableMemberCalled", resourceCulture);
            }
        }


        internal static string FormatNonInvocableMemberCalled(object arg1)
        {
            return string.Format(NonInvocableMemberCalled, arg1);
        }


        /// <summary>
        /// The best overload for '{0}' does not have a parameter named '{1}'
        /// </summary>
        internal static string BadNamedArgument
        {
            get
            {
                return ResourceManager.GetString("BadNamedArgument", resourceCulture);
            }
        }


        internal static string FormatBadNamedArgument(object arg1, object arg2)
        {
            return string.Format(BadNamedArgument, arg1, arg2);
        }


        /// <summary>
        /// The delegate '{0}' does not have a parameter named '{1}'
        /// </summary>
        internal static string BadNamedArgumentForDelegateInvoke
        {
            get
            {
                return ResourceManager.GetString("BadNamedArgumentForDelegateInvoke", resourceCulture);
            }
        }


        internal static string FormatBadNamedArgumentForDelegateInvoke(object arg1, object arg2)
        {
            return string.Format(BadNamedArgumentForDelegateInvoke, arg1, arg2);
        }


        /// <summary>
        /// Named argument '{0}' cannot be specified multiple times
        /// </summary>
        internal static string DuplicateNamedArgument
        {
            get
            {
                return ResourceManager.GetString("DuplicateNamedArgument", resourceCulture);
            }
        }


        internal static string FormatDuplicateNamedArgument(object arg1)
        {
            return string.Format(DuplicateNamedArgument, arg1);
        }


        /// <summary>
        /// Named argument '{0}' specifies a parameter for which a positional argument has already been given
        /// </summary>
        internal static string NamedArgumentUsedInPositional
        {
            get
            {
                return ResourceManager.GetString("NamedArgumentUsedInPositional", resourceCulture);
            }
        }


        internal static string FormatNamedArgumentUsedInPositional(object arg1)
        {
            return string.Format(NamedArgumentUsedInPositional, arg1);
        }


        /// <summary>
        /// The first argument to dynamically-bound static or constructor call must be a Type
        /// </summary>
        internal static string TypeArgumentRequiredForStaticCall
        {
            get
            {
                return ResourceManager.GetString("TypeArgumentRequiredForStaticCall", resourceCulture);
            }
        }



        /// <summary>
        /// The runtime binder cannot bind a metaobject without a value
        /// </summary>
        internal static string DynamicArgumentNeedsValue
        {
            get
            {
                return ResourceManager.GetString("DynamicArgumentNeedsValue", resourceCulture);
            }
        }



        /// <summary>
        /// Named argument '{0}' is used out-of-position but is followed by an unnamed argument
        /// </summary>
        internal static string BadNonTrailingNamedArgument
        {
            get
            {
                return ResourceManager.GetString("BadNonTrailingNamedArgument", resourceCulture);
            }
        }


        internal static string FormatBadNonTrailingNamedArgument(object arg1)
        {
            return string.Format(BadNonTrailingNamedArgument, arg1);
        }


        /// <summary>
        /// anonymous method
        /// </summary>
        internal static string AnonMethod
        {
            get
            {
                return ResourceManager.GetString("AnonMethod", resourceCulture);
            }
        }



        /// <summary>
        /// The C# runtime binder cannot dynamically resolve members on COM Runtime Callable Wrappers.
        /// </summary>
        internal static string DynamicBindingComUnsupported
        {
            get
            {
                return ResourceManager.GetString("DynamicBindingComUnsupported", resourceCulture);
            }
        }



        /// <summary>
        /// <error>
        /// </summary>
        internal static string ERRORSYM
        {
            get
            {
                return ResourceManager.GetString("ERRORSYM", resourceCulture);
            }
        }



        /// <summary>
        /// <global namespace>
        /// </summary>
        internal static string GlobalNamespace
        {
            get
            {
                return ResourceManager.GetString("GlobalNamespace", resourceCulture);
            }
        }



        /// <summary>
        /// lambda expression
        /// </summary>
        internal static string Lambda
        {
            get
            {
                return ResourceManager.GetString("Lambda", resourceCulture);
            }
        }



        /// <summary>
        /// method group
        /// </summary>
        internal static string MethodGroup
        {
            get
            {
                return ResourceManager.GetString("MethodGroup", resourceCulture);
            }
        }



        /// <summary>
        /// <null>
        /// </summary>
        internal static string NULL
        {
            get
            {
                return ResourceManager.GetString("NULL", resourceCulture);
            }
        }



        /// <summary>
        /// using alias
        /// </summary>
        internal static string SK_ALIAS
        {
            get
            {
                return ResourceManager.GetString("SK_ALIAS", resourceCulture);
            }
        }



        /// <summary>
        /// type
        /// </summary>
        internal static string SK_CLASS
        {
            get
            {
                return ResourceManager.GetString("SK_CLASS", resourceCulture);
            }
        }



        /// <summary>
        /// event
        /// </summary>
        internal static string SK_EVENT
        {
            get
            {
                return ResourceManager.GetString("SK_EVENT", resourceCulture);
            }
        }



        /// <summary>
        /// field
        /// </summary>
        internal static string SK_FIELD
        {
            get
            {
                return ResourceManager.GetString("SK_FIELD", resourceCulture);
            }
        }



        /// <summary>
        /// method
        /// </summary>
        internal static string SK_METHOD
        {
            get
            {
                return ResourceManager.GetString("SK_METHOD", resourceCulture);
            }
        }



        /// <summary>
        /// namespace
        /// </summary>
        internal static string SK_NAMESPACE
        {
            get
            {
                return ResourceManager.GetString("SK_NAMESPACE", resourceCulture);
            }
        }



        /// <summary>
        /// property
        /// </summary>
        internal static string SK_PROPERTY
        {
            get
            {
                return ResourceManager.GetString("SK_PROPERTY", resourceCulture);
            }
        }



        /// <summary>
        /// type parameter
        /// </summary>
        internal static string SK_TYVAR
        {
            get
            {
                return ResourceManager.GetString("SK_TYVAR", resourceCulture);
            }
        }



        /// <summary>
        /// element
        /// </summary>
        internal static string SK_UNKNOWN
        {
            get
            {
                return ResourceManager.GetString("SK_UNKNOWN", resourceCulture);
            }
        }



        /// <summary>
        /// variable
        /// </summary>
        internal static string SK_VARIABLE
        {
            get
            {
                return ResourceManager.GetString("SK_VARIABLE", resourceCulture);
            }
        }



        /// <summary>
        /// There are valid conversions from {0} to {1}.
        /// </summary>
        internal static string COMAmbiguousConversion
        {
            get
            {
                return ResourceManager.GetString("COMAmbiguousConversion", resourceCulture);
            }
        }


        internal static string FormatCOMAmbiguousConversion(object arg1, object arg2)
        {
            return string.Format(COMAmbiguousConversion, arg1, arg2);
        }


        /// <summary>
        /// Cannot perform call.
        /// </summary>
        internal static string COMCannotPerformCall
        {
            get
            {
                return ResourceManager.GetString("COMCannotPerformCall", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot retrieve type information.
        /// </summary>
        internal static string COMCannotRetrieveTypeInfo
        {
            get
            {
                return ResourceManager.GetString("COMCannotRetrieveTypeInfo", resourceCulture);
            }
        }



        /// <summary>
        /// Error while invoking {0}.
        /// </summary>
        internal static string COMDispatchInvokeError
        {
            get
            {
                return ResourceManager.GetString("COMDispatchInvokeError", resourceCulture);
            }
        }


        internal static string FormatCOMDispatchInvokeError(object arg1)
        {
            return string.Format(COMDispatchInvokeError, arg1);
        }


        /// <summary>
        /// Error while invoking {0}. Named arguments are not supported.
        /// </summary>
        internal static string COMDispatchInvokeErrorNoNamedArgs
        {
            get
            {
                return ResourceManager.GetString("COMDispatchInvokeErrorNoNamedArgs", resourceCulture);
            }
        }


        internal static string FormatCOMDispatchInvokeErrorNoNamedArgs(object arg1)
        {
            return string.Format(COMDispatchInvokeErrorNoNamedArgs, arg1);
        }


        /// <summary>
        /// Error while invoking {0}. A required parameter was omitted.
        /// </summary>
        internal static string COMDispatchInvokeErrorParamNotOptional
        {
            get
            {
                return ResourceManager.GetString("COMDispatchInvokeErrorParamNotOptional", resourceCulture);
            }
        }


        internal static string FormatCOMDispatchInvokeErrorParamNotOptional(object arg1)
        {
            return string.Format(COMDispatchInvokeErrorParamNotOptional, arg1);
        }


        /// <summary>
        /// Could not convert argument {0} for call to {1}.
        /// </summary>
        internal static string COMDispatchInvokeErrorTypeMismatch
        {
            get
            {
                return ResourceManager.GetString("COMDispatchInvokeErrorTypeMismatch", resourceCulture);
            }
        }


        internal static string FormatCOMDispatchInvokeErrorTypeMismatch(object arg1, object arg2)
        {
            return string.Format(COMDispatchInvokeErrorTypeMismatch, arg1, arg2);
        }


        /// <summary>
        /// Could not get dispatch ID for {0} (error: {1}).
        /// </summary>
        internal static string COMGetDispatchIdFailed
        {
            get
            {
                return ResourceManager.GetString("COMGetDispatchIdFailed", resourceCulture);
            }
        }


        internal static string FormatCOMGetDispatchIdFailed(object arg1, object arg2)
        {
            return string.Format(COMGetDispatchIdFailed, arg1, arg2);
        }


        /// <summary>
        /// IDispatch::GetIDsOfNames behaved unexpectedly for {0}.
        /// </summary>
        internal static string COMGetIDsOfNamesInvalid
        {
            get
            {
                return ResourceManager.GetString("COMGetIDsOfNamesInvalid", resourceCulture);
            }
        }


        internal static string FormatCOMGetIDsOfNamesInvalid(object arg1)
        {
            return string.Format(COMGetIDsOfNamesInvalid, arg1);
        }


        /// <summary>
        /// Marshal.SetComObjectData failed.
        /// </summary>
        internal static string COMSetComObjectDataFailed
        {
            get
            {
                return ResourceManager.GetString("COMSetComObjectDataFailed", resourceCulture);
            }
        }



        /// <summary>
        /// Unexpected VarEnum {0}.
        /// </summary>
        internal static string COMUnexpectedVarEnum
        {
            get
            {
                return ResourceManager.GetString("COMUnexpectedVarEnum", resourceCulture);
            }
        }


        internal static string FormatCOMUnexpectedVarEnum(object arg1)
        {
            return string.Format(COMUnexpectedVarEnum, arg1);
        }


        /// <summary>
        /// Attempting to pass an event handler of an unsupported type.
        /// </summary>
        internal static string COMUnsupportedEventHandlerType
        {
            get
            {
                return ResourceManager.GetString("COMUnsupportedEventHandlerType", resourceCulture);
            }
        }



        /// <summary>
        /// Attempting to wrap an unsupported enum type.
        /// </summary>
        internal static string UnsupportedEnum
        {
            get
            {
                return ResourceManager.GetString("UnsupportedEnum", resourceCulture);
            }
        }

    }
}
