
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.IO.Compression", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Enum value was out of legal range.
        /// </summary>
        internal static string ArgumentOutOfRange_Enum
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_Enum", resourceCulture);
            }
        }



        /// <summary>
        /// Reading from the compression stream is not supported.
        /// </summary>
        internal static string CannotReadFromDeflateStream
        {
            get
            {
                return ResourceManager.GetString("CannotReadFromDeflateStream", resourceCulture);
            }
        }



        /// <summary>
        /// Writing to the compression stream is not supported.
        /// </summary>
        internal static string CannotWriteToDeflateStream
        {
            get
            {
                return ResourceManager.GetString("CannotWriteToDeflateStream", resourceCulture);
            }
        }



        /// <summary>
        /// Found invalid data while decoding.
        /// </summary>
        internal static string GenericInvalidData
        {
            get
            {
                return ResourceManager.GetString("GenericInvalidData", resourceCulture);
            }
        }



        /// <summary>
        /// Only one asynchronous reader or writer is allowed time at one time.
        /// </summary>
        internal static string InvalidBeginCall
        {
            get
            {
                return ResourceManager.GetString("InvalidBeginCall", resourceCulture);
            }
        }



        /// <summary>
        /// Block length does not match with its complement.
        /// </summary>
        internal static string InvalidBlockLength
        {
            get
            {
                return ResourceManager.GetString("InvalidBlockLength", resourceCulture);
            }
        }



        /// <summary>
        /// Failed to construct a huffman tree using the length array. The stream might be corrupted.
        /// </summary>
        internal static string InvalidHuffmanData
        {
            get
            {
                return ResourceManager.GetString("InvalidHuffmanData", resourceCulture);
            }
        }



        /// <summary>
        /// This operation is not supported.
        /// </summary>
        internal static string NotSupported
        {
            get
            {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// Stream does not support reading.
        /// </summary>
        internal static string NotSupported_UnreadableStream
        {
            get
            {
                return ResourceManager.GetString("NotSupported_UnreadableStream", resourceCulture);
            }
        }



        /// <summary>
        /// Stream does not support writing.
        /// </summary>
        internal static string NotSupported_UnwritableStream
        {
            get
            {
                return ResourceManager.GetString("NotSupported_UnwritableStream", resourceCulture);
            }
        }



        /// <summary>
        /// Unknown block type. Stream might be corrupted.
        /// </summary>
        internal static string UnknownBlockType
        {
            get
            {
                return ResourceManager.GetString("UnknownBlockType", resourceCulture);
            }
        }



        /// <summary>
        /// Decoder is in some unknown state. This might be caused by corrupted data.
        /// </summary>
        internal static string UnknownState
        {
            get
            {
                return ResourceManager.GetString("UnknownState", resourceCulture);
            }
        }



        /// <summary>
        /// The underlying compression routine could not be loaded correctly.
        /// </summary>
        internal static string ZLibErrorDLLLoadError
        {
            get
            {
                return ResourceManager.GetString("ZLibErrorDLLLoadError", resourceCulture);
            }
        }



        /// <summary>
        /// The stream state of the underlying compression routine is inconsistent.
        /// </summary>
        internal static string ZLibErrorInconsistentStream
        {
            get
            {
                return ResourceManager.GetString("ZLibErrorInconsistentStream", resourceCulture);
            }
        }



        /// <summary>
        /// The underlying compression routine received incorrect initialization parameters.
        /// </summary>
        internal static string ZLibErrorIncorrectInitParameters
        {
            get
            {
                return ResourceManager.GetString("ZLibErrorIncorrectInitParameters", resourceCulture);
            }
        }



        /// <summary>
        /// The underlying compression routine could not reserve sufficient memory.
        /// </summary>
        internal static string ZLibErrorNotEnoughMemory
        {
            get
            {
                return ResourceManager.GetString("ZLibErrorNotEnoughMemory", resourceCulture);
            }
        }



        /// <summary>
        /// The version of the underlying compression routine does not match expected version.
        /// </summary>
        internal static string ZLibErrorVersionMismatch
        {
            get
            {
                return ResourceManager.GetString("ZLibErrorVersionMismatch", resourceCulture);
            }
        }



        /// <summary>
        /// The underlying compression routine returned an unexpected error code: '{0}'.
        /// </summary>
        internal static string ZLibErrorUnexpected
        {
            get
            {
                return ResourceManager.GetString("ZLibErrorUnexpected", resourceCulture);
            }
        }


        internal static string FormatZLibErrorUnexpected(object arg1)
        {
            return string.Format(ZLibErrorUnexpected, arg1);
        }


        /// <summary>
        /// Central Directory corrupt.
        /// </summary>
        internal static string CDCorrupt
        {
            get
            {
                return ResourceManager.GetString("CDCorrupt", resourceCulture);
            }
        }



        /// <summary>
        /// Central Directory is invalid.
        /// </summary>
        internal static string CentralDirectoryInvalid
        {
            get
            {
                return ResourceManager.GetString("CentralDirectoryInvalid", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot create entries on an archive opened in read mode.
        /// </summary>
        internal static string CreateInReadMode
        {
            get
            {
                return ResourceManager.GetString("CreateInReadMode", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot use create mode on a non-writable stream.
        /// </summary>
        internal static string CreateModeCapabilities
        {
            get
            {
                return ResourceManager.GetString("CreateModeCapabilities", resourceCulture);
            }
        }



        /// <summary>
        /// Entries cannot be created while previously created entries are still open.
        /// </summary>
        internal static string CreateModeCreateEntryWhileOpen
        {
            get
            {
                return ResourceManager.GetString("CreateModeCreateEntryWhileOpen", resourceCulture);
            }
        }



        /// <summary>
        /// Entries in create mode may only be written to once, and only one entry may be held open at a time.
        /// </summary>
        internal static string CreateModeWriteOnceAndOneEntryAtATime
        {
            get
            {
                return ResourceManager.GetString("CreateModeWriteOnceAndOneEntryAtATime", resourceCulture);
            }
        }



        /// <summary>
        /// The DateTimeOffset specified cannot be converted into a Zip file timestamp.
        /// </summary>
        internal static string DateTimeOutOfRange
        {
            get
            {
                return ResourceManager.GetString("DateTimeOutOfRange", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot modify deleted entry.
        /// </summary>
        internal static string DeletedEntry
        {
            get
            {
                return ResourceManager.GetString("DeletedEntry", resourceCulture);
            }
        }



        /// <summary>
        /// Delete can only be used when the archive is in Update mode.
        /// </summary>
        internal static string DeleteOnlyInUpdate
        {
            get
            {
                return ResourceManager.GetString("DeleteOnlyInUpdate", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot delete an entry currently open for writing.
        /// </summary>
        internal static string DeleteOpenEntry
        {
            get
            {
                return ResourceManager.GetString("DeleteOpenEntry", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot access entries in Create mode.
        /// </summary>
        internal static string EntriesInCreateMode
        {
            get
            {
                return ResourceManager.GetString("EntriesInCreateMode", resourceCulture);
            }
        }



        /// <summary>
        /// The specified encoding is not supported for entry names and comments.
        /// </summary>
        internal static string EntryNameAndCommentEncodingNotSupported
        {
            get
            {
                return ResourceManager.GetString("EntryNameAndCommentEncodingNotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// Entry names cannot require more than 2^16 bits.
        /// </summary>
        internal static string EntryNamesTooLong
        {
            get
            {
                return ResourceManager.GetString("EntryNamesTooLong", resourceCulture);
            }
        }



        /// <summary>
        /// Entries larger than 4GB are not supported in Update mode.
        /// </summary>
        internal static string EntryTooLarge
        {
            get
            {
                return ResourceManager.GetString("EntryTooLarge", resourceCulture);
            }
        }



        /// <summary>
        /// End of Central Directory record could not be found.
        /// </summary>
        internal static string EOCDNotFound
        {
            get
            {
                return ResourceManager.GetString("EOCDNotFound", resourceCulture);
            }
        }



        /// <summary>
        /// Compressed Size cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigCompressedSize
        {
            get
            {
                return ResourceManager.GetString("FieldTooBigCompressedSize", resourceCulture);
            }
        }



        /// <summary>
        /// Local Header Offset cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigLocalHeaderOffset
        {
            get
            {
                return ResourceManager.GetString("FieldTooBigLocalHeaderOffset", resourceCulture);
            }
        }



        /// <summary>
        /// Number of Entries cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigNumEntries
        {
            get
            {
                return ResourceManager.GetString("FieldTooBigNumEntries", resourceCulture);
            }
        }



        /// <summary>
        /// Offset to Central Directory cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigOffsetToCD
        {
            get
            {
                return ResourceManager.GetString("FieldTooBigOffsetToCD", resourceCulture);
            }
        }



        /// <summary>
        /// Offset to Zip64 End Of Central Directory record cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigOffsetToZip64EOCD
        {
            get
            {
                return ResourceManager.GetString("FieldTooBigOffsetToZip64EOCD", resourceCulture);
            }
        }



        /// <summary>
        /// Uncompressed Size cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigUncompressedSize
        {
            get
            {
                return ResourceManager.GetString("FieldTooBigUncompressedSize", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot modify entry in Create mode after entry has been opened for writing.
        /// </summary>
        internal static string FrozenAfterWrite
        {
            get
            {
                return ResourceManager.GetString("FrozenAfterWrite", resourceCulture);
            }
        }



        /// <summary>
        /// A stream from ZipArchiveEntry has been disposed.
        /// </summary>
        internal static string HiddenStreamName
        {
            get
            {
                return ResourceManager.GetString("HiddenStreamName", resourceCulture);
            }
        }



        /// <summary>
        /// Length properties are unavailable once an entry has been opened for writing.
        /// </summary>
        internal static string LengthAfterWrite
        {
            get
            {
                return ResourceManager.GetString("LengthAfterWrite", resourceCulture);
            }
        }



        /// <summary>
        /// A local file header is corrupt.
        /// </summary>
        internal static string LocalFileHeaderCorrupt
        {
            get
            {
                return ResourceManager.GetString("LocalFileHeaderCorrupt", resourceCulture);
            }
        }



        /// <summary>
        /// Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.
        /// </summary>
        internal static string NumEntriesWrong
        {
            get
            {
                return ResourceManager.GetString("NumEntriesWrong", resourceCulture);
            }
        }



        /// <summary>
        /// This stream from ZipArchiveEntry does not support reading.
        /// </summary>
        internal static string ReadingNotSupported
        {
            get
            {
                return ResourceManager.GetString("ReadingNotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot use read mode on a non-readable stream.
        /// </summary>
        internal static string ReadModeCapabilities
        {
            get
            {
                return ResourceManager.GetString("ReadModeCapabilities", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot modify read-only archive.
        /// </summary>
        internal static string ReadOnlyArchive
        {
            get
            {
                return ResourceManager.GetString("ReadOnlyArchive", resourceCulture);
            }
        }



        /// <summary>
        /// This stream from ZipArchiveEntry does not support seeking.
        /// </summary>
        internal static string SeekingNotSupported
        {
            get
            {
                return ResourceManager.GetString("SeekingNotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// SetLength requires a stream that supports seeking and writing.
        /// </summary>
        internal static string SetLengthRequiresSeekingAndWriting
        {
            get
            {
                return ResourceManager.GetString("SetLengthRequiresSeekingAndWriting", resourceCulture);
            }
        }



        /// <summary>
        /// Split or spanned archives are not supported.
        /// </summary>
        internal static string SplitSpanned
        {
            get
            {
                return ResourceManager.GetString("SplitSpanned", resourceCulture);
            }
        }



        /// <summary>
        /// Found truncated data while decoding.
        /// </summary>
        internal static string TruncatedData
        {
            get
            {
                return ResourceManager.GetString("TruncatedData", resourceCulture);
            }
        }



        /// <summary>
        /// Zip file corrupt: unexpected end of stream reached.
        /// </summary>
        internal static string UnexpectedEndOfStream
        {
            get
            {
                return ResourceManager.GetString("UnexpectedEndOfStream", resourceCulture);
            }
        }



        /// <summary>
        /// The archive entry was compressed using an unsupported compression method.
        /// </summary>
        internal static string UnsupportedCompression
        {
            get
            {
                return ResourceManager.GetString("UnsupportedCompression", resourceCulture);
            }
        }



        /// <summary>
        /// The archive entry was compressed using {0} and is not supported.
        /// </summary>
        internal static string UnsupportedCompressionMethod
        {
            get
            {
                return ResourceManager.GetString("UnsupportedCompressionMethod", resourceCulture);
            }
        }


        internal static string FormatUnsupportedCompressionMethod(object arg1)
        {
            return string.Format(UnsupportedCompressionMethod, arg1);
        }


        /// <summary>
        /// Update mode requires a stream with read, write, and seek capabilities.
        /// </summary>
        internal static string UpdateModeCapabilities
        {
            get
            {
                return ResourceManager.GetString("UpdateModeCapabilities", resourceCulture);
            }
        }



        /// <summary>
        /// Entries cannot be opened multiple times in Update mode.
        /// </summary>
        internal static string UpdateModeOneStream
        {
            get
            {
                return ResourceManager.GetString("UpdateModeOneStream", resourceCulture);
            }
        }



        /// <summary>
        /// This stream from ZipArchiveEntry does not support writing.
        /// </summary>
        internal static string WritingNotSupported
        {
            get
            {
                return ResourceManager.GetString("WritingNotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// Zip 64 End of Central Directory Record not where indicated.
        /// </summary>
        internal static string Zip64EOCDNotWhereExpected
        {
            get
            {
                return ResourceManager.GetString("Zip64EOCDNotWhereExpected", resourceCulture);
            }
        }



        /// <summary>
        /// System.IO.Compression is not supported on this platform.
        /// </summary>
        internal static string PlatformNotSupported_Compression
        {
            get
            {
                return ResourceManager.GetString("PlatformNotSupported_Compression", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid offset to the Zip64 End of Central Directory record.
        /// </summary>
        internal static string InvalidOffsetToZip64EOCD
        {
            get
            {
                return ResourceManager.GetString("InvalidOffsetToZip64EOCD", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot open entry for writing when archive is opened in read-only mode.
        /// </summary>
        internal static string CannotBeWrittenInReadMode
        {
            get
            {
                return ResourceManager.GetString("CannotBeWrittenInReadMode", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot open entry for reading when archive is opened in create mode.
        /// </summary>
        internal static string CannotBeReadInCreateMode
        {
            get
            {
                return ResourceManager.GetString("CannotBeReadInCreateMode", resourceCulture);
            }
        }



        /// <summary>
        /// The specified FileAccess value is not valid.
        /// </summary>
        internal static string InvalidFileAccess
        {
            get
            {
                return ResourceManager.GetString("InvalidFileAccess", resourceCulture);
            }
        }



        /// <summary>
        /// An attempt was made to move the position before the beginning of the stream.
        /// </summary>
        internal static string IO_SeekBeforeBegin
        {
            get
            {
                return ResourceManager.GetString("IO_SeekBeforeBegin", resourceCulture);
            }
        }

    }
}
