
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Runtime.InteropServices", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Handle collector count overflows or underflows.
        /// </summary>
        internal static string InvalidOperation_HCCountOverflow
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_HCCountOverflow", resourceCulture);
            }
        }



        /// <summary>
        /// Non-negative number required.
        /// </summary>
        internal static string Arg_NeedNonNegNumRequired
        {
            get
            {
                return ResourceManager.GetString("Arg_NeedNonNegNumRequired", resourceCulture);
            }
        }



        /// <summary>
        /// maximumThreshold cannot be less than initialThreshold.
        /// </summary>
        internal static string Arg_InvalidThreshold
        {
            get
            {
                return ResourceManager.GetString("Arg_InvalidThreshold", resourceCulture);
            }
        }



        /// <summary>
        /// Event invocation for COM objects requires the declaring interface of the event to be attributed with ComEventInterfaceAttribute.
        /// </summary>
        internal static string InvalidOperation_NoComEventInterfaceAttribute
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_NoComEventInterfaceAttribute", resourceCulture);
            }
        }



        /// <summary>
        /// More than one ComEventInterfaceAttribute found for '{0}' on the declaring interface of the event.
        /// </summary>
        internal static string AmbiguousMatch_MultipleEventInterfaceAttributes
        {
            get
            {
                return ResourceManager.GetString("AmbiguousMatch_MultipleEventInterfaceAttributes", resourceCulture);
            }
        }


        internal static string FormatAmbiguousMatch_MultipleEventInterfaceAttributes(object arg1)
        {
            return string.Format(AmbiguousMatch_MultipleEventInterfaceAttributes, arg1);
        }


        /// <summary>
        /// Event invocation for COM objects requires event to be attributed with DispIdAttribute.
        /// </summary>
        internal static string InvalidOperation_NoDispIdAttribute
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_NoDispIdAttribute", resourceCulture);
            }
        }



        /// <summary>
        /// The file '{0}' already exists.
        /// </summary>
        internal static string IO_FileExists_Name
        {
            get
            {
                return ResourceManager.GetString("IO_FileExists_Name", resourceCulture);
            }
        }


        internal static string FormatIO_FileExists_Name(object arg1)
        {
            return string.Format(IO_FileExists_Name, arg1);
        }


        /// <summary>
        /// Unable to find the specified file.
        /// </summary>
        internal static string IO_FileNotFound
        {
            get
            {
                return ResourceManager.GetString("IO_FileNotFound", resourceCulture);
            }
        }



        /// <summary>
        /// Could not find file '{0}'.
        /// </summary>
        internal static string IO_FileNotFound_FileName
        {
            get
            {
                return ResourceManager.GetString("IO_FileNotFound_FileName", resourceCulture);
            }
        }


        internal static string FormatIO_FileNotFound_FileName(object arg1)
        {
            return string.Format(IO_FileNotFound_FileName, arg1);
        }


        /// <summary>
        /// Could not find a part of the path.
        /// </summary>
        internal static string IO_PathNotFound_NoPathName
        {
            get
            {
                return ResourceManager.GetString("IO_PathNotFound_NoPathName", resourceCulture);
            }
        }



        /// <summary>
        /// Could not find a part of the path '{0}'.
        /// </summary>
        internal static string IO_PathNotFound_Path
        {
            get
            {
                return ResourceManager.GetString("IO_PathNotFound_Path", resourceCulture);
            }
        }


        internal static string FormatIO_PathNotFound_Path(object arg1)
        {
            return string.Format(IO_PathNotFound_Path, arg1);
        }


        /// <summary>
        /// The specified file name or path is too long, or a component of the specified path is too long.
        /// </summary>
        internal static string IO_PathTooLong
        {
            get
            {
                return ResourceManager.GetString("IO_PathTooLong", resourceCulture);
            }
        }



        /// <summary>
        /// The process cannot access the file '{0}' because it is being used by another process.
        /// </summary>
        internal static string IO_SharingViolation_File
        {
            get
            {
                return ResourceManager.GetString("IO_SharingViolation_File", resourceCulture);
            }
        }


        internal static string FormatIO_SharingViolation_File(object arg1)
        {
            return string.Format(IO_SharingViolation_File, arg1);
        }


        /// <summary>
        /// The process cannot access the file because it is being used by another process.
        /// </summary>
        internal static string IO_SharingViolation_NoFileName
        {
            get
            {
                return ResourceManager.GetString("IO_SharingViolation_NoFileName", resourceCulture);
            }
        }



        /// <summary>
        /// The path '{0}' is too long, or a component of the specified path is too long.
        /// </summary>
        internal static string IO_PathTooLong_Path
        {
            get
            {
                return ResourceManager.GetString("IO_PathTooLong_Path", resourceCulture);
            }
        }


        internal static string FormatIO_PathTooLong_Path(object arg1)
        {
            return string.Format(IO_PathTooLong_Path, arg1);
        }


        /// <summary>
        /// Access to the path '{0}' is denied.
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_Path
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_Path", resourceCulture);
            }
        }


        internal static string FormatUnauthorizedAccess_IODenied_Path(object arg1)
        {
            return string.Format(UnauthorizedAccess_IODenied_Path, arg1);
        }


        /// <summary>
        /// Access to the path is denied.
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_NoPathName
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_NoPathName", resourceCulture);
            }
        }



        /// <summary>
        /// Specified file length was too large for the file system.
        /// </summary>
        internal static string ArgumentOutOfRange_FileLengthTooBig
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_FileLengthTooBig", resourceCulture);
            }
        }



        /// <summary>
        /// Type of managed object is not supported for marshalling as ComVariant.
        /// </summary>
        internal static string ComVariantMarshaller_ManagedTypeNotSupported
        {
            get
            {
                return ResourceManager.GetString("ComVariantMarshaller_ManagedTypeNotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// Type of unmanaged variant is not supported for marshalling to a managed object.
        /// </summary>
        internal static string ComVariantMarshaller_UnmanagedTypeNotSupported
        {
            get
            {
                return ResourceManager.GetString("ComVariantMarshaller_UnmanagedTypeNotSupported", resourceCulture);
            }
        }

    }
}
