
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Memory", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Equals() on Span and ReadOnlySpan is not supported. Use operator== instead.
        /// </summary>
        internal static string NotSupported_CannotCallEqualsOnSpan
        {
            get
            {
                return ResourceManager.GetString("NotSupported_CannotCallEqualsOnSpan", resourceCulture);
            }
        }



        /// <summary>
        /// GetHashCode() on Span and ReadOnlySpan is not supported.
        /// </summary>
        internal static string NotSupported_CannotCallGetHashCodeOnSpan
        {
            get
            {
                return ResourceManager.GetString("NotSupported_CannotCallGetHashCodeOnSpan", resourceCulture);
            }
        }



        /// <summary>
        /// The type '{0}' is not supported because it contains references.
        /// </summary>
        internal static string Argument_TypeContainsReferences
        {
            get
            {
                return ResourceManager.GetString("Argument_TypeContainsReferences", resourceCulture);
            }
        }


        internal static string FormatArgument_TypeContainsReferences(object arg1)
        {
            return string.Format(Argument_TypeContainsReferences, arg1);
        }


        /// <summary>
        /// Destination is too short.
        /// </summary>
        internal static string Argument_DestinationTooShort
        {
            get
            {
                return ResourceManager.GetString("Argument_DestinationTooShort", resourceCulture);
            }
        }



        /// <summary>
        /// Release all references before disposing this instance.
        /// </summary>
        internal static string OutstandingReferences
        {
            get
            {
                return ResourceManager.GetString("OutstandingReferences", resourceCulture);
            }
        }



        /// <summary>
        /// Format specifier was invalid.
        /// </summary>
        internal static string Argument_BadFormatSpecifier
        {
            get
            {
                return ResourceManager.GetString("Argument_BadFormatSpecifier", resourceCulture);
            }
        }



        /// <summary>
        /// Overlapping spans have mismatching alignment.
        /// </summary>
        internal static string Argument_OverlapAlignmentMismatch
        {
            get
            {
                return ResourceManager.GetString("Argument_OverlapAlignmentMismatch", resourceCulture);
            }
        }



        /// <summary>
        /// End position was not reached during enumeration.
        /// </summary>
        internal static string EndPositionNotReached
        {
            get
            {
                return ResourceManager.GetString("EndPositionNotReached", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot advance past the end of the buffer, which has a size of {0}.
        /// </summary>
        internal static string BufferWriterAdvancedTooFar
        {
            get
            {
                return ResourceManager.GetString("BufferWriterAdvancedTooFar", resourceCulture);
            }
        }


        internal static string FormatBufferWriterAdvancedTooFar(object arg1)
        {
            return string.Format(BufferWriterAdvancedTooFar, arg1);
        }


        /// <summary>
        /// Cannot allocate a buffer of size {0}.
        /// </summary>
        internal static string BufferMaximumSizeExceeded
        {
            get
            {
                return ResourceManager.GetString("BufferMaximumSizeExceeded", resourceCulture);
            }
        }


        internal static string FormatBufferMaximumSizeExceeded(object arg1)
        {
            return string.Format(BufferMaximumSizeExceeded, arg1);
        }
    }
}
