
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Security.Claims", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// The StringComparison must be one of Ordinal, OrdinalIgnoreCase, InvariantCulture, InvariantCultureIgnoreCase.
        /// </summary>
        internal static string ArgumentException_StringComparisonCultureAware
        {
            get
            {
                return ResourceManager.GetString("ArgumentException_StringComparisonCultureAware", resourceCulture);
            }
        }



        /// <summary>
        /// The Claim '{0}' was not able to be removed.  It is either not part of this Identity or it is a Claim that is owned by the Principal that contains this Identity. For example, the Principal will own the Claim when creating a GenericPrincipal with roles. The roles will be exposed through the Identity that is passed in the constructor, but not actually owned by the Identity.  Similar logic exists for a RolePrincipal.
        /// </summary>
        internal static string InvalidOperation_ClaimCannotBeRemoved
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_ClaimCannotBeRemoved", resourceCulture);
            }
        }


        internal static string FormatInvalidOperation_ClaimCannotBeRemoved(object arg1)
        {
            return string.Format(InvalidOperation_ClaimCannotBeRemoved, arg1);
        }


        /// <summary>
        /// An Actor must not create a circular reference between itself (or one of its child Actors) and one of its parents.
        /// </summary>
        internal static string InvalidOperationException_ActorGraphCircular
        {
            get
            {
                return ResourceManager.GetString("InvalidOperationException_ActorGraphCircular", resourceCulture);
            }
        }



        /// <summary>
        /// This instance contains state that cannot be serialized and deserialized on this platform.
        /// </summary>
        internal static string PlatformNotSupported_Serialization
        {
            get
            {
                return ResourceManager.GetString("PlatformNotSupported_Serialization", resourceCulture);
            }
        }

    }
}
