
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Diagnostics.TraceSource", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// '{0}' is not a valid attribute for type '{1}'.
        /// </summary>
        internal static string AttributeNotSupported
        {
            get
            {
                return ResourceManager.GetString("AttributeNotSupported", resourceCulture);
            }
        }


        internal static string FormatAttributeNotSupported(object arg1, object arg2)
        {
            return string.Format(AttributeNotSupported, arg1, arg2);
        }


        /// <summary>
        /// An exception occurred while writing to the log file {0}: {1}.
        /// </summary>
        internal static string ExceptionOccurred
        {
            get
            {
                return ResourceManager.GetString("ExceptionOccurred", resourceCulture);
            }
        }


        internal static string FormatExceptionOccurred(object arg1, object arg2)
        {
            return string.Format(ExceptionOccurred, arg1, arg2);
        }


        /// <summary>
        /// Only TraceListeners can be added to a TraceListenerCollection.
        /// </summary>
        internal static string MustAddListener
        {
            get
            {
                return ResourceManager.GetString("MustAddListener", resourceCulture);
            }
        }



        /// <summary>
        /// Fail:
        /// </summary>
        internal static string TraceListenerFail
        {
            get
            {
                return ResourceManager.GetString("TraceListenerFail", resourceCulture);
            }
        }



        /// <summary>
        /// The IndentSize property must be non-negative.
        /// </summary>
        internal static string TraceListenerIndentSize
        {
            get
            {
                return ResourceManager.GetString("TraceListenerIndentSize", resourceCulture);
            }
        }



        /// <summary>
        /// ---- DEBUG ASSERTION FAILED ----
        /// </summary>
        internal static string DebugAssertBanner
        {
            get
            {
                return ResourceManager.GetString("DebugAssertBanner", resourceCulture);
            }
        }



        /// <summary>
        /// ---- Assert Short Message ----
        /// </summary>
        internal static string DebugAssertShortMessage
        {
            get
            {
                return ResourceManager.GetString("DebugAssertShortMessage", resourceCulture);
            }
        }



        /// <summary>
        /// ---- Assert Long Message ----
        /// </summary>
        internal static string DebugAssertLongMessage
        {
            get
            {
                return ResourceManager.GetString("DebugAssertLongMessage", resourceCulture);
            }
        }



        /// <summary>
        /// Attempted to set {0} to a value that is too low.  Setting level to TraceLevel.Off
        /// </summary>
        internal static string TraceSwitchLevelTooLow
        {
            get
            {
                return ResourceManager.GetString("TraceSwitchLevelTooLow", resourceCulture);
            }
        }


        internal static string FormatTraceSwitchLevelTooLow(object arg1)
        {
            return string.Format(TraceSwitchLevelTooLow, arg1);
        }


        /// <summary>
        /// The Level must be set to a value in the enumeration TraceLevel.
        /// </summary>
        internal static string TraceSwitchInvalidLevel
        {
            get
            {
                return ResourceManager.GetString("TraceSwitchInvalidLevel", resourceCulture);
            }
        }



        /// <summary>
        /// Attempted to set {0} to a value that is too high.  Setting level to TraceLevel.Verbose
        /// </summary>
        internal static string TraceSwitchLevelTooHigh
        {
            get
            {
                return ResourceManager.GetString("TraceSwitchLevelTooHigh", resourceCulture);
            }
        }


        internal static string FormatTraceSwitchLevelTooHigh(object arg1)
        {
            return string.Format(TraceSwitchLevelTooHigh, arg1);
        }
    }
}
