
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Runtime.Serialization.Formatters", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.
        /// </summary>
        internal static string Arg_HTCapacityOverflow
        {
            get
            {
                return ResourceManager.GetString("Arg_HTCapacityOverflow", resourceCulture);
            }
        }



        /// <summary>
        /// Type '{0}' in Assembly '{1}' is not marked as serializable.
        /// </summary>
        internal static string Serialization_NonSerType
        {
            get
            {
                return ResourceManager.GetString("Serialization_NonSerType", resourceCulture);
            }
        }


        internal static string FormatSerialization_NonSerType(object arg1, object arg2)
        {
            return string.Format(Serialization_NonSerType, arg1, arg2);
        }


        /// <summary>
        /// Parameters 'members' and 'data' must have the same length.
        /// </summary>
        internal static string Argument_DataLengthDifferent
        {
            get
            {
                return ResourceManager.GetString("Argument_DataLengthDifferent", resourceCulture);
            }
        }



        /// <summary>
        /// Member at position {0} was null.
        /// </summary>
        internal static string ArgumentNull_NullMember
        {
            get
            {
                return ResourceManager.GetString("ArgumentNull_NullMember", resourceCulture);
            }
        }


        internal static string FormatArgumentNull_NullMember(object arg1)
        {
            return string.Format(ArgumentNull_NullMember, arg1);
        }


        /// <summary>
        /// Only FieldInfo, PropertyInfo, and SerializationMemberInfo are recognized.
        /// </summary>
        internal static string Serialization_UnknownMemberInfo
        {
            get
            {
                return ResourceManager.GetString("Serialization_UnknownMemberInfo", resourceCulture);
            }
        }



        /// <summary>
        /// Object has never been assigned an objectID.
        /// </summary>
        internal static string Serialization_NoID
        {
            get
            {
                return ResourceManager.GetString("Serialization_NoID", resourceCulture);
            }
        }



        /// <summary>
        /// The internal array cannot expand to greater than Int32.MaxValue elements.
        /// </summary>
        internal static string Serialization_TooManyElements
        {
            get
            {
                return ResourceManager.GetString("Serialization_TooManyElements", resourceCulture);
            }
        }



        /// <summary>
        /// The FieldInfo object is not valid.
        /// </summary>
        internal static string Argument_InvalidFieldInfo
        {
            get
            {
                return ResourceManager.GetString("Argument_InvalidFieldInfo", resourceCulture);
            }
        }



        /// <summary>
        /// A fixup is registered to the object with ID {0}, but the object does not appear in the graph.
        /// </summary>
        internal static string Serialization_NeverSeen
        {
            get
            {
                return ResourceManager.GetString("Serialization_NeverSeen", resourceCulture);
            }
        }


        internal static string FormatSerialization_NeverSeen(object arg1)
        {
            return string.Format(Serialization_NeverSeen, arg1);
        }


        /// <summary>
        /// The object with ID {0} implements the IObjectReference interface for which all dependencies cannot be resolved. The likely cause is two instances of IObjectReference that have a mutual dependency on each other.
        /// </summary>
        internal static string Serialization_IORIncomplete
        {
            get
            {
                return ResourceManager.GetString("Serialization_IORIncomplete", resourceCulture);
            }
        }


        internal static string FormatSerialization_IORIncomplete(object arg1)
        {
            return string.Format(Serialization_IORIncomplete, arg1);
        }


        /// <summary>
        /// The object with ID {0} was referenced in a fixup but does not exist.
        /// </summary>
        internal static string Serialization_ObjectNotSupplied
        {
            get
            {
                return ResourceManager.GetString("Serialization_ObjectNotSupplied", resourceCulture);
            }
        }


        internal static string FormatSerialization_ObjectNotSupplied(object arg1)
        {
            return string.Format(Serialization_ObjectNotSupplied, arg1);
        }


        /// <summary>
        /// {0}.SetObjectData returns a value that is neither null nor equal to the first parameter. Such Surrogates cannot be part of cyclical reference.
        /// </summary>
        internal static string Serialization_NotCyclicallyReferenceableSurrogate
        {
            get
            {
                return ResourceManager.GetString("Serialization_NotCyclicallyReferenceableSurrogate", resourceCulture);
            }
        }


        internal static string FormatSerialization_NotCyclicallyReferenceableSurrogate(object arg1)
        {
            return string.Format(Serialization_NotCyclicallyReferenceableSurrogate, arg1);
        }


        /// <summary>
        /// The implementation of the IObjectReference interface returns too many nested references to other objects that implement IObjectReference.
        /// </summary>
        internal static string Serialization_TooManyReferences
        {
            get
            {
                return ResourceManager.GetString("Serialization_TooManyReferences", resourceCulture);
            }
        }



        /// <summary>
        /// The object with ID {0} was referenced in a fixup but has not been registered.
        /// </summary>
        internal static string Serialization_MissingObject
        {
            get
            {
                return ResourceManager.GetString("Serialization_MissingObject", resourceCulture);
            }
        }


        internal static string FormatSerialization_MissingObject(object arg1)
        {
            return string.Format(Serialization_MissingObject, arg1);
        }


        /// <summary>
        /// A fixup on an object implementing ISerializable or having a surrogate was discovered for an object which does not have a SerializationInfo available.
        /// </summary>
        internal static string Serialization_InvalidFixupDiscovered
        {
            get
            {
                return ResourceManager.GetString("Serialization_InvalidFixupDiscovered", resourceCulture);
            }
        }



        /// <summary>
        /// Unable to load type {0} required for deserialization.
        /// </summary>
        internal static string Serialization_TypeLoadFailure
        {
            get
            {
                return ResourceManager.GetString("Serialization_TypeLoadFailure", resourceCulture);
            }
        }


        internal static string FormatSerialization_TypeLoadFailure(object arg1)
        {
            return string.Format(Serialization_TypeLoadFailure, arg1);
        }


        /// <summary>
        /// ValueType fixup on Arrays is not implemented.
        /// </summary>
        internal static string Serialization_ValueTypeFixup
        {
            get
            {
                return ResourceManager.GetString("Serialization_ValueTypeFixup", resourceCulture);
            }
        }



        /// <summary>
        /// Fixing up a partially available ValueType chain is not implemented.
        /// </summary>
        internal static string Serialization_PartialValueTypeFixup
        {
            get
            {
                return ResourceManager.GetString("Serialization_PartialValueTypeFixup", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot perform fixup.
        /// </summary>
        internal static string Serialization_UnableToFixup
        {
            get
            {
                return ResourceManager.GetString("Serialization_UnableToFixup", resourceCulture);
            }
        }



        /// <summary>
        /// objectID cannot be less than or equal to zero.
        /// </summary>
        internal static string ArgumentOutOfRange_ObjectID
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_ObjectID", resourceCulture);
            }
        }



        /// <summary>
        /// An object cannot be registered twice.
        /// </summary>
        internal static string Serialization_RegisterTwice
        {
            get
            {
                return ResourceManager.GetString("Serialization_RegisterTwice", resourceCulture);
            }
        }



        /// <summary>
        /// The given object does not implement the ISerializable interface.
        /// </summary>
        internal static string Serialization_NotISer
        {
            get
            {
                return ResourceManager.GetString("Serialization_NotISer", resourceCulture);
            }
        }



        /// <summary>
        /// The constructor to deserialize an object of type '{0}' was not found.
        /// </summary>
        internal static string Serialization_ConstructorNotFound
        {
            get
            {
                return ResourceManager.GetString("Serialization_ConstructorNotFound", resourceCulture);
            }
        }


        internal static string FormatSerialization_ConstructorNotFound(object arg1)
        {
            return string.Format(Serialization_ConstructorNotFound, arg1);
        }


        /// <summary>
        /// The ObjectManager found an invalid number of fixups. This usually indicates a problem in the Formatter.
        /// </summary>
        internal static string Serialization_IncorrectNumberOfFixups
        {
            get
            {
                return ResourceManager.GetString("Serialization_IncorrectNumberOfFixups", resourceCulture);
            }
        }



        /// <summary>
        /// A member fixup was registered for an object which implements ISerializable or has a surrogate. In this situation, a delayed fixup must be used.
        /// </summary>
        internal static string Serialization_InvalidFixupType
        {
            get
            {
                return ResourceManager.GetString("Serialization_InvalidFixupType", resourceCulture);
            }
        }



        /// <summary>
        /// Object IDs must be greater than zero.
        /// </summary>
        internal static string Serialization_IdTooSmall
        {
            get
            {
                return ResourceManager.GetString("Serialization_IdTooSmall", resourceCulture);
            }
        }



        /// <summary>
        /// The ID of the containing object cannot be the same as the object ID.
        /// </summary>
        internal static string Serialization_ParentChildIdentical
        {
            get
            {
                return ResourceManager.GetString("Serialization_ParentChildIdentical", resourceCulture);
            }
        }



        /// <summary>
        /// Only system-provided types can be passed to the GetUninitializedObject method. '{0}' is not a valid instance of a type.
        /// </summary>
        internal static string Serialization_InvalidType
        {
            get
            {
                return ResourceManager.GetString("Serialization_InvalidType", resourceCulture);
            }
        }


        internal static string FormatSerialization_InvalidType(object arg1)
        {
            return string.Format(Serialization_InvalidType, arg1);
        }


        /// <summary>
        /// When supplying the ID of a containing object, the FieldInfo that identifies the current field within that object must also be supplied.
        /// </summary>
        internal static string Argument_MustSupplyParent
        {
            get
            {
                return ResourceManager.GetString("Argument_MustSupplyParent", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot supply both a MemberInfo and an Array to indicate the parent of a value type.
        /// </summary>
        internal static string Argument_MemberAndArray
        {
            get
            {
                return ResourceManager.GetString("Argument_MemberAndArray", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid BinaryFormatter stream.
        /// </summary>
        internal static string Serialization_CorruptedStream
        {
            get
            {
                return ResourceManager.GetString("Serialization_CorruptedStream", resourceCulture);
            }
        }



        /// <summary>
        /// Attempting to deserialize an empty stream.
        /// </summary>
        internal static string Serialization_Stream
        {
            get
            {
                return ResourceManager.GetString("Serialization_Stream", resourceCulture);
            }
        }



        /// <summary>
        /// Binary stream '{0}' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
        /// </summary>
        internal static string Serialization_BinaryHeader
        {
            get
            {
                return ResourceManager.GetString("Serialization_BinaryHeader", resourceCulture);
            }
        }


        internal static string FormatSerialization_BinaryHeader(object arg1)
        {
            return string.Format(Serialization_BinaryHeader, arg1);
        }


        /// <summary>
        /// Invalid expected type.
        /// </summary>
        internal static string Serialization_TypeExpected
        {
            get
            {
                return ResourceManager.GetString("Serialization_TypeExpected", resourceCulture);
            }
        }



        /// <summary>
        /// End of Stream encountered before parsing was completed.
        /// </summary>
        internal static string Serialization_StreamEnd
        {
            get
            {
                return ResourceManager.GetString("Serialization_StreamEnd", resourceCulture);
            }
        }



        /// <summary>
        /// Cross-AppDomain BinaryFormatter error; expected '{0}' but received '{1}'.
        /// </summary>
        internal static string Serialization_CrossAppDomainError
        {
            get
            {
                return ResourceManager.GetString("Serialization_CrossAppDomainError", resourceCulture);
            }
        }


        internal static string FormatSerialization_CrossAppDomainError(object arg1, object arg2)
        {
            return string.Format(Serialization_CrossAppDomainError, arg1, arg2);
        }


        /// <summary>
        /// No map for object '{0}'.
        /// </summary>
        internal static string Serialization_Map
        {
            get
            {
                return ResourceManager.GetString("Serialization_Map", resourceCulture);
            }
        }


        internal static string FormatSerialization_Map(object arg1)
        {
            return string.Format(Serialization_Map, arg1);
        }


        /// <summary>
        /// No assembly information is available for object on the wire, '{0}'.
        /// </summary>
        internal static string Serialization_Assembly
        {
            get
            {
                return ResourceManager.GetString("Serialization_Assembly", resourceCulture);
            }
        }


        internal static string FormatSerialization_Assembly(object arg1)
        {
            return string.Format(Serialization_Assembly, arg1);
        }


        /// <summary>
        /// Invalid ObjectTypeEnum {0}.
        /// </summary>
        internal static string Serialization_ObjectTypeEnum
        {
            get
            {
                return ResourceManager.GetString("Serialization_ObjectTypeEnum", resourceCulture);
            }
        }


        internal static string FormatSerialization_ObjectTypeEnum(object arg1)
        {
            return string.Format(Serialization_ObjectTypeEnum, arg1);
        }


        /// <summary>
        /// No assembly ID for object type '{0}'.
        /// </summary>
        internal static string Serialization_AssemblyId
        {
            get
            {
                return ResourceManager.GetString("Serialization_AssemblyId", resourceCulture);
            }
        }


        internal static string FormatSerialization_AssemblyId(object arg1)
        {
            return string.Format(Serialization_AssemblyId, arg1);
        }


        /// <summary>
        /// Invalid array type '{0}'.
        /// </summary>
        internal static string Serialization_ArrayType
        {
            get
            {
                return ResourceManager.GetString("Serialization_ArrayType", resourceCulture);
            }
        }


        internal static string FormatSerialization_ArrayType(object arg1)
        {
            return string.Format(Serialization_ArrayType, arg1);
        }


        /// <summary>
        /// Invalid type code in stream '{0}'.
        /// </summary>
        internal static string Serialization_TypeCode
        {
            get
            {
                return ResourceManager.GetString("Serialization_TypeCode", resourceCulture);
            }
        }


        internal static string FormatSerialization_TypeCode(object arg1)
        {
            return string.Format(Serialization_TypeCode, arg1);
        }


        /// <summary>
        /// Invalid write type request '{0}'.
        /// </summary>
        internal static string Serialization_TypeWrite
        {
            get
            {
                return ResourceManager.GetString("Serialization_TypeWrite", resourceCulture);
            }
        }


        internal static string FormatSerialization_TypeWrite(object arg1)
        {
            return string.Format(Serialization_TypeWrite, arg1);
        }


        /// <summary>
        /// Invalid read type request '{0}'.
        /// </summary>
        internal static string Serialization_TypeRead
        {
            get
            {
                return ResourceManager.GetString("Serialization_TypeRead", resourceCulture);
            }
        }


        internal static string FormatSerialization_TypeRead(object arg1)
        {
            return string.Format(Serialization_TypeRead, arg1);
        }


        /// <summary>
        /// Unable to find assembly '{0}'.
        /// </summary>
        internal static string Serialization_AssemblyNotFound
        {
            get
            {
                return ResourceManager.GetString("Serialization_AssemblyNotFound", resourceCulture);
            }
        }


        internal static string FormatSerialization_AssemblyNotFound(object arg1)
        {
            return string.Format(Serialization_AssemblyNotFound, arg1);
        }


        /// <summary>
        /// The input stream is not a valid binary format. The starting contents (in bytes) are: {0} ...
        /// </summary>
        internal static string Serialization_InvalidFormat
        {
            get
            {
                return ResourceManager.GetString("Serialization_InvalidFormat", resourceCulture);
            }
        }


        internal static string FormatSerialization_InvalidFormat(object arg1)
        {
            return string.Format(Serialization_InvalidFormat, arg1);
        }


        /// <summary>
        /// No top object.
        /// </summary>
        internal static string Serialization_TopObject
        {
            get
            {
                return ResourceManager.GetString("Serialization_TopObject", resourceCulture);
            }
        }



        /// <summary>
        /// Invalid element '{0}'.
        /// </summary>
        internal static string Serialization_XMLElement
        {
            get
            {
                return ResourceManager.GetString("Serialization_XMLElement", resourceCulture);
            }
        }


        internal static string FormatSerialization_XMLElement(object arg1)
        {
            return string.Format(Serialization_XMLElement, arg1);
        }


        /// <summary>
        /// Top object cannot be instantiated for element '{0}'.
        /// </summary>
        internal static string Serialization_TopObjectInstantiate
        {
            get
            {
                return ResourceManager.GetString("Serialization_TopObjectInstantiate", resourceCulture);
            }
        }


        internal static string FormatSerialization_TopObjectInstantiate(object arg1)
        {
            return string.Format(Serialization_TopObjectInstantiate, arg1);
        }


        /// <summary>
        /// Array element type is Object, 'dt' attribute is null.
        /// </summary>
        internal static string Serialization_ArrayTypeObject
        {
            get
            {
                return ResourceManager.GetString("Serialization_ArrayTypeObject", resourceCulture);
            }
        }



        /// <summary>
        /// Type is missing for member of type Object '{0}'.
        /// </summary>
        internal static string Serialization_TypeMissing
        {
            get
            {
                return ResourceManager.GetString("Serialization_TypeMissing", resourceCulture);
            }
        }


        internal static string FormatSerialization_TypeMissing(object arg1)
        {
            return string.Format(Serialization_TypeMissing, arg1);
        }


        /// <summary>
        /// Object {0} has never been assigned an objectID.
        /// </summary>
        internal static string Serialization_ObjNoID
        {
            get
            {
                return ResourceManager.GetString("Serialization_ObjNoID", resourceCulture);
            }
        }


        internal static string FormatSerialization_ObjNoID(object arg1)
        {
            return string.Format(Serialization_ObjNoID, arg1);
        }


        /// <summary>
        /// MemberInfo type {0} cannot be serialized.
        /// </summary>
        internal static string Serialization_SerMemberInfo
        {
            get
            {
                return ResourceManager.GetString("Serialization_SerMemberInfo", resourceCulture);
            }
        }


        internal static string FormatSerialization_SerMemberInfo(object arg1)
        {
            return string.Format(Serialization_SerMemberInfo, arg1);
        }


        /// <summary>
        /// When supplying a FieldInfo for fixing up a nested type, a valid ID for that containing object must also be supplied.
        /// </summary>
        internal static string Argument_MustSupplyContainer
        {
            get
            {
                return ResourceManager.GetString("Argument_MustSupplyContainer", resourceCulture);
            }
        }



        /// <summary>
        /// Parse error. Current element is not compatible with the next element, {0}.
        /// </summary>
        internal static string Serialization_ParseError
        {
            get
            {
                return ResourceManager.GetString("Serialization_ParseError", resourceCulture);
            }
        }


        internal static string FormatSerialization_ParseError(object arg1)
        {
            return string.Format(Serialization_ParseError, arg1);
        }


        /// <summary>
        /// MemberInfo requested for ISerializable type.
        /// </summary>
        internal static string Serialization_ISerializableMemberInfo
        {
            get
            {
                return ResourceManager.GetString("Serialization_ISerializableMemberInfo", resourceCulture);
            }
        }



        /// <summary>
        /// MemberInfo cannot be obtained for ISerialized Object '{0}'.
        /// </summary>
        internal static string Serialization_MemberInfo
        {
            get
            {
                return ResourceManager.GetString("Serialization_MemberInfo", resourceCulture);
            }
        }


        internal static string FormatSerialization_MemberInfo(object arg1)
        {
            return string.Format(Serialization_MemberInfo, arg1);
        }


        /// <summary>
        /// Types not available for ISerializable object '{0}'.
        /// </summary>
        internal static string Serialization_ISerializableTypes
        {
            get
            {
                return ResourceManager.GetString("Serialization_ISerializableTypes", resourceCulture);
            }
        }


        internal static string FormatSerialization_ISerializableTypes(object arg1)
        {
            return string.Format(Serialization_ISerializableTypes, arg1);
        }


        /// <summary>
        /// Member '{0}' in class '{1}' is not present in the serialized stream and is not marked with {2}.
        /// </summary>
        internal static string Serialization_MissingMember
        {
            get
            {
                return ResourceManager.GetString("Serialization_MissingMember", resourceCulture);
            }
        }


        internal static string FormatSerialization_MissingMember(object arg1, object arg2, object arg3)
        {
            return string.Format(Serialization_MissingMember, arg1, arg2, arg3);
        }


        /// <summary>
        /// No MemberInfo for Object {0}.
        /// </summary>
        internal static string Serialization_NoMemberInfo
        {
            get
            {
                return ResourceManager.GetString("Serialization_NoMemberInfo", resourceCulture);
            }
        }


        internal static string FormatSerialization_NoMemberInfo(object arg1)
        {
            return string.Format(Serialization_NoMemberInfo, arg1);
        }


        /// <summary>
        /// Selector contained a cycle.
        /// </summary>
        internal static string Serialization_SurrogateCycleInArgument
        {
            get
            {
                return ResourceManager.GetString("Serialization_SurrogateCycleInArgument", resourceCulture);
            }
        }



        /// <summary>
        /// Adding selector will introduce a cycle.
        /// </summary>
        internal static string Serialization_SurrogateCycle
        {
            get
            {
                return ResourceManager.GetString("Serialization_SurrogateCycle", resourceCulture);
            }
        }



        /// <summary>
        /// Unable to read beyond the end of the stream.
        /// </summary>
        internal static string IO_EOF_ReadBeyondEOF
        {
            get
            {
                return ResourceManager.GetString("IO_EOF_ReadBeyondEOF", resourceCulture);
            }
        }



        /// <summary>
        /// BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
        /// </summary>
        internal static string BinaryFormatter_SerializationDisallowed
        {
            get
            {
                return ResourceManager.GetString("BinaryFormatter_SerializationDisallowed", resourceCulture);
            }
        }



        /// <summary>
        /// BinaryFormatter serialization and deserialization are not supported on this platform. See https://aka.ms/binaryformatter for more information.
        /// </summary>
        internal static string BinaryFormatter_SerializationNotSupportedOnThisPlatform
        {
            get
            {
                return ResourceManager.GetString("BinaryFormatter_SerializationNotSupportedOnThisPlatform", resourceCulture);
            }
        }



        /// <summary>
        /// BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
        /// </summary>
        internal static string BinaryFormatter_Removed
        {
            get
            {
                return ResourceManager.GetString("BinaryFormatter_Removed", resourceCulture);
            }
        }

    }
}
