using dotnetJs;

namespace System
{
    /// <summary>
    /// This represent the type generated by the transpiler
    /// </summary>
    [External]
    public class TypePrototype
    {
        [Name("$type")]
        public Type? Type { get; set; }
        public string FullName { get; set; } = default!;
        [Name(Constants.IsTypeName)]
        public extern bool Is(object value);
        [Name(Constants.StaticInitializerName)]
        public extern bool StaticInitializeMembers();
        [Name(Constants.StaticConstructorName)]
        public extern bool StaticConstructor();
        [Name(Constants.DefaultConstructorName)]
        public extern object CallDefaultConstructor();
        [Name("constructor")]
        public extern object NativeConstructor();
    }

    [External]
    public class EnumPrototype : TypePrototype
    {
        [Name(Constants.EnumMapName)]
        public extern SimpleDictionary<object> Map { get; }
        [Name(Constants.EnumMapName)]
        public extern TypePrototype UnderlyingType { get; }
    }

    public delegate TypePrototype TypePrototypeProvider(TypePrototype[]? genericArgs, TypePrototype? baseType);
    public delegate TypePrototype ParameterlessTypePrototypeProvider();
}