
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.IO.MemoryMappedFiles", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Unable to find the specified file.
        /// </summary>
        internal static string IO_FileNotFound
        {
            get
            {
                return ResourceManager.GetString("IO_FileNotFound", resourceCulture);
            }
        }



        /// <summary>
        /// Could not find file '{0}'.
        /// </summary>
        internal static string IO_FileNotFound_FileName
        {
            get
            {
                return ResourceManager.GetString("IO_FileNotFound_FileName", resourceCulture);
            }
        }


        internal static string FormatIO_FileNotFound_FileName(object arg1)
        {
            return string.Format(IO_FileNotFound_FileName, arg1);
        }


        /// <summary>
        /// Cannot create '{0}' because a file or directory with the same name already exists.
        /// </summary>
        internal static string IO_AlreadyExists_Name
        {
            get
            {
                return ResourceManager.GetString("IO_AlreadyExists_Name", resourceCulture);
            }
        }


        internal static string FormatIO_AlreadyExists_Name(object arg1)
        {
            return string.Format(IO_AlreadyExists_Name, arg1);
        }


        /// <summary>
        /// The file '{0}' already exists.
        /// </summary>
        internal static string IO_FileExists_Name
        {
            get
            {
                return ResourceManager.GetString("IO_FileExists_Name", resourceCulture);
            }
        }


        internal static string FormatIO_FileExists_Name(object arg1)
        {
            return string.Format(IO_FileExists_Name, arg1);
        }


        /// <summary>
        /// The process cannot access the file '{0}' because it is being used by another process.
        /// </summary>
        internal static string IO_SharingViolation_File
        {
            get
            {
                return ResourceManager.GetString("IO_SharingViolation_File", resourceCulture);
            }
        }


        internal static string FormatIO_SharingViolation_File(object arg1)
        {
            return string.Format(IO_SharingViolation_File, arg1);
        }


        /// <summary>
        /// The process cannot access the file because it is being used by another process.
        /// </summary>
        internal static string IO_SharingViolation_NoFileName
        {
            get
            {
                return ResourceManager.GetString("IO_SharingViolation_NoFileName", resourceCulture);
            }
        }



        /// <summary>
        /// Could not find a part of the path '{0}'.
        /// </summary>
        internal static string IO_PathNotFound_Path
        {
            get
            {
                return ResourceManager.GetString("IO_PathNotFound_Path", resourceCulture);
            }
        }


        internal static string FormatIO_PathNotFound_Path(object arg1)
        {
            return string.Format(IO_PathNotFound_Path, arg1);
        }


        /// <summary>
        /// Could not find a part of the path.
        /// </summary>
        internal static string IO_PathNotFound_NoPathName
        {
            get
            {
                return ResourceManager.GetString("IO_PathNotFound_NoPathName", resourceCulture);
            }
        }



        /// <summary>
        /// The specified file name or path is too long, or a component of the specified path is too long.
        /// </summary>
        internal static string IO_PathTooLong
        {
            get
            {
                return ResourceManager.GetString("IO_PathTooLong", resourceCulture);
            }
        }



        /// <summary>
        /// Access to the path '{0}' is denied.
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_Path
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_Path", resourceCulture);
            }
        }


        internal static string FormatUnauthorizedAccess_IODenied_Path(object arg1)
        {
            return string.Format(UnauthorizedAccess_IODenied_Path, arg1);
        }


        /// <summary>
        /// Access to the path is denied.
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_NoPathName
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_NoPathName", resourceCulture);
            }
        }



        /// <summary>
        /// Map name cannot be an empty string.
        /// </summary>
        internal static string Argument_MapNameEmptyString
        {
            get
            {
                return ResourceManager.GetString("Argument_MapNameEmptyString", resourceCulture);
            }
        }



        /// <summary>
        /// A positive capacity must be specified for a Memory Mapped File backed by an empty file.
        /// </summary>
        internal static string Argument_EmptyFile
        {
            get
            {
                return ResourceManager.GetString("Argument_EmptyFile", resourceCulture);
            }
        }



        /// <summary>
        /// MemoryMappedFileAccess.Write is not permitted when creating new memory mapped files. Use MemoryMappedFileAccess.ReadWrite instead.
        /// </summary>
        internal static string Argument_NewMMFWriteAccessNotAllowed
        {
            get
            {
                return ResourceManager.GetString("Argument_NewMMFWriteAccessNotAllowed", resourceCulture);
            }
        }



        /// <summary>
        /// When specifying MemoryMappedFileAccess.Read access, the capacity must not be larger than the file size.
        /// </summary>
        internal static string Argument_ReadAccessWithLargeCapacity
        {
            get
            {
                return ResourceManager.GetString("Argument_ReadAccessWithLargeCapacity", resourceCulture);
            }
        }



        /// <summary>
        /// FileMode.Append is not permitted when creating new memory mapped files. Instead, use MemoryMappedFileView to ensure write-only access within a specified region.
        /// </summary>
        internal static string Argument_NewMMFAppendModeNotAllowed
        {
            get
            {
                return ResourceManager.GetString("Argument_NewMMFAppendModeNotAllowed", resourceCulture);
            }
        }



        /// <summary>
        /// FileMode.Truncate is not permitted when creating new memory mapped files.
        /// </summary>
        internal static string Argument_NewMMFTruncateModeNotAllowed
        {
            get
            {
                return ResourceManager.GetString("Argument_NewMMFTruncateModeNotAllowed", resourceCulture);
            }
        }



        /// <summary>
        /// The capacity cannot be greater than the size of the system's logical address space.
        /// </summary>
        internal static string ArgumentOutOfRange_CapacityLargerThanLogicalAddressSpaceNotAllowed
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_CapacityLargerThanLogicalAddressSpaceNotAllowed", resourceCulture);
            }
        }



        /// <summary>
        /// Specified file length was too large for the file system.
        /// </summary>
        internal static string ArgumentOutOfRange_FileLengthTooBig
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_FileLengthTooBig", resourceCulture);
            }
        }



        /// <summary>
        /// The capacity must be greater than or equal to 0. 0 represents the size of the file being mapped.
        /// </summary>
        internal static string ArgumentOutOfRange_PositiveOrDefaultCapacityRequired
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_PositiveOrDefaultCapacityRequired", resourceCulture);
            }
        }



        /// <summary>
        /// The size must be greater than or equal to 0. If 0 is specified, the view extends from the specified offset to the end of the file mapping.
        /// </summary>
        internal static string ArgumentOutOfRange_PositiveOrDefaultSizeRequired
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_PositiveOrDefaultSizeRequired", resourceCulture);
            }
        }



        /// <summary>
        /// The capacity may not be smaller than the file size.
        /// </summary>
        internal static string ArgumentOutOfRange_CapacityGEFileSizeRequired
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_CapacityGEFileSizeRequired", resourceCulture);
            }
        }



        /// <summary>
        /// Not enough memory to map view.
        /// </summary>
        internal static string IO_NotEnoughMemory
        {
            get
            {
                return ResourceManager.GetString("IO_NotEnoughMemory", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot create file mapping.
        /// </summary>
        internal static string InvalidOperation_CantCreateFileMapping
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_CantCreateFileMapping", resourceCulture);
            }
        }



        /// <summary>
        /// MemoryMappedViewStreams are fixed length.
        /// </summary>
        internal static string NotSupported_MMViewStreamsFixedLength
        {
            get
            {
                return ResourceManager.GetString("NotSupported_MMViewStreamsFixedLength", resourceCulture);
            }
        }



        /// <summary>
        /// Stream does not support reading.
        /// </summary>
        internal static string NotSupported_UnreadableStream
        {
            get
            {
                return ResourceManager.GetString("NotSupported_UnreadableStream", resourceCulture);
            }
        }



        /// <summary>
        /// Stream does not support writing.
        /// </summary>
        internal static string NotSupported_UnwritableStream
        {
            get
            {
                return ResourceManager.GetString("NotSupported_UnwritableStream", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot access a closed accessor.
        /// </summary>
        internal static string ObjectDisposed_ViewAccessorClosed
        {
            get
            {
                return ResourceManager.GetString("ObjectDisposed_ViewAccessorClosed", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot access a closed Stream.
        /// </summary>
        internal static string ObjectDisposed_StreamIsClosed
        {
            get
            {
                return ResourceManager.GetString("ObjectDisposed_StreamIsClosed", resourceCulture);
            }
        }



        /// <summary>
        /// Named maps are not supported.
        /// </summary>
        internal static string PlatformNotSupported_NamedMaps
        {
            get
            {
                return ResourceManager.GetString("PlatformNotSupported_NamedMaps", resourceCulture);
            }
        }



        /// <summary>
        /// The path '{0}' is too long, or a component of the specified path is too long.
        /// </summary>
        internal static string IO_PathTooLong_Path
        {
            get
            {
                return ResourceManager.GetString("IO_PathTooLong_Path", resourceCulture);
            }
        }


        internal static string FormatIO_PathTooLong_Path(object arg1)
        {
            return string.Format(IO_PathTooLong_Path, arg1);
        }


        /// <summary>
        /// System.IO.MemoryMappedFiles is not supported on this platform.
        /// </summary>
        internal static string PlatformNotSupported_MemoryMappedFiles
        {
            get
            {
                return ResourceManager.GetString("PlatformNotSupported_MemoryMappedFiles", resourceCulture);
            }
        }

    }
}
