
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Collections.Immutable", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// The given key '{0}' was not present in the dictionary.
        /// </summary>
        internal static string Arg_KeyNotFoundWithKey
        {
            get
            {
                return ResourceManager.GetString("Arg_KeyNotFoundWithKey", resourceCulture);
            }
        }


        internal static string FormatArg_KeyNotFoundWithKey(object arg1)
        {
            return string.Format(Arg_KeyNotFoundWithKey, arg1);
        }


        /// <summary>
        /// Object is not an array with the same initialization state as the array to compare it to.
        /// </summary>
        internal static string ArrayInitializedStateNotEqual
        {
            get
            {
                return ResourceManager.GetString("ArrayInitializedStateNotEqual", resourceCulture);
            }
        }



        /// <summary>
        /// Object is not an array with the same number of elements as the array to compare it to.
        /// </summary>
        internal static string ArrayLengthsNotEqual
        {
            get
            {
                return ResourceManager.GetString("ArrayLengthsNotEqual", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot find the old value
        /// </summary>
        internal static string CannotFindOldValue
        {
            get
            {
                return ResourceManager.GetString("CannotFindOldValue", resourceCulture);
            }
        }



        /// <summary>
        /// Capacity was less than the current Count of elements.
        /// </summary>
        internal static string CapacityMustBeGreaterThanOrEqualToCount
        {
            get
            {
                return ResourceManager.GetString("CapacityMustBeGreaterThanOrEqualToCount", resourceCulture);
            }
        }



        /// <summary>
        /// MoveToImmutable can only be performed when Count equals Capacity.
        /// </summary>
        internal static string CapacityMustEqualCountOnMove
        {
            get
            {
                return ResourceManager.GetString("CapacityMustEqualCountOnMove", resourceCulture);
            }
        }



        /// <summary>
        /// Collection was modified; enumeration operation may not execute.
        /// </summary>
        internal static string CollectionModifiedDuringEnumeration
        {
            get
            {
                return ResourceManager.GetString("CollectionModifiedDuringEnumeration", resourceCulture);
            }
        }



        /// <summary>
        /// An element with the same key but a different value already exists. Key: '{0}'
        /// </summary>
        internal static string DuplicateKey
        {
            get
            {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }


        internal static string FormatDuplicateKey(object arg1)
        {
            return string.Format(DuplicateKey, arg1);
        }


        /// <summary>
        /// This operation does not apply to an empty instance.
        /// </summary>
        internal static string InvalidEmptyOperation
        {
            get
            {
                return ResourceManager.GetString("InvalidEmptyOperation", resourceCulture);
            }
        }



        /// <summary>
        /// This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
        /// </summary>
        internal static string InvalidOperationOnDefaultArray
        {
            get
            {
                return ResourceManager.GetString("InvalidOperationOnDefaultArray", resourceCulture);
            }
        }



        /// <summary>
        /// Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.
        /// </summary>
        internal static string Arg_HTCapacityOverflow
        {
            get
            {
                return ResourceManager.GetString("Arg_HTCapacityOverflow", resourceCulture);
            }
        }



        /// <summary>
        /// Only single dimensional arrays are supported for the requested action.
        /// </summary>
        internal static string Arg_RankMultiDimNotSupported
        {
            get
            {
                return ResourceManager.GetString("Arg_RankMultiDimNotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// The lower bound of target array must be zero.
        /// </summary>
        internal static string Arg_NonZeroLowerBound
        {
            get
            {
                return ResourceManager.GetString("Arg_NonZeroLowerBound", resourceCulture);
            }
        }



        /// <summary>
        /// Destination array is not long enough to copy all the items in the collection. Check array index and length.
        /// </summary>
        internal static string Arg_ArrayPlusOffTooSmall
        {
            get
            {
                return ResourceManager.GetString("Arg_ArrayPlusOffTooSmall", resourceCulture);
            }
        }



        /// <summary>
        /// Target array type is not compatible with the type of items in the collection.
        /// </summary>
        internal static string Argument_IncompatibleArrayType
        {
            get
            {
                return ResourceManager.GetString("Argument_IncompatibleArrayType", resourceCulture);
            }
        }



        /// <summary>
        /// Non-negative number required.
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }



        /// <summary>
        /// The collection, in conjunction with its comparer, does not support the specified alternate key type.
        /// </summary>
        internal static string InvalidOperation_IncompatibleComparer
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_IncompatibleComparer", resourceCulture);
            }
        }

    }
}
