
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Console", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// The value must be less than the console's current maximum window size of {0} in that dimension. Note that this value depends on screen resolution and the console font.
        /// </summary>
        internal static string ArgumentOutOfRange_ConsoleWindowBufferSize
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_ConsoleWindowBufferSize", resourceCulture);
            }
        }


        internal static string FormatArgumentOutOfRange_ConsoleWindowBufferSize(object arg1)
        {
            return string.Format(ArgumentOutOfRange_ConsoleWindowBufferSize, arg1);
        }


        /// <summary>
        /// The new console window size would force the console buffer size to be too large. Maximum allowed is {0}.
        /// </summary>
        internal static string ArgumentOutOfRange_ConsoleWindowSize_Size
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_ConsoleWindowSize_Size", resourceCulture);
            }
        }


        internal static string FormatArgumentOutOfRange_ConsoleWindowSize_Size(object arg1)
        {
            return string.Format(ArgumentOutOfRange_ConsoleWindowSize_Size, arg1);
        }


        /// <summary>
        /// Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
        /// </summary>
        internal static string Argument_InvalidOffLen
        {
            get
            {
                return ResourceManager.GetString("Argument_InvalidOffLen", resourceCulture);
            }
        }



        /// <summary>
        /// Specified file length was too large for the file system.
        /// </summary>
        internal static string ArgumentOutOfRange_FileLengthTooBig
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_FileLengthTooBig", resourceCulture);
            }
        }



        /// <summary>
        /// Stream does not support seeking.
        /// </summary>
        internal static string NotSupported_UnseekableStream
        {
            get
            {
                return ResourceManager.GetString("NotSupported_UnseekableStream", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot access a closed file.
        /// </summary>
        internal static string ObjectDisposed_FileClosed
        {
            get
            {
                return ResourceManager.GetString("ObjectDisposed_FileClosed", resourceCulture);
            }
        }



        /// <summary>
        /// Stream does not support writing.
        /// </summary>
        internal static string NotSupported_UnwritableStream
        {
            get
            {
                return ResourceManager.GetString("NotSupported_UnwritableStream", resourceCulture);
            }
        }



        /// <summary>
        /// Stream does not support reading.
        /// </summary>
        internal static string NotSupported_UnreadableStream
        {
            get
            {
                return ResourceManager.GetString("NotSupported_UnreadableStream", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot create '{0}' because a file or directory with the same name already exists.
        /// </summary>
        internal static string IO_AlreadyExists_Name
        {
            get
            {
                return ResourceManager.GetString("IO_AlreadyExists_Name", resourceCulture);
            }
        }


        internal static string FormatIO_AlreadyExists_Name(object arg1)
        {
            return string.Format(IO_AlreadyExists_Name, arg1);
        }


        /// <summary>
        /// The file '{0}' already exists.
        /// </summary>
        internal static string IO_FileExists_Name
        {
            get
            {
                return ResourceManager.GetString("IO_FileExists_Name", resourceCulture);
            }
        }


        internal static string FormatIO_FileExists_Name(object arg1)
        {
            return string.Format(IO_FileExists_Name, arg1);
        }


        /// <summary>
        /// Unable to find the specified file.
        /// </summary>
        internal static string IO_FileNotFound
        {
            get
            {
                return ResourceManager.GetString("IO_FileNotFound", resourceCulture);
            }
        }



        /// <summary>
        /// Could not find file '{0}'.
        /// </summary>
        internal static string IO_FileNotFound_FileName
        {
            get
            {
                return ResourceManager.GetString("IO_FileNotFound_FileName", resourceCulture);
            }
        }


        internal static string FormatIO_FileNotFound_FileName(object arg1)
        {
            return string.Format(IO_FileNotFound_FileName, arg1);
        }


        /// <summary>
        /// Could not find a part of the path.
        /// </summary>
        internal static string IO_PathNotFound_NoPathName
        {
            get
            {
                return ResourceManager.GetString("IO_PathNotFound_NoPathName", resourceCulture);
            }
        }



        /// <summary>
        /// Could not find a part of the path '{0}'.
        /// </summary>
        internal static string IO_PathNotFound_Path
        {
            get
            {
                return ResourceManager.GetString("IO_PathNotFound_Path", resourceCulture);
            }
        }


        internal static string FormatIO_PathNotFound_Path(object arg1)
        {
            return string.Format(IO_PathNotFound_Path, arg1);
        }


        /// <summary>
        /// The specified file name or path is too long, or a component of the specified path is too long.
        /// </summary>
        internal static string IO_PathTooLong
        {
            get
            {
                return ResourceManager.GetString("IO_PathTooLong", resourceCulture);
            }
        }



        /// <summary>
        /// Access to the path is denied.
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_NoPathName
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_NoPathName", resourceCulture);
            }
        }



        /// <summary>
        /// Access to the path '{0}' is denied.
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_Path
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_Path", resourceCulture);
            }
        }


        internal static string FormatUnauthorizedAccess_IODenied_Path(object arg1)
        {
            return string.Format(UnauthorizedAccess_IODenied_Path, arg1);
        }


        /// <summary>
        /// The process cannot access the file '{0}' because it is being used by another process.
        /// </summary>
        internal static string IO_SharingViolation_File
        {
            get
            {
                return ResourceManager.GetString("IO_SharingViolation_File", resourceCulture);
            }
        }


        internal static string FormatIO_SharingViolation_File(object arg1)
        {
            return string.Format(IO_SharingViolation_File, arg1);
        }


        /// <summary>
        /// The process cannot access the file because it is being used by another process.
        /// </summary>
        internal static string IO_SharingViolation_NoFileName
        {
            get
            {
                return ResourceManager.GetString("IO_SharingViolation_NoFileName", resourceCulture);
            }
        }



        /// <summary>
        /// The ConsoleColor enum value was not defined on that enum. Please use a defined color from the enum.
        /// </summary>
        internal static string Arg_InvalidConsoleColor
        {
            get
            {
                return ResourceManager.GetString("Arg_InvalidConsoleColor", resourceCulture);
            }
        }



        /// <summary>
        /// There is no console.
        /// </summary>
        internal static string IO_NoConsole
        {
            get
            {
                return ResourceManager.GetString("IO_NoConsole", resourceCulture);
            }
        }



        /// <summary>
        /// The terminfo database is invalid.
        /// </summary>
        internal static string IO_TermInfoInvalid
        {
            get
            {
                return ResourceManager.GetString("IO_TermInfoInvalid", resourceCulture);
            }
        }



        /// <summary>
        /// The printf operation failed.
        /// </summary>
        internal static string InvalidOperation_PrintF
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_PrintF", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
        /// </summary>
        internal static string InvalidOperation_ConsoleReadKeyOnFile
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_ConsoleReadKeyOnFile", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot set window size when console output has been redirected.
        /// </summary>
        internal static string InvalidOperation_SetWindowSize
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_SetWindowSize", resourceCulture);
            }
        }



        /// <summary>
        /// The home directory of the current user could not be determined.
        /// </summary>
        internal static string PersistedFiles_NoHomeDirectory
        {
            get
            {
                return ResourceManager.GetString("PersistedFiles_NoHomeDirectory", resourceCulture);
            }
        }



        /// <summary>
        /// Console key values must be between 0 and 255 inclusive.
        /// </summary>
        internal static string ArgumentOutOfRange_ConsoleKey
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_ConsoleKey", resourceCulture);
            }
        }



        /// <summary>
        /// The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
        /// </summary>
        internal static string ArgumentOutOfRange_ConsoleBufferBoundaries
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_ConsoleBufferBoundaries", resourceCulture);
            }
        }



        /// <summary>
        /// The window position must be set such that the current window size fits within the console's buffer, and the numbers must not be negative.
        /// </summary>
        internal static string ArgumentOutOfRange_ConsoleWindowPos
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_ConsoleWindowPos", resourceCulture);
            }
        }



        /// <summary>
        /// Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek.
        /// </summary>
        internal static string InvalidOperation_ConsoleKeyAvailableOnFile
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_ConsoleKeyAvailableOnFile", resourceCulture);
            }
        }



        /// <summary>
        /// The console buffer size must not be less than the current size and position of the console window, nor greater than or equal to short.MaxValue.
        /// </summary>
        internal static string ArgumentOutOfRange_ConsoleBufferLessThanWindowSize
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_ConsoleBufferLessThanWindowSize", resourceCulture);
            }
        }



        /// <summary>
        /// The cursor size is invalid. It must be a percentage between 1 and 100.
        /// </summary>
        internal static string ArgumentOutOfRange_CursorSize
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_CursorSize", resourceCulture);
            }
        }



        /// <summary>
        /// The frequency must be between {0} and {1}.
        /// </summary>
        internal static string ArgumentOutOfRange_BeepFrequency
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_BeepFrequency", resourceCulture);
            }
        }


        internal static string FormatArgumentOutOfRange_BeepFrequency(object arg1, object arg2)
        {
            return string.Format(ArgumentOutOfRange_BeepFrequency, arg1, arg2);
        }


        /// <summary>
        /// Index and count must refer to a location within the buffer.
        /// </summary>
        internal static string ArgumentOutOfRange_IndexCountBuffer
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexCountBuffer", resourceCulture);
            }
        }



        /// <summary>
        /// Index and count must refer to a location within the string.
        /// </summary>
        internal static string ArgumentOutOfRange_IndexCount
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexCount", resourceCulture);
            }
        }



        /// <summary>
        /// Index was out of range. Must be non-negative and less than the size of the collection.
        /// </summary>
        internal static string ArgumentOutOfRange_IndexMustBeLess
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexMustBeLess", resourceCulture);
            }
        }



        /// <summary>
        /// Index was out of range. Must be non-negative and less than or equal to the size of the collection.
        /// </summary>
        internal static string ArgumentOutOfRange_IndexMustBeLessOrEqual
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexMustBeLessOrEqual", resourceCulture);
            }
        }



        /// <summary>
        /// The output byte buffer is too small to contain the encoded data, encoding '{0}' fallback '{1}'.
        /// </summary>
        internal static string Argument_EncodingConversionOverflowBytes
        {
            get
            {
                return ResourceManager.GetString("Argument_EncodingConversionOverflowBytes", resourceCulture);
            }
        }


        internal static string FormatArgument_EncodingConversionOverflowBytes(object arg1, object arg2)
        {
            return string.Format(Argument_EncodingConversionOverflowBytes, arg1, arg2);
        }


        /// <summary>
        /// The output char buffer is too small to contain the decoded characters, encoding '{0}' fallback '{1}'.
        /// </summary>
        internal static string Argument_EncodingConversionOverflowChars
        {
            get
            {
                return ResourceManager.GetString("Argument_EncodingConversionOverflowChars", resourceCulture);
            }
        }


        internal static string FormatArgument_EncodingConversionOverflowChars(object arg1, object arg2)
        {
            return string.Format(Argument_EncodingConversionOverflowChars, arg1, arg2);
        }


        /// <summary>
        /// Too many characters. The resulting number of bytes is larger than what can be returned as an int.
        /// </summary>
        internal static string ArgumentOutOfRange_GetByteCountOverflow
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_GetByteCountOverflow", resourceCulture);
            }
        }



        /// <summary>
        /// Too many bytes. The resulting number of chars is larger than what can be returned as an int.
        /// </summary>
        internal static string ArgumentOutOfRange_GetCharCountOverflow
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_GetCharCountOverflow", resourceCulture);
            }
        }



        /// <summary>
        /// String contains invalid Unicode code points.
        /// </summary>
        internal static string Argument_InvalidCharSequenceNoIndex
        {
            get
            {
                return ResourceManager.GetString("Argument_InvalidCharSequenceNoIndex", resourceCulture);
            }
        }



        /// <summary>
        /// The path '{0}' is too long, or a component of the specified path is too long.
        /// </summary>
        internal static string IO_PathTooLong_Path
        {
            get
            {
                return ResourceManager.GetString("IO_PathTooLong_Path", resourceCulture);
            }
        }


        internal static string FormatIO_PathTooLong_Path(object arg1)
        {
            return string.Format(IO_PathTooLong_Path, arg1);
        }


        /// <summary>
        /// The terminfo database has an invalid magic number: '{0}'.
        /// </summary>
        internal static string IO_TermInfoInvalidMagicNumber
        {
            get
            {
                return ResourceManager.GetString("IO_TermInfoInvalidMagicNumber", resourceCulture);
            }
        }


        internal static string FormatIO_TermInfoInvalidMagicNumber(object arg1)
        {
            return string.Format(IO_TermInfoInvalidMagicNumber, arg1);
        }


        /// <summary>
        /// System.Console is not supported on this platform.
        /// </summary>
        internal static string PlatformNotSupported_SystemConsole
        {
            get
            {
                return ResourceManager.GetString("PlatformNotSupported_SystemConsole", resourceCulture);
            }
        }

    }
}
