
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Extensions.Configuration", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// A configuration source is not registered. Please register one before setting a value.
        /// </summary>
        internal static string Error_NoSources
        {
            get
            {
                return ResourceManager.GetString("Error_NoSources", resourceCulture);
            }
        }



        /// <summary>
        /// Null is not a valid value for '{0}'.
        /// </summary>
        internal static string InvalidNullArgument
        {
            get
            {
                return ResourceManager.GetString("InvalidNullArgument", resourceCulture);
            }
        }


        internal static string FormatInvalidNullArgument(object arg1)
        {
            return string.Format(InvalidNullArgument, arg1);
        }


        /// <summary>
        /// StreamConfigurationProviders cannot be loaded more than once.
        /// </summary>
        internal static string StreamConfigurationProvidersAlreadyLoaded
        {
            get
            {
                return ResourceManager.GetString("StreamConfigurationProvidersAlreadyLoaded", resourceCulture);
            }
        }



        /// <summary>
        /// Source.Stream cannot be null.
        /// </summary>
        internal static string StreamConfigurationSourceStreamCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("StreamConfigurationSourceStreamCannotBeNull", resourceCulture);
            }
        }

    }
}
