
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project. \
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Collections", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// The lower bound of target array must be zero.
        /// </summary>
        internal static string Arg_NonZeroLowerBound
        {
            get
            {
                return ResourceManager.GetString("Arg_NonZeroLowerBound", resourceCulture);
            }
        }



        /// <summary>
        /// The value '{0}' is not of type '{1}' and cannot be used in this generic collection.
        /// </summary>
        internal static string Arg_WrongType
        {
            get
            {
                return ResourceManager.GetString("Arg_WrongType", resourceCulture);
            }
        }


        internal static string FormatArg_WrongType(object arg1, object arg2)
        {
            return string.Format(Arg_WrongType, arg1, arg2);
        }


        /// <summary>
        /// Destination array is not long enough to copy all the items in the collection. Check array index and length.
        /// </summary>
        internal static string Arg_ArrayPlusOffTooSmall
        {
            get
            {
                return ResourceManager.GetString("Arg_ArrayPlusOffTooSmall", resourceCulture);
            }
        }



        /// <summary>
        /// capacity was less than the current size.
        /// </summary>
        internal static string ArgumentOutOfRange_SmallCapacity
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_SmallCapacity", resourceCulture);
            }
        }



        /// <summary>
        /// Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
        /// </summary>
        internal static string Argument_InvalidOffLen
        {
            get
            {
                return ResourceManager.GetString("Argument_InvalidOffLen", resourceCulture);
            }
        }



        /// <summary>
        /// An item with the same key has already been added. Key: {0}
        /// </summary>
        internal static string Argument_AddingDuplicate
        {
            get
            {
                return ResourceManager.GetString("Argument_AddingDuplicate", resourceCulture);
            }
        }


        internal static string FormatArgument_AddingDuplicate(object arg1)
        {
            return string.Format(Argument_AddingDuplicate, arg1);
        }


        /// <summary>
        /// Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
        /// </summary>
        internal static string InvalidOperation_ConcurrentOperationsNotSupported
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_ConcurrentOperationsNotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// Queue empty.
        /// </summary>
        internal static string InvalidOperation_EmptyQueue
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_EmptyQueue", resourceCulture);
            }
        }



        /// <summary>
        /// Enumeration has either not started or has already finished.
        /// </summary>
        internal static string InvalidOperation_EnumOpCantHappen
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_EnumOpCantHappen", resourceCulture);
            }
        }



        /// <summary>
        /// Collection was modified after the enumerator was instantiated.
        /// </summary>
        internal static string InvalidOperation_EnumFailedVersion
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_EnumFailedVersion", resourceCulture);
            }
        }



        /// <summary>
        /// Stack empty.
        /// </summary>
        internal static string InvalidOperation_EmptyStack
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_EmptyStack", resourceCulture);
            }
        }



        /// <summary>
        /// Enumeration has not started. Call MoveNext.
        /// </summary>
        internal static string InvalidOperation_EnumNotStarted
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_EnumNotStarted", resourceCulture);
            }
        }



        /// <summary>
        /// Enumeration already finished.
        /// </summary>
        internal static string InvalidOperation_EnumEnded
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_EnumEnded", resourceCulture);
            }
        }



        /// <summary>
        /// Mutating a key collection derived from a dictionary is not allowed.
        /// </summary>
        internal static string NotSupported_KeyCollectionSet
        {
            get
            {
                return ResourceManager.GetString("NotSupported_KeyCollectionSet", resourceCulture);
            }
        }



        /// <summary>
        /// Mutating a value collection derived from a dictionary is not allowed.
        /// </summary>
        internal static string NotSupported_ValueCollectionSet
        {
            get
            {
                return ResourceManager.GetString("NotSupported_ValueCollectionSet", resourceCulture);
            }
        }



        /// <summary>
        /// Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.
        /// </summary>
        internal static string Arg_HTCapacityOverflow
        {
            get
            {
                return ResourceManager.GetString("Arg_HTCapacityOverflow", resourceCulture);
            }
        }



        /// <summary>
        /// Insufficient space in the target location to copy the information.
        /// </summary>
        internal static string Arg_InsufficientSpace
        {
            get
            {
                return ResourceManager.GetString("Arg_InsufficientSpace", resourceCulture);
            }
        }



        /// <summary>
        /// Only single dimensional arrays are supported for the requested action.
        /// </summary>
        internal static string Arg_RankMultiDimNotSupported
        {
            get
            {
                return ResourceManager.GetString("Arg_RankMultiDimNotSupported", resourceCulture);
            }
        }



        /// <summary>
        /// Target array type is not compatible with the type of items in the collection.
        /// </summary>
        internal static string Argument_IncompatibleArrayType
        {
            get
            {
                return ResourceManager.GetString("Argument_IncompatibleArrayType", resourceCulture);
            }
        }



        /// <summary>
        /// Must be less than or equal to the size of the collection.
        /// </summary>
        internal static string ArgumentOutOfRange_BiggerThanCollection
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_BiggerThanCollection", resourceCulture);
            }
        }



        /// <summary>
        /// Index was out of range. Must be non-negative and less than the size of the collection.
        /// </summary>
        internal static string ArgumentOutOfRange_IndexMustBeLess
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexMustBeLess", resourceCulture);
            }
        }



        /// <summary>
        /// Index was out of range. Must be non-negative and less than or equal to the size of the collection.
        /// </summary>
        internal static string ArgumentOutOfRange_IndexMustBeLessOrEqual
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexMustBeLessOrEqual", resourceCulture);
            }
        }



        /// <summary>
        /// The LinkedList node does not belong to current LinkedList.
        /// </summary>
        internal static string ExternalLinkedListNode
        {
            get
            {
                return ResourceManager.GetString("ExternalLinkedListNode", resourceCulture);
            }
        }



        /// <summary>
        /// The LinkedList is empty.
        /// </summary>
        internal static string LinkedListEmpty
        {
            get
            {
                return ResourceManager.GetString("LinkedListEmpty", resourceCulture);
            }
        }



        /// <summary>
        /// The LinkedList node already belongs to a LinkedList.
        /// </summary>
        internal static string LinkedListNodeIsAttached
        {
            get
            {
                return ResourceManager.GetString("LinkedListNodeIsAttached", resourceCulture);
            }
        }



        /// <summary>
        /// This operation is not supported on SortedList nested types because they require modifying the original SortedList.
        /// </summary>
        internal static string NotSupported_SortedListNestedWrite
        {
            get
            {
                return ResourceManager.GetString("NotSupported_SortedListNestedWrite", resourceCulture);
            }
        }



        /// <summary>
        /// Must be less than or equal to upperValue.
        /// </summary>
        internal static string SortedSet_LowerValueGreaterThanUpperValue
        {
            get
            {
                return ResourceManager.GetString("SortedSet_LowerValueGreaterThanUpperValue", resourceCulture);
            }
        }



        /// <summary>
        /// OnDeserialization method was called while the object was not being deserialized.
        /// </summary>
        internal static string Serialization_InvalidOnDeser
        {
            get
            {
                return ResourceManager.GetString("Serialization_InvalidOnDeser", resourceCulture);
            }
        }



        /// <summary>
        /// The serialized Count information doesn't match the number of items.
        /// </summary>
        internal static string Serialization_MismatchedCount
        {
            get
            {
                return ResourceManager.GetString("Serialization_MismatchedCount", resourceCulture);
            }
        }



        /// <summary>
        /// The keys for this dictionary are missing.
        /// </summary>
        internal static string Serialization_MissingKeys
        {
            get
            {
                return ResourceManager.GetString("Serialization_MissingKeys", resourceCulture);
            }
        }



        /// <summary>
        /// The values for this dictionary are missing.
        /// </summary>
        internal static string Serialization_MissingValues
        {
            get
            {
                return ResourceManager.GetString("Serialization_MissingValues", resourceCulture);
            }
        }



        /// <summary>
        /// The given key '{0}' was not present in the dictionary.
        /// </summary>
        internal static string Arg_KeyNotFoundWithKey
        {
            get
            {
                return ResourceManager.GetString("Arg_KeyNotFoundWithKey", resourceCulture);
            }
        }


        internal static string FormatArg_KeyNotFoundWithKey(object arg1)
        {
            return string.Format(Arg_KeyNotFoundWithKey, arg1);
        }
    }
}
